// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_k1_transform (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s0_a_dout,
        s0_a_empty_n,
        s0_a_read,
        s0_a_num_data_valid,
        s0_a_fifo_cap,
        s1_din,
        s1_full_n,
        s1_write,
        s1_num_data_valid,
        s1_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [19:0] s0_a_dout;
input   s0_a_empty_n;
output   s0_a_read;
input  [8:0] s0_a_num_data_valid;
input  [8:0] s0_a_fifo_cap;
output  [19:0] s1_din;
input   s1_full_n;
output   s1_write;
input  [31:0] s1_num_data_valid;
input  [31:0] s1_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg s0_a_read;
reg s1_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln148_fu_499_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s0_a_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    s1_blk_n;
wire   [19:0] add_ln152_fu_337_p2;
reg   [19:0] add_ln152_reg_669;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [0:0] and_ln152_3_fu_457_p2;
reg   [0:0] and_ln152_3_reg_674;
wire   [0:0] or_ln152_1_fu_487_p2;
reg   [0:0] or_ln152_1_reg_679;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] k1_fu_114;
wire   [15:0] k_fu_493_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_k1_load;
wire    ap_block_pp0_stage0;
reg   [19:0] x22_fu_118;
reg   [19:0] ap_sig_allocacmp_x22_load;
reg   [19:0] x2_fu_122;
reg   [19:0] ap_sig_allocacmp_x2_1;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [51:0] tmp_fu_171_p3;
wire   [52:0] shl_ln151_1_fu_163_p3;
wire   [50:0] shl_ln151_4_fu_187_p3;
wire  signed [52:0] sext_ln151_2_fu_195_p1;
wire  signed [52:0] sext_ln151_fu_179_p1;
wire   [52:0] sub_ln151_fu_199_p2;
wire  signed [53:0] sext_ln151_3_fu_205_p1;
wire  signed [53:0] sext_ln151_1_fu_183_p1;
wire   [53:0] add_ln151_fu_209_p2;
wire   [29:0] acc_fu_223_p4;
wire  signed [30:0] sext_ln151_4_fu_233_p1;
wire  signed [30:0] acc_1_fu_237_p2;
wire   [0:0] tmp_24_fu_215_p3;
wire   [0:0] tmp_25_fu_247_p3;
wire   [0:0] xor_ln151_fu_255_p2;
wire   [0:0] or_ln151_1_fu_261_p2;
wire   [0:0] xor_ln151_1_fu_267_p2;
wire   [0:0] xor_ln151_2_fu_273_p2;
wire   [0:0] or_ln151_fu_279_p2;
wire   [0:0] and_ln151_fu_285_p2;
wire  signed [35:0] sext_ln151_5_fu_243_p1;
wire   [35:0] acc_2_fu_291_p3;
wire   [0:0] tmp_27_fu_317_p3;
wire   [19:0] trunc_ln_fu_307_p4;
wire   [19:0] zext_ln152_fu_333_p1;
wire   [0:0] tmp_29_fu_343_p3;
wire   [0:0] tmp_28_fu_325_p3;
wire   [0:0] xor_ln152_fu_351_p2;
wire   [4:0] tmp_27_i_fu_371_p3;
wire   [5:0] tmp_28_i_fu_385_p3;
wire   [0:0] and_ln152_fu_357_p2;
wire   [0:0] icmp_ln152_1_fu_393_p2;
wire   [0:0] icmp_ln152_2_fu_399_p2;
wire   [0:0] tmp_30_fu_363_p3;
wire   [0:0] icmp_ln152_fu_379_p2;
wire   [0:0] xor_ln152_1_fu_413_p2;
wire   [0:0] and_ln152_1_fu_419_p2;
wire   [0:0] select_ln152_fu_405_p3;
wire   [0:0] xor_ln152_2_fu_439_p2;
wire   [0:0] tmp_26_fu_299_p3;
wire   [0:0] or_ln152_fu_445_p2;
wire   [0:0] xor_ln152_3_fu_451_p2;
wire   [0:0] select_ln152_1_fu_425_p3;
wire   [0:0] and_ln152_2_fu_433_p2;
wire   [0:0] and_ln152_4_fu_463_p2;
wire   [0:0] or_ln152_2_fu_469_p2;
wire   [0:0] xor_ln152_4_fu_475_p2;
wire   [0:0] and_ln152_5_fu_481_p2;
wire   [19:0] select_ln152_2_fu_520_p3;
wire   [19:0] x_fu_527_p3;
wire   [19:0] sub_ln111_fu_541_p2;
wire   [0:0] tmp_32_fu_547_p3;
wire   [0:0] tmp_31_fu_533_p3;
wire   [0:0] and_ln111_fu_563_p2;
wire   [0:0] xor_ln111_fu_569_p2;
wire   [19:0] x_1_fu_583_p2;
wire   [19:0] x_1_fu_583_p7;
wire   [1:0] x_1_fu_583_p8;
wire   [19:0] x_1_fu_583_p9;
wire   [0:0] tmp_33_fu_607_p3;
wire   [0:0] icmp_ln116_fu_615_p2;
wire   [0:0] or_ln115_fu_629_p2;
wire   [16:0] select_ln115_fu_621_p3;
wire   [16:0] trunc_ln114_fu_603_p1;
wire   [16:0] y_fu_635_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_119;
reg    ap_condition_131;
wire  signed [1:0] x_1_fu_583_p1;
wire   [1:0] x_1_fu_583_p3;
wire   [1:0] x_1_fu_583_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 k1_fu_114 = 16'd0;
#0 x22_fu_118 = 20'd0;
#0 x2_fu_122 = 20'd0;
end

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U11(
    .din0(x_1_fu_583_p2),
    .din1(x_fu_527_p3),
    .din2(sub_ln111_fu_541_p2),
    .def(x_1_fu_583_p7),
    .sel(x_1_fu_583_p8),
    .dout(x_1_fu_583_p9)
);

top_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_119)) begin
        k1_fu_114 <= k_fu_493_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_131)) begin
    x22_fu_118 <= ap_sig_allocacmp_x2_1;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_131)) begin
    x2_fu_122 <= s0_a_dout;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln152_reg_669 <= add_ln152_fu_337_p2;
        and_ln152_3_reg_674 <= and_ln152_3_fu_457_p2;
        or_ln152_1_reg_679 <= or_ln152_1_fu_487_p2;
    end
end

always @ (*) begin
    if (((icmp_ln148_fu_499_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k1_load = 16'd0;
    end else begin
        ap_sig_allocacmp_k1_load = k1_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x22_load = 20'd0;
    end else begin
        ap_sig_allocacmp_x22_load = x22_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x2_1 = 20'd0;
    end else begin
        ap_sig_allocacmp_x2_1 = x2_fu_122;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s0_a_blk_n = s0_a_empty_n;
    end else begin
        s0_a_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s0_a_read = 1'b1;
    end else begin
        s0_a_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_blk_n = s1_full_n;
    end else begin
        s1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s1_write = 1'b1;
    end else begin
        s1_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_237_p2 = ($signed(sext_ln151_4_fu_233_p1) + $signed(31'd0));

assign acc_2_fu_291_p3 = ((and_ln151_fu_285_p2[0:0] == 1'b1) ? 36'd34359738367 : sext_ln151_5_fu_243_p1);

assign acc_fu_223_p4 = {{add_ln151_fu_209_p2[53:24]}};

assign add_ln151_fu_209_p2 = ($signed(sext_ln151_3_fu_205_p1) + $signed(sext_ln151_1_fu_183_p1));

assign add_ln152_fu_337_p2 = (trunc_ln_fu_307_p4 + zext_ln152_fu_333_p1);

assign and_ln111_fu_563_p2 = (tmp_32_fu_547_p3 & tmp_31_fu_533_p3);

assign and_ln151_fu_285_p2 = (xor_ln151_fu_255_p2 & or_ln151_fu_279_p2);

assign and_ln152_1_fu_419_p2 = (xor_ln152_1_fu_413_p2 & icmp_ln152_fu_379_p2);

assign and_ln152_2_fu_433_p2 = (icmp_ln152_1_fu_393_p2 & and_ln152_fu_357_p2);

assign and_ln152_3_fu_457_p2 = (xor_ln152_3_fu_451_p2 & or_ln152_fu_445_p2);

assign and_ln152_4_fu_463_p2 = (tmp_29_fu_343_p3 & select_ln152_1_fu_425_p3);

assign and_ln152_5_fu_481_p2 = (xor_ln152_4_fu_475_p2 & tmp_26_fu_299_p3);

assign and_ln152_fu_357_p2 = (xor_ln152_fu_351_p2 & tmp_28_fu_325_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((s1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((s1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((s1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((s1_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (s0_a_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_119 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_131 = ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign icmp_ln116_fu_615_p2 = (($signed(x_1_fu_583_p9) > $signed(20'd122880)) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_499_p2 = ((ap_sig_allocacmp_k1_load == 16'd65535) ? 1'b1 : 1'b0);

assign icmp_ln152_1_fu_393_p2 = ((tmp_28_i_fu_385_p3 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln152_2_fu_399_p2 = ((tmp_28_i_fu_385_p3 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln152_fu_379_p2 = ((tmp_27_i_fu_371_p3 == 5'd31) ? 1'b1 : 1'b0);

assign k_fu_493_p2 = (ap_sig_allocacmp_k1_load + 16'd1);

assign or_ln115_fu_629_p2 = (tmp_33_fu_607_p3 | icmp_ln116_fu_615_p2);

assign or_ln151_1_fu_261_p2 = (xor_ln151_fu_255_p2 | tmp_25_fu_247_p3);

assign or_ln151_fu_279_p2 = (xor_ln151_2_fu_273_p2 | tmp_25_fu_247_p3);

assign or_ln152_1_fu_487_p2 = (and_ln152_5_fu_481_p2 | and_ln152_3_fu_457_p2);

assign or_ln152_2_fu_469_p2 = (and_ln152_4_fu_463_p2 | and_ln152_2_fu_433_p2);

assign or_ln152_fu_445_p2 = (xor_ln152_2_fu_439_p2 | tmp_29_fu_343_p3);

assign s1_din = y_fu_635_p3;

assign select_ln115_fu_621_p3 = ((tmp_33_fu_607_p3[0:0] == 1'b1) ? 17'd0 : 17'd122880);

assign select_ln152_1_fu_425_p3 = ((and_ln152_fu_357_p2[0:0] == 1'b1) ? and_ln152_1_fu_419_p2 : icmp_ln152_1_fu_393_p2);

assign select_ln152_2_fu_520_p3 = ((and_ln152_3_reg_674[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln152_fu_405_p3 = ((and_ln152_fu_357_p2[0:0] == 1'b1) ? icmp_ln152_1_fu_393_p2 : icmp_ln152_2_fu_399_p2);

assign sext_ln151_1_fu_183_p1 = $signed(shl_ln151_1_fu_163_p3);

assign sext_ln151_2_fu_195_p1 = $signed(shl_ln151_4_fu_187_p3);

assign sext_ln151_3_fu_205_p1 = $signed(sub_ln151_fu_199_p2);

assign sext_ln151_4_fu_233_p1 = $signed(acc_fu_223_p4);

assign sext_ln151_5_fu_243_p1 = acc_1_fu_237_p2;

assign sext_ln151_fu_179_p1 = $signed(tmp_fu_171_p3);

assign shl_ln151_1_fu_163_p3 = {{s0_a_dout}, {33'd0}};

assign shl_ln151_4_fu_187_p3 = {{ap_sig_allocacmp_x22_load}, {31'd0}};

assign start_out = real_start;

assign sub_ln111_fu_541_p2 = (20'd0 - x_fu_527_p3);

assign sub_ln151_fu_199_p2 = ($signed(sext_ln151_2_fu_195_p1) - $signed(sext_ln151_fu_179_p1));

assign tmp_24_fu_215_p3 = add_ln151_fu_209_p2[32'd53];

assign tmp_25_fu_247_p3 = acc_1_fu_237_p2[32'd30];

assign tmp_26_fu_299_p3 = acc_2_fu_291_p3[32'd35];

assign tmp_27_fu_317_p3 = acc_2_fu_291_p3[32'd9];

assign tmp_27_i_fu_371_p3 = {{acc_2_fu_291_p3[35:31]}};

assign tmp_28_fu_325_p3 = acc_2_fu_291_p3[32'd29];

assign tmp_28_i_fu_385_p3 = {{acc_2_fu_291_p3[35:30]}};

assign tmp_29_fu_343_p3 = add_ln152_fu_337_p2[32'd19];

assign tmp_30_fu_363_p3 = acc_2_fu_291_p3[32'd30];

assign tmp_31_fu_533_p3 = x_fu_527_p3[32'd19];

assign tmp_32_fu_547_p3 = sub_ln111_fu_541_p2[32'd19];

assign tmp_33_fu_607_p3 = x_1_fu_583_p9[32'd19];

assign tmp_fu_171_p3 = {{ap_sig_allocacmp_x2_1}, {32'd0}};

assign trunc_ln114_fu_603_p1 = x_1_fu_583_p9[16:0];

assign trunc_ln_fu_307_p4 = {{acc_2_fu_291_p3[29:10]}};

assign x_1_fu_583_p2 = ((tmp_32_fu_547_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign x_1_fu_583_p7 = 'bx;

assign x_1_fu_583_p8 = {{and_ln111_fu_563_p2}, {xor_ln111_fu_569_p2}};

assign x_fu_527_p3 = ((or_ln152_1_reg_679[0:0] == 1'b1) ? select_ln152_2_fu_520_p3 : add_ln152_reg_669);

assign xor_ln111_fu_569_p2 = (tmp_31_fu_533_p3 ^ 1'd1);

assign xor_ln151_1_fu_267_p2 = (tmp_24_fu_215_p3 ^ or_ln151_1_fu_261_p2);

assign xor_ln151_2_fu_273_p2 = (xor_ln151_1_fu_267_p2 ^ 1'd1);

assign xor_ln151_fu_255_p2 = (tmp_24_fu_215_p3 ^ 1'd1);

assign xor_ln152_1_fu_413_p2 = (tmp_30_fu_363_p3 ^ 1'd1);

assign xor_ln152_2_fu_439_p2 = (select_ln152_fu_405_p3 ^ 1'd1);

assign xor_ln152_3_fu_451_p2 = (tmp_26_fu_299_p3 ^ 1'd1);

assign xor_ln152_4_fu_475_p2 = (or_ln152_2_fu_469_p2 ^ 1'd1);

assign xor_ln152_fu_351_p2 = (tmp_29_fu_343_p3 ^ 1'd1);

assign y_fu_635_p3 = ((or_ln115_fu_629_p2[0:0] == 1'b1) ? select_ln115_fu_621_p3 : trunc_ln114_fu_603_p1);

assign zext_ln152_fu_333_p1 = tmp_27_fu_317_p3;

endmodule //top_kernel_k1_transform
