-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ag_pipeline_baseline_extract_edges_and_profile is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    in_r_ce0 : OUT STD_LOGIC;
    in_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_r_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    in_r_ce1 : OUT STD_LOGIC;
    in_r_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    profile_out_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    profile_out_ce0 : OUT STD_LOGIC;
    profile_out_we0 : OUT STD_LOGIC;
    profile_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of ag_pipeline_baseline_extract_edges_and_profile is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv17_100 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal c_1_reg_754 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln56_fu_195_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln56_reg_763 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvars_iv_next32_fu_199_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvars_iv_next32_reg_768 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_fu_205_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_reg_776 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln59_fu_217_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln59_reg_786 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal in_load_reg_811 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_load_1_reg_817 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln59_1_fu_325_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln59_1_reg_823 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln59_2_fu_331_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln59_2_reg_828 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal in_load_4_reg_854 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_load_5_reg_859 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln61_fu_670_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_864 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal col_acc_2_fu_739_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal r_reg_156 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln56_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_acc_reg_168 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln59_2_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln58_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln59_3_fu_242_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln59_fu_258_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln59_1_fu_270_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln59_4_fu_344_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln59_5_fu_356_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln60_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln60_1_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_66 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal in_r_ce1_local : STD_LOGIC;
    signal in_r_address1_local : STD_LOGIC_VECTOR (13 downto 0);
    signal in_r_ce0_local : STD_LOGIC;
    signal in_r_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal profile_out_we0_local : STD_LOGIC;
    signal profile_out_ce0_local : STD_LOGIC;
    signal tmp_1_fu_223_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_235_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_9_fu_251_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_s_fu_263_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln59_fu_275_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln59_1_fu_278_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln59_fu_281_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln_fu_287_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln59_3_fu_299_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln59_2_fu_295_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln59_1_fu_303_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln59_1_fu_309_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln59_4_fu_317_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln59_5_fu_321_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_6_fu_337_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_7_fu_349_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_5_fu_361_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_8_fu_372_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln59_6_fu_383_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln59_3_fu_386_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln59_7_fu_391_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln59_2_fu_394_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3_fu_420_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_10_fu_412_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_1_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_400_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln59_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln59_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln59_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln59_1_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln59_1_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln59_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln59_1_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln59_2_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln59_fu_478_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal gx_fu_408_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1_fu_500_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln60_1_fu_511_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln60_fu_508_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln60_fu_515_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln60_2_fu_521_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln60_1_fu_524_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln60_3_fu_530_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln60_1_fu_540_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln60_fu_534_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln60_4_fu_548_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln60_1_fu_552_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln60_2_fu_558_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_4_fu_584_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_12_fu_576_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_1_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_564_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln60_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln60_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln60_1_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln60_1_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln60_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln60_1_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln60_2_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_fu_642_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal gy_fu_572_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal gy_1_fu_656_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal gx_1_fu_492_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln61_fu_664_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln61_fu_680_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln61_fu_676_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln61_fu_687_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_13_fu_693_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_705_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln61_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln61_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln61_1_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln61_1_fu_731_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_acc_1_fu_701_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    c_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                c_fu_66 <= ap_const_lv7_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln58_fu_211_p2 = ap_const_lv1_1))) then 
                c_fu_66 <= indvars_iv_next32_reg_768;
            end if; 
        end if;
    end process;

    col_acc_reg_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                col_acc_reg_168 <= col_acc_2_fu_739_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln56_fu_189_p2 = ap_const_lv1_0))) then 
                col_acc_reg_168 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    r_reg_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                r_reg_156 <= add_ln59_2_reg_828;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln56_fu_189_p2 = ap_const_lv1_0))) then 
                r_reg_156 <= ap_const_lv7_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln59_2_reg_828 <= add_ln59_2_fu_331_p2;
                sub_ln59_1_reg_823 <= sub_ln59_1_fu_325_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln59_reg_786 <= add_ln59_fu_217_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                c_1_reg_754 <= c_fu_66;
                empty_reg_776 <= empty_fu_205_p2;
                indvars_iv_next32_reg_768 <= indvars_iv_next32_fu_199_p2;
                    zext_ln56_reg_763(6 downto 0) <= zext_ln56_fu_195_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                icmp_ln61_reg_864 <= icmp_ln61_fu_670_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                in_load_1_reg_817 <= in_r_q0;
                in_load_reg_811 <= in_r_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                in_load_4_reg_854 <= in_r_q1;
                in_load_5_reg_859 <= in_r_q0;
            end if;
        end if;
    end process;
    zext_ln56_reg_763(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln56_fu_189_p2, icmp_ln58_fu_211_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln56_fu_189_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln58_fu_211_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln59_1_fu_303_p2 <= std_logic_vector(signed(sext_ln59_3_fu_299_p1) + signed(sext_ln59_2_fu_295_p1));
    add_ln59_2_fu_331_p2 <= std_logic_vector(unsigned(r_reg_156) + unsigned(ap_const_lv7_1));
    add_ln59_3_fu_386_p2 <= std_logic_vector(unsigned(sub_ln59_1_reg_823) + unsigned(sext_ln59_6_fu_383_p1));
    add_ln59_fu_217_p2 <= std_logic_vector(unsigned(r_reg_156) + unsigned(ap_const_lv7_7F));
    add_ln60_1_fu_524_p2 <= std_logic_vector(unsigned(add_ln60_fu_515_p2) + unsigned(sext_ln60_2_fu_521_p1));
    add_ln60_fu_515_p2 <= std_logic_vector(signed(sext_ln60_1_fu_511_p1) + signed(sext_ln60_fu_508_p1));
    add_ln61_fu_687_p2 <= std_logic_vector(unsigned(select_ln61_fu_680_p3) + unsigned(sext_ln61_fu_676_p1));
    and_ln59_1_fu_472_p2 <= (tmp_fu_400_p3 and or_ln59_1_fu_466_p2);
    and_ln59_fu_454_p2 <= (xor_ln59_fu_448_p2 and or_ln59_fu_442_p2);
    and_ln60_1_fu_636_p2 <= (tmp_11_fu_564_p3 and or_ln60_1_fu_630_p2);
    and_ln60_fu_618_p2 <= (xor_ln60_fu_612_p2 and or_ln60_fu_606_p2);
    and_ln61_fu_719_p2 <= (xor_ln61_fu_713_p2 and tmp_14_fu_705_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln56_fu_189_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln56_fu_189_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln56_fu_189_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln56_fu_189_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    col_acc_1_fu_701_p1 <= add_ln61_fu_687_p2(16 - 1 downto 0);
    col_acc_2_fu_739_p3 <= 
        select_ln61_1_fu_731_p3 when (xor_ln61_1_fu_725_p2(0) = '1') else 
        col_acc_1_fu_701_p1;
    empty_fu_205_p2 <= std_logic_vector(unsigned(c_fu_66) + unsigned(ap_const_lv7_7F));
    gx_1_fu_492_p3 <= 
        select_ln59_fu_478_p3 when (or_ln59_2_fu_486_p2(0) = '1') else 
        gx_fu_408_p1;
    gx_fu_408_p1 <= sub_ln59_2_fu_394_p2(16 - 1 downto 0);
    gy_1_fu_656_p3 <= 
        select_ln60_fu_642_p3 when (or_ln60_2_fu_650_p2(0) = '1') else 
        gy_fu_572_p1;
    gy_fu_572_p1 <= sub_ln60_2_fu_558_p2(16 - 1 downto 0);
    icmp_ln56_fu_189_p2 <= "1" when (c_fu_66 = ap_const_lv7_7F) else "0";
    icmp_ln58_fu_211_p2 <= "1" when (r_reg_156 = ap_const_lv7_7F) else "0";
    icmp_ln59_1_fu_436_p2 <= "0" when (tmp_3_fu_420_p4 = ap_const_lv3_0) else "1";
    icmp_ln59_fu_430_p2 <= "0" when (tmp_3_fu_420_p4 = ap_const_lv3_7) else "1";
    icmp_ln60_1_fu_600_p2 <= "0" when (tmp_4_fu_584_p4 = ap_const_lv3_0) else "1";
    icmp_ln60_fu_594_p2 <= "0" when (tmp_4_fu_584_p4 = ap_const_lv3_7) else "1";
    icmp_ln61_fu_670_p2 <= "0" when (or_ln61_fu_664_p2 = ap_const_lv16_0) else "1";
    in_r_address0 <= in_r_address0_local;

    in_r_address0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, zext_ln59_3_fu_242_p1, zext_ln59_1_fu_270_p1, zext_ln59_5_fu_356_p1, zext_ln60_1_fu_378_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_r_address0_local <= zext_ln60_1_fu_378_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_r_address0_local <= zext_ln59_5_fu_356_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_r_address0_local <= zext_ln59_1_fu_270_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_r_address0_local <= zext_ln59_3_fu_242_p1(14 - 1 downto 0);
        else 
            in_r_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    in_r_address1 <= in_r_address1_local;

    in_r_address1_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, zext_ln59_2_fu_230_p1, zext_ln59_fu_258_p1, zext_ln59_4_fu_344_p1, zext_ln60_fu_367_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_r_address1_local <= zext_ln60_fu_367_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_r_address1_local <= zext_ln59_4_fu_344_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_r_address1_local <= zext_ln59_fu_258_p1(14 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_r_address1_local <= zext_ln59_2_fu_230_p1(14 - 1 downto 0);
        else 
            in_r_address1_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    in_r_ce0 <= in_r_ce0_local;

    in_r_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_r_ce0_local <= ap_const_logic_1;
        else 
            in_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_r_ce1 <= in_r_ce1_local;

    in_r_ce1_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in_r_ce1_local <= ap_const_logic_1;
        else 
            in_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    indvars_iv_next32_fu_199_p2 <= std_logic_vector(unsigned(c_fu_66) + unsigned(ap_const_lv7_1));
    or_ln59_1_fu_466_p2 <= (xor_ln59_1_fu_460_p2 or icmp_ln59_fu_430_p2);
    or_ln59_2_fu_486_p2 <= (and_ln59_fu_454_p2 or and_ln59_1_fu_472_p2);
    or_ln59_fu_442_p2 <= (tmp_10_fu_412_p3 or icmp_ln59_1_fu_436_p2);
    or_ln60_1_fu_630_p2 <= (xor_ln60_1_fu_624_p2 or icmp_ln60_fu_594_p2);
    or_ln60_2_fu_650_p2 <= (and_ln60_fu_618_p2 or and_ln60_1_fu_636_p2);
    or_ln60_fu_606_p2 <= (tmp_12_fu_576_p3 or icmp_ln60_1_fu_600_p2);
    or_ln61_fu_664_p2 <= (gy_1_fu_656_p3 or gx_1_fu_492_p3);
    profile_out_address0 <= zext_ln56_reg_763(7 - 1 downto 0);
    profile_out_ce0 <= profile_out_ce0_local;

    profile_out_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            profile_out_ce0_local <= ap_const_logic_1;
        else 
            profile_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    profile_out_d0 <= col_acc_reg_168;
    profile_out_we0 <= profile_out_we0_local;

    profile_out_we0_local_assign_proc : process(ap_CS_fsm_state3, icmp_ln58_fu_211_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln58_fu_211_p2 = ap_const_lv1_1))) then 
            profile_out_we0_local <= ap_const_logic_1;
        else 
            profile_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln59_fu_478_p3 <= 
        ap_const_lv16_7FFF when (and_ln59_fu_454_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln60_fu_642_p3 <= 
        ap_const_lv16_7FFF when (and_ln60_fu_618_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln61_1_fu_731_p3 <= 
        ap_const_lv16_7FFF when (and_ln61_fu_719_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln61_fu_680_p3 <= 
        ap_const_lv17_100 when (icmp_ln61_reg_864(0) = '1') else 
        ap_const_lv17_0;
        sext_ln59_1_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_load_1_reg_817),17));

        sext_ln59_2_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln59_fu_281_p2),18));

        sext_ln59_3_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_287_p3),18));

        sext_ln59_4_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln59_1_fu_303_p2),19));

        sext_ln59_5_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln59_1_fu_309_p3),19));

        sext_ln59_6_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_load_4_reg_854),19));

        sext_ln59_7_fu_391_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_load_5_reg_859),19));

        sext_ln59_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_load_reg_811),17));

        sext_ln60_1_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1_fu_500_p3),18));

        sext_ln60_2_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_load_reg_811),18));

        sext_ln60_3_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln60_1_fu_524_p2),19));

        sext_ln60_4_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln60_1_fu_540_p3),19));

        sext_ln60_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_load_1_reg_817),18));

        sext_ln61_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(col_acc_reg_168),17));

    shl_ln1_fu_500_p3 <= (in_r_q1 & ap_const_lv1_0);
    shl_ln59_1_fu_309_p3 <= (in_r_q0 & ap_const_lv1_0);
    shl_ln60_1_fu_540_p3 <= (in_r_q0 & ap_const_lv1_0);
    shl_ln_fu_287_p3 <= (in_r_q1 & ap_const_lv1_0);
    sub_ln59_1_fu_325_p2 <= std_logic_vector(signed(sext_ln59_4_fu_317_p1) - signed(sext_ln59_5_fu_321_p1));
    sub_ln59_2_fu_394_p2 <= std_logic_vector(unsigned(add_ln59_3_fu_386_p2) - unsigned(sext_ln59_7_fu_391_p1));
    sub_ln59_fu_281_p2 <= std_logic_vector(signed(sext_ln59_fu_275_p1) - signed(sext_ln59_1_fu_278_p1));
    sub_ln60_1_fu_552_p2 <= std_logic_vector(unsigned(sub_ln60_fu_534_p2) - unsigned(sext_ln60_4_fu_548_p1));
    sub_ln60_2_fu_558_p2 <= std_logic_vector(unsigned(sub_ln60_1_fu_552_p2) - unsigned(sext_ln59_6_fu_383_p1));
    sub_ln60_fu_534_p2 <= std_logic_vector(signed(sext_ln60_3_fu_530_p1) - signed(sext_ln59_7_fu_391_p1));
    tmp_10_fu_412_p3 <= sub_ln59_2_fu_394_p2(15 downto 15);
    tmp_11_fu_564_p3 <= sub_ln60_2_fu_558_p2(18 downto 18);
    tmp_12_fu_576_p3 <= sub_ln60_2_fu_558_p2(15 downto 15);
    tmp_13_fu_693_p3 <= add_ln61_fu_687_p2(16 downto 16);
    tmp_14_fu_705_p3 <= add_ln61_fu_687_p2(15 downto 15);
    tmp_1_fu_223_p3 <= (add_ln59_fu_217_p2 & indvars_iv_next32_reg_768);
    tmp_2_fu_235_p3 <= (add_ln59_fu_217_p2 & empty_reg_776);
    tmp_3_fu_420_p4 <= sub_ln59_2_fu_394_p2(18 downto 16);
    tmp_4_fu_584_p4 <= sub_ln60_2_fu_558_p2(18 downto 16);
    tmp_5_fu_361_p3 <= (add_ln59_reg_786 & c_1_reg_754);
    tmp_6_fu_337_p3 <= (add_ln59_2_fu_331_p2 & indvars_iv_next32_reg_768);
    tmp_7_fu_349_p3 <= (add_ln59_2_fu_331_p2 & empty_reg_776);
    tmp_8_fu_372_p3 <= (add_ln59_2_reg_828 & c_1_reg_754);
    tmp_9_fu_251_p3 <= (r_reg_156 & indvars_iv_next32_reg_768);
    tmp_fu_400_p3 <= sub_ln59_2_fu_394_p2(18 downto 18);
    tmp_s_fu_263_p3 <= (r_reg_156 & empty_reg_776);
    xor_ln59_1_fu_460_p2 <= (tmp_10_fu_412_p3 xor ap_const_lv1_1);
    xor_ln59_fu_448_p2 <= (tmp_fu_400_p3 xor ap_const_lv1_1);
    xor_ln60_1_fu_624_p2 <= (tmp_12_fu_576_p3 xor ap_const_lv1_1);
    xor_ln60_fu_612_p2 <= (tmp_11_fu_564_p3 xor ap_const_lv1_1);
    xor_ln61_1_fu_725_p2 <= (tmp_14_fu_705_p3 xor tmp_13_fu_693_p3);
    xor_ln61_fu_713_p2 <= (tmp_13_fu_693_p3 xor ap_const_lv1_1);
    zext_ln56_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_66),64));
    zext_ln59_1_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_263_p3),64));
    zext_ln59_2_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_223_p3),64));
    zext_ln59_3_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_235_p3),64));
    zext_ln59_4_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_337_p3),64));
    zext_ln59_5_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_349_p3),64));
    zext_ln59_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_251_p3),64));
    zext_ln60_1_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_372_p3),64));
    zext_ln60_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_361_p3),64));
end behav;
