// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_k0_preprocess (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_in_dout,
        s_in_empty_n,
        s_in_read,
        s_in_num_data_valid,
        s_in_fifo_cap,
        s0_din,
        s0_full_n,
        s0_write,
        s0_num_data_valid,
        s0_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [19:0] s_in_dout;
input   s_in_empty_n;
output   s_in_read;
input  [2:0] s_in_num_data_valid;
input  [2:0] s_in_fifo_cap;
output  [19:0] s0_din;
input   s0_full_n;
output   s0_write;
input  [2:0] s0_num_data_valid;
input  [2:0] s0_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg s_in_read;
reg s0_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln130_fu_216_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_in_blk_n;
reg    s0_blk_n;
reg   [15:0] k1_fu_64;
wire   [15:0] k_fu_210_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_k1_load;
wire   [50:0] tmp_fu_97_p3;
wire   [53:0] p_shl_fu_89_p3;
wire  signed [53:0] sext_ln133_fu_105_p1;
wire   [53:0] sub_ln133_fu_109_p2;
wire   [53:0] add_ln133_fu_115_p2;
wire   [0:0] tmp_35_fu_139_p3;
wire   [19:0] trunc_ln_fu_129_p4;
wire   [19:0] zext_ln133_fu_147_p1;
wire   [19:0] add_ln133_1_fu_151_p2;
wire   [0:0] tmp_34_fu_121_p3;
wire   [0:0] tmp_36_fu_157_p3;
wire   [0:0] xor_ln133_fu_165_p2;
wire   [0:0] or_ln133_1_fu_171_p2;
wire   [0:0] xor_ln133_1_fu_177_p2;
wire   [0:0] xor_ln133_2_fu_183_p2;
wire   [0:0] or_ln133_fu_189_p2;
wire   [0:0] and_ln133_fu_195_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 k1_fu_64 = 16'd0;
end

top_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        k1_fu_64 <= k_fu_210_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln130_fu_216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_k1_load = 16'd0;
    end else begin
        ap_sig_allocacmp_k1_load = k1_fu_64;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        s0_blk_n = s0_full_n;
    end else begin
        s0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        s0_write = 1'b1;
    end else begin
        s0_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start_int == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        s_in_blk_n = s_in_empty_n;
    end else begin
        s_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        s_in_read = 1'b1;
    end else begin
        s_in_read = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln133_1_fu_151_p2 = (trunc_ln_fu_129_p4 + zext_ln133_fu_147_p1);

assign add_ln133_fu_115_p2 = (sub_ln133_fu_109_p2 + 54'd35184372088832);

assign and_ln133_fu_195_p2 = (xor_ln133_fu_165_p2 & or_ln133_fu_189_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (s0_full_n == 1'b0) | (s_in_empty_n == 1'b0) | (ap_start_int == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign icmp_ln130_fu_216_p2 = ((ap_sig_allocacmp_k1_load == 16'd65535) ? 1'b1 : 1'b0);

assign k_fu_210_p2 = (ap_sig_allocacmp_k1_load + 16'd1);

assign or_ln133_1_fu_171_p2 = (xor_ln133_fu_165_p2 | tmp_36_fu_157_p3);

assign or_ln133_fu_189_p2 = (xor_ln133_2_fu_183_p2 | tmp_36_fu_157_p3);

assign p_shl_fu_89_p3 = {{s_in_dout}, {34'd0}};

assign s0_din = ((and_ln133_fu_195_p2[0:0] == 1'b1) ? 20'd524287 : add_ln133_1_fu_151_p2);

assign sext_ln133_fu_105_p1 = $signed(tmp_fu_97_p3);

assign start_out = real_start;

assign sub_ln133_fu_109_p2 = ($signed(p_shl_fu_89_p3) - $signed(sext_ln133_fu_105_p1));

assign tmp_34_fu_121_p3 = add_ln133_fu_115_p2[32'd53];

assign tmp_35_fu_139_p3 = add_ln133_fu_115_p2[32'd33];

assign tmp_36_fu_157_p3 = add_ln133_1_fu_151_p2[32'd19];

assign tmp_fu_97_p3 = {{s_in_dout}, {31'd0}};

assign trunc_ln_fu_129_p4 = {{add_ln133_fu_115_p2[53:34]}};

assign xor_ln133_1_fu_177_p2 = (tmp_34_fu_121_p3 ^ or_ln133_1_fu_171_p2);

assign xor_ln133_2_fu_183_p2 = (xor_ln133_1_fu_177_p2 ^ 1'd1);

assign xor_ln133_fu_165_p2 = (tmp_34_fu_121_p3 ^ 1'd1);

assign zext_ln133_fu_147_p1 = tmp_35_fu_139_p3;

endmodule //top_kernel_k0_preprocess
