// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_k2_stats (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s0_b_dout,
        s0_b_empty_n,
        s0_b_read,
        s0_b_num_data_valid,
        s0_b_fifo_cap,
        s_stats_din,
        s_stats_full_n,
        s_stats_write,
        s_stats_num_data_valid,
        s_stats_fifo_cap
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] s0_b_dout;
input   s0_b_empty_n;
output   s0_b_read;
input  [2:0] s0_b_num_data_valid;
input  [2:0] s0_b_fifo_cap;
output  [27:0] s_stats_din;
input   s_stats_full_n;
output   s_stats_write;
input  [31:0] s_stats_num_data_valid;
input  [31:0] s_stats_fifo_cap;

reg ap_idle;
reg s0_b_read;
reg s_stats_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln214_reg_3243;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln212_fu_1496_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_stats_blk_n;
wire    ap_block_pp0_stage0;
reg    s0_b_blk_n;
wire   [19:0] ref_tmp9_2_i_fu_420_p9;
reg   [19:0] ref_tmp9_2_i_reg_3154;
reg    ap_block_pp0_stage0_11001;
wire   [19:0] ref_tmp9_2_1_i_fu_490_p9;
reg   [19:0] ref_tmp9_2_1_i_reg_3159;
wire   [19:0] ref_tmp9_2_2_i_fu_560_p9;
reg   [19:0] ref_tmp9_2_2_i_reg_3164;
wire   [19:0] ref_tmp9_2_3_i_fu_630_p9;
reg   [19:0] ref_tmp9_2_3_i_reg_3169;
wire   [19:0] ref_tmp9_2_4_i_fu_700_p9;
reg   [19:0] ref_tmp9_2_4_i_reg_3174;
wire   [19:0] ref_tmp9_2_5_i_fu_770_p9;
reg   [19:0] ref_tmp9_2_5_i_reg_3179;
wire   [19:0] ref_tmp9_2_6_i_fu_840_p9;
reg   [19:0] ref_tmp9_2_6_i_reg_3184;
wire   [19:0] ref_tmp9_2_7_i_fu_910_p9;
reg   [19:0] ref_tmp9_2_7_i_reg_3189;
wire   [19:0] ref_tmp9_2_8_i_fu_980_p9;
reg   [19:0] ref_tmp9_2_8_i_reg_3194;
wire   [19:0] ref_tmp9_2_9_i_fu_1050_p9;
reg   [19:0] ref_tmp9_2_9_i_reg_3199;
wire   [19:0] ref_tmp9_2_10_i_fu_1120_p9;
reg   [19:0] ref_tmp9_2_10_i_reg_3204;
wire   [19:0] ref_tmp9_2_11_i_fu_1190_p9;
reg   [19:0] ref_tmp9_2_11_i_reg_3209;
wire   [19:0] ref_tmp9_2_12_i_fu_1260_p9;
reg   [19:0] ref_tmp9_2_12_i_reg_3214;
wire   [19:0] ref_tmp9_2_13_i_fu_1330_p9;
reg   [19:0] ref_tmp9_2_13_i_reg_3219;
wire   [19:0] ref_tmp9_2_14_i_fu_1400_p9;
reg   [19:0] ref_tmp9_2_14_i_reg_3224;
wire   [19:0] ref_tmp9_2_15_i_fu_1470_p9;
reg   [19:0] ref_tmp9_2_15_i_reg_3229;
reg   [0:0] icmp_ln212_reg_3234;
reg   [0:0] icmp_ln212_reg_3234_pp0_iter1_reg;
wire   [35:0] sum_abs_fu_2873_p3;
reg   [35:0] sum_abs_reg_3238;
wire   [0:0] icmp_ln214_fu_2895_p2;
reg   [0:0] tmp_283_reg_3248;
reg   [27:0] tmp_48_reg_3253;
reg   [0:0] ap_phi_mux_icmp_ln2145_phi_fu_221_p4;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg   [11:0] indvar_flatten2_fu_192;
wire   [11:0] add_ln212_fu_1490_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten2_load;
reg   [4:0] i3_fu_196;
wire   [4:0] i_fu_2887_p3;
reg   [35:0] sum_abs4_fu_200;
reg    ap_block_pp0_stage0_01001;
wire   [19:0] v_fu_246_p1;
wire   [19:0] sub_ln220_fu_378_p2;
wire   [0:0] tmp_220_fu_384_p3;
wire   [0:0] tmp_219_fu_370_p3;
wire   [0:0] and_ln220_fu_400_p2;
wire   [0:0] xor_ln220_fu_406_p2;
wire   [19:0] ref_tmp9_2_i_fu_420_p2;
wire   [19:0] ref_tmp9_2_i_fu_420_p7;
wire   [1:0] ref_tmp9_2_i_fu_420_p8;
wire   [19:0] v_16_fu_250_p3;
wire   [19:0] sub_ln220_1_fu_448_p2;
wire   [0:0] tmp_224_fu_454_p3;
wire   [0:0] tmp_223_fu_440_p3;
wire   [0:0] and_ln220_2_fu_470_p2;
wire   [0:0] xor_ln220_3_fu_476_p2;
wire   [19:0] ref_tmp9_2_1_i_fu_490_p2;
wire   [19:0] ref_tmp9_2_1_i_fu_490_p4;
wire   [19:0] ref_tmp9_2_1_i_fu_490_p7;
wire   [1:0] ref_tmp9_2_1_i_fu_490_p8;
wire   [19:0] v_17_fu_258_p3;
wire   [19:0] sub_ln220_2_fu_518_p2;
wire   [0:0] tmp_228_fu_524_p3;
wire   [0:0] tmp_227_fu_510_p3;
wire   [0:0] and_ln220_4_fu_540_p2;
wire   [0:0] xor_ln220_6_fu_546_p2;
wire   [19:0] ref_tmp9_2_2_i_fu_560_p2;
wire   [19:0] ref_tmp9_2_2_i_fu_560_p4;
wire   [19:0] ref_tmp9_2_2_i_fu_560_p7;
wire   [1:0] ref_tmp9_2_2_i_fu_560_p8;
wire   [19:0] v_18_fu_266_p3;
wire   [19:0] sub_ln220_3_fu_588_p2;
wire   [0:0] tmp_232_fu_594_p3;
wire   [0:0] tmp_231_fu_580_p3;
wire   [0:0] and_ln220_6_fu_610_p2;
wire   [0:0] xor_ln220_9_fu_616_p2;
wire   [19:0] ref_tmp9_2_3_i_fu_630_p2;
wire   [19:0] ref_tmp9_2_3_i_fu_630_p4;
wire   [19:0] ref_tmp9_2_3_i_fu_630_p7;
wire   [1:0] ref_tmp9_2_3_i_fu_630_p8;
wire   [19:0] v_19_fu_274_p3;
wire   [19:0] sub_ln220_4_fu_658_p2;
wire   [0:0] tmp_236_fu_664_p3;
wire   [0:0] tmp_235_fu_650_p3;
wire   [0:0] and_ln220_8_fu_680_p2;
wire   [0:0] xor_ln220_12_fu_686_p2;
wire   [19:0] ref_tmp9_2_4_i_fu_700_p2;
wire   [19:0] ref_tmp9_2_4_i_fu_700_p4;
wire   [19:0] ref_tmp9_2_4_i_fu_700_p7;
wire   [1:0] ref_tmp9_2_4_i_fu_700_p8;
wire   [19:0] v_20_fu_282_p3;
wire   [19:0] sub_ln220_5_fu_728_p2;
wire   [0:0] tmp_240_fu_734_p3;
wire   [0:0] tmp_239_fu_720_p3;
wire   [0:0] and_ln220_10_fu_750_p2;
wire   [0:0] xor_ln220_15_fu_756_p2;
wire   [19:0] ref_tmp9_2_5_i_fu_770_p2;
wire   [19:0] ref_tmp9_2_5_i_fu_770_p4;
wire   [19:0] ref_tmp9_2_5_i_fu_770_p7;
wire   [1:0] ref_tmp9_2_5_i_fu_770_p8;
wire   [19:0] v_21_fu_290_p3;
wire   [19:0] sub_ln220_6_fu_798_p2;
wire   [0:0] tmp_244_fu_804_p3;
wire   [0:0] tmp_243_fu_790_p3;
wire   [0:0] and_ln220_12_fu_820_p2;
wire   [0:0] xor_ln220_18_fu_826_p2;
wire   [19:0] ref_tmp9_2_6_i_fu_840_p2;
wire   [19:0] ref_tmp9_2_6_i_fu_840_p4;
wire   [19:0] ref_tmp9_2_6_i_fu_840_p7;
wire   [1:0] ref_tmp9_2_6_i_fu_840_p8;
wire   [19:0] v_22_fu_298_p3;
wire   [19:0] sub_ln220_7_fu_868_p2;
wire   [0:0] tmp_248_fu_874_p3;
wire   [0:0] tmp_247_fu_860_p3;
wire   [0:0] and_ln220_14_fu_890_p2;
wire   [0:0] xor_ln220_21_fu_896_p2;
wire   [19:0] ref_tmp9_2_7_i_fu_910_p2;
wire   [19:0] ref_tmp9_2_7_i_fu_910_p4;
wire   [19:0] ref_tmp9_2_7_i_fu_910_p7;
wire   [1:0] ref_tmp9_2_7_i_fu_910_p8;
wire   [19:0] v_23_fu_306_p3;
wire   [19:0] sub_ln220_8_fu_938_p2;
wire   [0:0] tmp_252_fu_944_p3;
wire   [0:0] tmp_251_fu_930_p3;
wire   [0:0] and_ln220_16_fu_960_p2;
wire   [0:0] xor_ln220_24_fu_966_p2;
wire   [19:0] ref_tmp9_2_8_i_fu_980_p2;
wire   [19:0] ref_tmp9_2_8_i_fu_980_p4;
wire   [19:0] ref_tmp9_2_8_i_fu_980_p7;
wire   [1:0] ref_tmp9_2_8_i_fu_980_p8;
wire   [19:0] v_24_fu_314_p3;
wire   [19:0] sub_ln220_9_fu_1008_p2;
wire   [0:0] tmp_256_fu_1014_p3;
wire   [0:0] tmp_255_fu_1000_p3;
wire   [0:0] and_ln220_18_fu_1030_p2;
wire   [0:0] xor_ln220_27_fu_1036_p2;
wire   [19:0] ref_tmp9_2_9_i_fu_1050_p2;
wire   [19:0] ref_tmp9_2_9_i_fu_1050_p4;
wire   [19:0] ref_tmp9_2_9_i_fu_1050_p7;
wire   [1:0] ref_tmp9_2_9_i_fu_1050_p8;
wire   [19:0] v_25_fu_322_p3;
wire   [19:0] sub_ln220_10_fu_1078_p2;
wire   [0:0] tmp_260_fu_1084_p3;
wire   [0:0] tmp_259_fu_1070_p3;
wire   [0:0] and_ln220_20_fu_1100_p2;
wire   [0:0] xor_ln220_30_fu_1106_p2;
wire   [19:0] ref_tmp9_2_10_i_fu_1120_p2;
wire   [19:0] ref_tmp9_2_10_i_fu_1120_p4;
wire   [19:0] ref_tmp9_2_10_i_fu_1120_p7;
wire   [1:0] ref_tmp9_2_10_i_fu_1120_p8;
wire   [19:0] v_26_fu_330_p3;
wire   [19:0] sub_ln220_11_fu_1148_p2;
wire   [0:0] tmp_264_fu_1154_p3;
wire   [0:0] tmp_263_fu_1140_p3;
wire   [0:0] and_ln220_22_fu_1170_p2;
wire   [0:0] xor_ln220_33_fu_1176_p2;
wire   [19:0] ref_tmp9_2_11_i_fu_1190_p2;
wire   [19:0] ref_tmp9_2_11_i_fu_1190_p4;
wire   [19:0] ref_tmp9_2_11_i_fu_1190_p7;
wire   [1:0] ref_tmp9_2_11_i_fu_1190_p8;
wire   [19:0] v_27_fu_338_p3;
wire   [19:0] sub_ln220_12_fu_1218_p2;
wire   [0:0] tmp_268_fu_1224_p3;
wire   [0:0] tmp_267_fu_1210_p3;
wire   [0:0] and_ln220_24_fu_1240_p2;
wire   [0:0] xor_ln220_36_fu_1246_p2;
wire   [19:0] ref_tmp9_2_12_i_fu_1260_p2;
wire   [19:0] ref_tmp9_2_12_i_fu_1260_p4;
wire   [19:0] ref_tmp9_2_12_i_fu_1260_p7;
wire   [1:0] ref_tmp9_2_12_i_fu_1260_p8;
wire   [19:0] v_28_fu_346_p3;
wire   [19:0] sub_ln220_13_fu_1288_p2;
wire   [0:0] tmp_272_fu_1294_p3;
wire   [0:0] tmp_271_fu_1280_p3;
wire   [0:0] and_ln220_26_fu_1310_p2;
wire   [0:0] xor_ln220_39_fu_1316_p2;
wire   [19:0] ref_tmp9_2_13_i_fu_1330_p2;
wire   [19:0] ref_tmp9_2_13_i_fu_1330_p4;
wire   [19:0] ref_tmp9_2_13_i_fu_1330_p7;
wire   [1:0] ref_tmp9_2_13_i_fu_1330_p8;
wire   [19:0] v_29_fu_354_p3;
wire   [19:0] sub_ln220_14_fu_1358_p2;
wire   [0:0] tmp_276_fu_1364_p3;
wire   [0:0] tmp_275_fu_1350_p3;
wire   [0:0] and_ln220_28_fu_1380_p2;
wire   [0:0] xor_ln220_42_fu_1386_p2;
wire   [19:0] ref_tmp9_2_14_i_fu_1400_p2;
wire   [19:0] ref_tmp9_2_14_i_fu_1400_p4;
wire   [19:0] ref_tmp9_2_14_i_fu_1400_p7;
wire   [1:0] ref_tmp9_2_14_i_fu_1400_p8;
wire   [19:0] v_30_fu_362_p3;
wire   [19:0] sub_ln220_15_fu_1428_p2;
wire   [0:0] tmp_280_fu_1434_p3;
wire   [0:0] tmp_279_fu_1420_p3;
wire   [0:0] and_ln220_30_fu_1450_p2;
wire   [0:0] xor_ln220_45_fu_1456_p2;
wire   [19:0] ref_tmp9_2_15_i_fu_1470_p2;
wire   [19:0] ref_tmp9_2_15_i_fu_1470_p4;
wire   [19:0] ref_tmp9_2_15_i_fu_1470_p7;
wire   [1:0] ref_tmp9_2_15_i_fu_1470_p8;
wire  signed [29:0] shl_ln_fu_1521_p3;
wire  signed [35:0] select_ln212_fu_1513_p3;
wire  signed [35:0] sext_ln220_fu_1528_p1;
wire  signed [36:0] sext_ln220_1_fu_1532_p1;
wire  signed [36:0] sext_ln220_2_fu_1536_p1;
wire   [36:0] add_ln220_1_fu_1546_p2;
wire   [35:0] add_ln220_fu_1540_p2;
wire   [0:0] tmp_221_fu_1552_p3;
wire   [0:0] tmp_222_fu_1564_p3;
wire   [0:0] xor_ln220_1_fu_1572_p2;
wire   [0:0] and_ln220_1_fu_1578_p2;
wire   [0:0] xor_ln220_2_fu_1584_p2;
wire   [35:0] select_ln220_1_fu_1590_p3;
wire   [35:0] sum_abs_1_fu_1560_p1;
wire  signed [29:0] shl_ln220_1_fu_1606_p3;
wire  signed [35:0] sum_abs_2_fu_1598_p3;
wire  signed [35:0] sext_ln220_3_fu_1613_p1;
wire  signed [36:0] sext_ln220_4_fu_1617_p1;
wire  signed [36:0] sext_ln220_5_fu_1621_p1;
wire   [36:0] add_ln220_3_fu_1631_p2;
wire   [35:0] add_ln220_2_fu_1625_p2;
wire   [0:0] tmp_225_fu_1637_p3;
wire   [0:0] tmp_226_fu_1649_p3;
wire   [0:0] xor_ln220_4_fu_1657_p2;
wire   [0:0] and_ln220_3_fu_1663_p2;
wire   [0:0] xor_ln220_5_fu_1669_p2;
wire   [35:0] select_ln220_4_fu_1675_p3;
wire   [35:0] sum_abs_3_fu_1645_p1;
wire  signed [29:0] shl_ln220_2_fu_1691_p3;
wire  signed [35:0] sum_abs_4_fu_1683_p3;
wire  signed [35:0] sext_ln220_6_fu_1698_p1;
wire  signed [36:0] sext_ln220_7_fu_1702_p1;
wire  signed [36:0] sext_ln220_8_fu_1706_p1;
wire   [36:0] add_ln220_5_fu_1716_p2;
wire   [35:0] add_ln220_4_fu_1710_p2;
wire   [0:0] tmp_229_fu_1722_p3;
wire   [0:0] tmp_230_fu_1734_p3;
wire   [0:0] xor_ln220_7_fu_1742_p2;
wire   [0:0] and_ln220_5_fu_1748_p2;
wire   [0:0] xor_ln220_8_fu_1754_p2;
wire   [35:0] select_ln220_7_fu_1760_p3;
wire   [35:0] sum_abs_5_fu_1730_p1;
wire  signed [29:0] shl_ln220_3_fu_1776_p3;
wire  signed [35:0] sum_abs_6_fu_1768_p3;
wire  signed [35:0] sext_ln220_9_fu_1783_p1;
wire  signed [36:0] sext_ln220_10_fu_1787_p1;
wire  signed [36:0] sext_ln220_11_fu_1791_p1;
wire   [36:0] add_ln220_7_fu_1801_p2;
wire   [35:0] add_ln220_6_fu_1795_p2;
wire   [0:0] tmp_233_fu_1807_p3;
wire   [0:0] tmp_234_fu_1819_p3;
wire   [0:0] xor_ln220_10_fu_1827_p2;
wire   [0:0] and_ln220_7_fu_1833_p2;
wire   [0:0] xor_ln220_11_fu_1839_p2;
wire   [35:0] select_ln220_10_fu_1845_p3;
wire   [35:0] sum_abs_7_fu_1815_p1;
wire  signed [29:0] shl_ln220_4_fu_1861_p3;
wire  signed [35:0] sum_abs_8_fu_1853_p3;
wire  signed [35:0] sext_ln220_12_fu_1868_p1;
wire  signed [36:0] sext_ln220_13_fu_1872_p1;
wire  signed [36:0] sext_ln220_14_fu_1876_p1;
wire   [36:0] add_ln220_9_fu_1886_p2;
wire   [35:0] add_ln220_8_fu_1880_p2;
wire   [0:0] tmp_237_fu_1892_p3;
wire   [0:0] tmp_238_fu_1904_p3;
wire   [0:0] xor_ln220_13_fu_1912_p2;
wire   [0:0] and_ln220_9_fu_1918_p2;
wire   [0:0] xor_ln220_14_fu_1924_p2;
wire   [35:0] select_ln220_13_fu_1930_p3;
wire   [35:0] sum_abs_9_fu_1900_p1;
wire  signed [29:0] shl_ln220_5_fu_1946_p3;
wire  signed [35:0] sum_abs_10_fu_1938_p3;
wire  signed [35:0] sext_ln220_15_fu_1953_p1;
wire  signed [36:0] sext_ln220_16_fu_1957_p1;
wire  signed [36:0] sext_ln220_17_fu_1961_p1;
wire   [36:0] add_ln220_11_fu_1971_p2;
wire   [35:0] add_ln220_10_fu_1965_p2;
wire   [0:0] tmp_241_fu_1977_p3;
wire   [0:0] tmp_242_fu_1989_p3;
wire   [0:0] xor_ln220_16_fu_1997_p2;
wire   [0:0] and_ln220_11_fu_2003_p2;
wire   [0:0] xor_ln220_17_fu_2009_p2;
wire   [35:0] select_ln220_16_fu_2015_p3;
wire   [35:0] sum_abs_11_fu_1985_p1;
wire  signed [29:0] shl_ln220_6_fu_2031_p3;
wire  signed [35:0] sum_abs_12_fu_2023_p3;
wire  signed [35:0] sext_ln220_18_fu_2038_p1;
wire  signed [36:0] sext_ln220_19_fu_2042_p1;
wire  signed [36:0] sext_ln220_20_fu_2046_p1;
wire   [36:0] add_ln220_13_fu_2056_p2;
wire   [35:0] add_ln220_12_fu_2050_p2;
wire   [0:0] tmp_245_fu_2062_p3;
wire   [0:0] tmp_246_fu_2074_p3;
wire   [0:0] xor_ln220_19_fu_2082_p2;
wire   [0:0] and_ln220_13_fu_2088_p2;
wire   [0:0] xor_ln220_20_fu_2094_p2;
wire   [35:0] select_ln220_19_fu_2100_p3;
wire   [35:0] sum_abs_13_fu_2070_p1;
wire  signed [29:0] shl_ln220_7_fu_2116_p3;
wire  signed [35:0] sum_abs_14_fu_2108_p3;
wire  signed [35:0] sext_ln220_21_fu_2123_p1;
wire  signed [36:0] sext_ln220_22_fu_2127_p1;
wire  signed [36:0] sext_ln220_23_fu_2131_p1;
wire   [36:0] add_ln220_15_fu_2141_p2;
wire   [35:0] add_ln220_14_fu_2135_p2;
wire   [0:0] tmp_249_fu_2147_p3;
wire   [0:0] tmp_250_fu_2159_p3;
wire   [0:0] xor_ln220_22_fu_2167_p2;
wire   [0:0] and_ln220_15_fu_2173_p2;
wire   [0:0] xor_ln220_23_fu_2179_p2;
wire   [35:0] select_ln220_22_fu_2185_p3;
wire   [35:0] sum_abs_15_fu_2155_p1;
wire  signed [29:0] shl_ln220_8_fu_2201_p3;
wire  signed [35:0] sum_abs_16_fu_2193_p3;
wire  signed [35:0] sext_ln220_24_fu_2208_p1;
wire  signed [36:0] sext_ln220_25_fu_2212_p1;
wire  signed [36:0] sext_ln220_26_fu_2216_p1;
wire   [36:0] add_ln220_17_fu_2226_p2;
wire   [35:0] add_ln220_16_fu_2220_p2;
wire   [0:0] tmp_253_fu_2232_p3;
wire   [0:0] tmp_254_fu_2244_p3;
wire   [0:0] xor_ln220_25_fu_2252_p2;
wire   [0:0] and_ln220_17_fu_2258_p2;
wire   [0:0] xor_ln220_26_fu_2264_p2;
wire   [35:0] select_ln220_25_fu_2270_p3;
wire   [35:0] sum_abs_17_fu_2240_p1;
wire  signed [29:0] shl_ln220_9_fu_2286_p3;
wire  signed [35:0] sum_abs_18_fu_2278_p3;
wire  signed [35:0] sext_ln220_27_fu_2293_p1;
wire  signed [36:0] sext_ln220_28_fu_2297_p1;
wire  signed [36:0] sext_ln220_29_fu_2301_p1;
wire   [36:0] add_ln220_19_fu_2311_p2;
wire   [35:0] add_ln220_18_fu_2305_p2;
wire   [0:0] tmp_257_fu_2317_p3;
wire   [0:0] tmp_258_fu_2329_p3;
wire   [0:0] xor_ln220_28_fu_2337_p2;
wire   [0:0] and_ln220_19_fu_2343_p2;
wire   [0:0] xor_ln220_29_fu_2349_p2;
wire   [35:0] select_ln220_28_fu_2355_p3;
wire   [35:0] sum_abs_19_fu_2325_p1;
wire  signed [29:0] shl_ln220_s_fu_2371_p3;
wire  signed [35:0] sum_abs_20_fu_2363_p3;
wire  signed [35:0] sext_ln220_30_fu_2378_p1;
wire  signed [36:0] sext_ln220_31_fu_2382_p1;
wire  signed [36:0] sext_ln220_32_fu_2386_p1;
wire   [36:0] add_ln220_21_fu_2396_p2;
wire   [35:0] add_ln220_20_fu_2390_p2;
wire   [0:0] tmp_261_fu_2402_p3;
wire   [0:0] tmp_262_fu_2414_p3;
wire   [0:0] xor_ln220_31_fu_2422_p2;
wire   [0:0] and_ln220_21_fu_2428_p2;
wire   [0:0] xor_ln220_32_fu_2434_p2;
wire   [35:0] select_ln220_31_fu_2440_p3;
wire   [35:0] sum_abs_21_fu_2410_p1;
wire  signed [29:0] shl_ln220_10_fu_2456_p3;
wire  signed [35:0] sum_abs_22_fu_2448_p3;
wire  signed [35:0] sext_ln220_33_fu_2463_p1;
wire  signed [36:0] sext_ln220_34_fu_2467_p1;
wire  signed [36:0] sext_ln220_35_fu_2471_p1;
wire   [36:0] add_ln220_23_fu_2481_p2;
wire   [35:0] add_ln220_22_fu_2475_p2;
wire   [0:0] tmp_265_fu_2487_p3;
wire   [0:0] tmp_266_fu_2499_p3;
wire   [0:0] xor_ln220_34_fu_2507_p2;
wire   [0:0] and_ln220_23_fu_2513_p2;
wire   [0:0] xor_ln220_35_fu_2519_p2;
wire   [35:0] select_ln220_34_fu_2525_p3;
wire   [35:0] sum_abs_23_fu_2495_p1;
wire  signed [29:0] shl_ln220_11_fu_2541_p3;
wire  signed [35:0] sum_abs_24_fu_2533_p3;
wire  signed [35:0] sext_ln220_36_fu_2548_p1;
wire  signed [36:0] sext_ln220_37_fu_2552_p1;
wire  signed [36:0] sext_ln220_38_fu_2556_p1;
wire   [36:0] add_ln220_25_fu_2566_p2;
wire   [35:0] add_ln220_24_fu_2560_p2;
wire   [0:0] tmp_269_fu_2572_p3;
wire   [0:0] tmp_270_fu_2584_p3;
wire   [0:0] xor_ln220_37_fu_2592_p2;
wire   [0:0] and_ln220_25_fu_2598_p2;
wire   [0:0] xor_ln220_38_fu_2604_p2;
wire   [35:0] select_ln220_37_fu_2610_p3;
wire   [35:0] sum_abs_25_fu_2580_p1;
wire  signed [29:0] shl_ln220_12_fu_2626_p3;
wire  signed [35:0] sum_abs_26_fu_2618_p3;
wire  signed [35:0] sext_ln220_39_fu_2633_p1;
wire  signed [36:0] sext_ln220_40_fu_2637_p1;
wire  signed [36:0] sext_ln220_41_fu_2641_p1;
wire   [36:0] add_ln220_27_fu_2651_p2;
wire   [35:0] add_ln220_26_fu_2645_p2;
wire   [0:0] tmp_273_fu_2657_p3;
wire   [0:0] tmp_274_fu_2669_p3;
wire   [0:0] xor_ln220_40_fu_2677_p2;
wire   [0:0] and_ln220_27_fu_2683_p2;
wire   [0:0] xor_ln220_41_fu_2689_p2;
wire   [35:0] select_ln220_40_fu_2695_p3;
wire   [35:0] sum_abs_27_fu_2665_p1;
wire  signed [29:0] shl_ln220_13_fu_2711_p3;
wire  signed [35:0] sum_abs_28_fu_2703_p3;
wire  signed [35:0] sext_ln220_42_fu_2718_p1;
wire  signed [36:0] sext_ln220_43_fu_2722_p1;
wire  signed [36:0] sext_ln220_44_fu_2726_p1;
wire   [36:0] add_ln220_29_fu_2736_p2;
wire   [35:0] add_ln220_28_fu_2730_p2;
wire   [0:0] tmp_277_fu_2742_p3;
wire   [0:0] tmp_278_fu_2754_p3;
wire   [0:0] xor_ln220_43_fu_2762_p2;
wire   [0:0] and_ln220_29_fu_2768_p2;
wire   [0:0] xor_ln220_44_fu_2774_p2;
wire   [35:0] select_ln220_43_fu_2780_p3;
wire   [35:0] sum_abs_29_fu_2750_p1;
wire  signed [29:0] shl_ln220_14_fu_2796_p3;
wire  signed [35:0] sum_abs_30_fu_2788_p3;
wire  signed [35:0] sext_ln220_45_fu_2803_p1;
wire  signed [36:0] sext_ln220_46_fu_2807_p1;
wire  signed [36:0] sext_ln220_47_fu_2811_p1;
wire   [36:0] add_ln220_31_fu_2821_p2;
wire   [35:0] add_ln220_30_fu_2815_p2;
wire   [0:0] tmp_281_fu_2827_p3;
wire   [0:0] tmp_282_fu_2839_p3;
wire   [0:0] xor_ln220_46_fu_2847_p2;
wire   [0:0] and_ln220_31_fu_2853_p2;
wire   [0:0] xor_ln220_47_fu_2859_p2;
wire   [35:0] select_ln220_46_fu_2865_p3;
wire   [35:0] sum_abs_31_fu_2835_p1;
wire   [4:0] add_ln214_fu_2881_p2;
wire   [59:0] shl_ln2_fu_2929_p3;
wire   [59:0] sub_ln223_fu_2936_p2;
wire   [27:0] tmp_fu_2942_p4;
wire   [28:0] zext_ln223_1_fu_2952_p1;
wire   [28:0] sub_ln223_1_fu_2956_p2;
wire   [28:0] zext_ln223_2_fu_2962_p1;
wire   [28:0] select_ln223_fu_2965_p3;
wire   [22:0] avg_abs_fu_2980_p4;
wire   [0:0] tmp_285_fu_2994_p3;
wire  signed [23:0] sext_ln223_fu_2990_p1;
wire   [23:0] zext_ln223_fu_3002_p1;
wire  signed [23:0] avg_abs_1_fu_3006_p2;
wire   [0:0] tmp_284_fu_2972_p3;
wire   [0:0] tmp_286_fu_3016_p3;
wire   [0:0] xor_ln223_fu_3024_p2;
wire   [0:0] or_ln223_1_fu_3030_p2;
wire   [0:0] xor_ln223_1_fu_3036_p2;
wire   [0:0] xor_ln223_2_fu_3042_p2;
wire   [0:0] or_ln223_fu_3048_p2;
wire   [0:0] and_ln223_fu_3054_p2;
wire  signed [27:0] sext_ln223_1_fu_3012_p1;
wire   [27:0] avg_abs_2_fu_3060_p3;
wire  signed [28:0] sext_ln225_fu_3068_p1;
wire   [28:0] add_ln225_fu_3072_p2;
wire   [0:0] tmp_287_fu_3078_p3;
wire   [0:0] tmp_288_fu_3090_p3;
wire   [0:0] xor_ln225_fu_3098_p2;
wire   [0:0] and_ln225_fu_3104_p2;
wire   [0:0] xor_ln225_1_fu_3110_p2;
wire   [27:0] select_ln225_fu_3116_p3;
wire   [27:0] trunc_ln225_fu_3086_p1;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_157;
wire  signed [1:0] ref_tmp9_2_i_fu_420_p1;
wire   [1:0] ref_tmp9_2_i_fu_420_p3;
wire   [1:0] ref_tmp9_2_i_fu_420_p5;
wire  signed [1:0] ref_tmp9_2_1_i_fu_490_p1;
wire   [1:0] ref_tmp9_2_1_i_fu_490_p3;
wire   [1:0] ref_tmp9_2_1_i_fu_490_p5;
wire  signed [1:0] ref_tmp9_2_2_i_fu_560_p1;
wire   [1:0] ref_tmp9_2_2_i_fu_560_p3;
wire   [1:0] ref_tmp9_2_2_i_fu_560_p5;
wire  signed [1:0] ref_tmp9_2_3_i_fu_630_p1;
wire   [1:0] ref_tmp9_2_3_i_fu_630_p3;
wire   [1:0] ref_tmp9_2_3_i_fu_630_p5;
wire  signed [1:0] ref_tmp9_2_4_i_fu_700_p1;
wire   [1:0] ref_tmp9_2_4_i_fu_700_p3;
wire   [1:0] ref_tmp9_2_4_i_fu_700_p5;
wire  signed [1:0] ref_tmp9_2_5_i_fu_770_p1;
wire   [1:0] ref_tmp9_2_5_i_fu_770_p3;
wire   [1:0] ref_tmp9_2_5_i_fu_770_p5;
wire  signed [1:0] ref_tmp9_2_6_i_fu_840_p1;
wire   [1:0] ref_tmp9_2_6_i_fu_840_p3;
wire   [1:0] ref_tmp9_2_6_i_fu_840_p5;
wire  signed [1:0] ref_tmp9_2_7_i_fu_910_p1;
wire   [1:0] ref_tmp9_2_7_i_fu_910_p3;
wire   [1:0] ref_tmp9_2_7_i_fu_910_p5;
wire  signed [1:0] ref_tmp9_2_8_i_fu_980_p1;
wire   [1:0] ref_tmp9_2_8_i_fu_980_p3;
wire   [1:0] ref_tmp9_2_8_i_fu_980_p5;
wire  signed [1:0] ref_tmp9_2_9_i_fu_1050_p1;
wire   [1:0] ref_tmp9_2_9_i_fu_1050_p3;
wire   [1:0] ref_tmp9_2_9_i_fu_1050_p5;
wire  signed [1:0] ref_tmp9_2_10_i_fu_1120_p1;
wire   [1:0] ref_tmp9_2_10_i_fu_1120_p3;
wire   [1:0] ref_tmp9_2_10_i_fu_1120_p5;
wire  signed [1:0] ref_tmp9_2_11_i_fu_1190_p1;
wire   [1:0] ref_tmp9_2_11_i_fu_1190_p3;
wire   [1:0] ref_tmp9_2_11_i_fu_1190_p5;
wire  signed [1:0] ref_tmp9_2_12_i_fu_1260_p1;
wire   [1:0] ref_tmp9_2_12_i_fu_1260_p3;
wire   [1:0] ref_tmp9_2_12_i_fu_1260_p5;
wire  signed [1:0] ref_tmp9_2_13_i_fu_1330_p1;
wire   [1:0] ref_tmp9_2_13_i_fu_1330_p3;
wire   [1:0] ref_tmp9_2_13_i_fu_1330_p5;
wire  signed [1:0] ref_tmp9_2_14_i_fu_1400_p1;
wire   [1:0] ref_tmp9_2_14_i_fu_1400_p3;
wire   [1:0] ref_tmp9_2_14_i_fu_1400_p5;
wire  signed [1:0] ref_tmp9_2_15_i_fu_1470_p1;
wire   [1:0] ref_tmp9_2_15_i_fu_1470_p3;
wire   [1:0] ref_tmp9_2_15_i_fu_1470_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 indvar_flatten2_fu_192 = 12'd0;
#0 i3_fu_196 = 5'd0;
#0 sum_abs4_fu_200 = 36'd0;
end

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U30(
    .din0(ref_tmp9_2_i_fu_420_p2),
    .din1(v_fu_246_p1),
    .din2(sub_ln220_fu_378_p2),
    .def(ref_tmp9_2_i_fu_420_p7),
    .sel(ref_tmp9_2_i_fu_420_p8),
    .dout(ref_tmp9_2_i_fu_420_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U31(
    .din0(ref_tmp9_2_1_i_fu_490_p2),
    .din1(ref_tmp9_2_1_i_fu_490_p4),
    .din2(sub_ln220_1_fu_448_p2),
    .def(ref_tmp9_2_1_i_fu_490_p7),
    .sel(ref_tmp9_2_1_i_fu_490_p8),
    .dout(ref_tmp9_2_1_i_fu_490_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U32(
    .din0(ref_tmp9_2_2_i_fu_560_p2),
    .din1(ref_tmp9_2_2_i_fu_560_p4),
    .din2(sub_ln220_2_fu_518_p2),
    .def(ref_tmp9_2_2_i_fu_560_p7),
    .sel(ref_tmp9_2_2_i_fu_560_p8),
    .dout(ref_tmp9_2_2_i_fu_560_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U33(
    .din0(ref_tmp9_2_3_i_fu_630_p2),
    .din1(ref_tmp9_2_3_i_fu_630_p4),
    .din2(sub_ln220_3_fu_588_p2),
    .def(ref_tmp9_2_3_i_fu_630_p7),
    .sel(ref_tmp9_2_3_i_fu_630_p8),
    .dout(ref_tmp9_2_3_i_fu_630_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U34(
    .din0(ref_tmp9_2_4_i_fu_700_p2),
    .din1(ref_tmp9_2_4_i_fu_700_p4),
    .din2(sub_ln220_4_fu_658_p2),
    .def(ref_tmp9_2_4_i_fu_700_p7),
    .sel(ref_tmp9_2_4_i_fu_700_p8),
    .dout(ref_tmp9_2_4_i_fu_700_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U35(
    .din0(ref_tmp9_2_5_i_fu_770_p2),
    .din1(ref_tmp9_2_5_i_fu_770_p4),
    .din2(sub_ln220_5_fu_728_p2),
    .def(ref_tmp9_2_5_i_fu_770_p7),
    .sel(ref_tmp9_2_5_i_fu_770_p8),
    .dout(ref_tmp9_2_5_i_fu_770_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U36(
    .din0(ref_tmp9_2_6_i_fu_840_p2),
    .din1(ref_tmp9_2_6_i_fu_840_p4),
    .din2(sub_ln220_6_fu_798_p2),
    .def(ref_tmp9_2_6_i_fu_840_p7),
    .sel(ref_tmp9_2_6_i_fu_840_p8),
    .dout(ref_tmp9_2_6_i_fu_840_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U37(
    .din0(ref_tmp9_2_7_i_fu_910_p2),
    .din1(ref_tmp9_2_7_i_fu_910_p4),
    .din2(sub_ln220_7_fu_868_p2),
    .def(ref_tmp9_2_7_i_fu_910_p7),
    .sel(ref_tmp9_2_7_i_fu_910_p8),
    .dout(ref_tmp9_2_7_i_fu_910_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U38(
    .din0(ref_tmp9_2_8_i_fu_980_p2),
    .din1(ref_tmp9_2_8_i_fu_980_p4),
    .din2(sub_ln220_8_fu_938_p2),
    .def(ref_tmp9_2_8_i_fu_980_p7),
    .sel(ref_tmp9_2_8_i_fu_980_p8),
    .dout(ref_tmp9_2_8_i_fu_980_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U39(
    .din0(ref_tmp9_2_9_i_fu_1050_p2),
    .din1(ref_tmp9_2_9_i_fu_1050_p4),
    .din2(sub_ln220_9_fu_1008_p2),
    .def(ref_tmp9_2_9_i_fu_1050_p7),
    .sel(ref_tmp9_2_9_i_fu_1050_p8),
    .dout(ref_tmp9_2_9_i_fu_1050_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U40(
    .din0(ref_tmp9_2_10_i_fu_1120_p2),
    .din1(ref_tmp9_2_10_i_fu_1120_p4),
    .din2(sub_ln220_10_fu_1078_p2),
    .def(ref_tmp9_2_10_i_fu_1120_p7),
    .sel(ref_tmp9_2_10_i_fu_1120_p8),
    .dout(ref_tmp9_2_10_i_fu_1120_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U41(
    .din0(ref_tmp9_2_11_i_fu_1190_p2),
    .din1(ref_tmp9_2_11_i_fu_1190_p4),
    .din2(sub_ln220_11_fu_1148_p2),
    .def(ref_tmp9_2_11_i_fu_1190_p7),
    .sel(ref_tmp9_2_11_i_fu_1190_p8),
    .dout(ref_tmp9_2_11_i_fu_1190_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U42(
    .din0(ref_tmp9_2_12_i_fu_1260_p2),
    .din1(ref_tmp9_2_12_i_fu_1260_p4),
    .din2(sub_ln220_12_fu_1218_p2),
    .def(ref_tmp9_2_12_i_fu_1260_p7),
    .sel(ref_tmp9_2_12_i_fu_1260_p8),
    .dout(ref_tmp9_2_12_i_fu_1260_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U43(
    .din0(ref_tmp9_2_13_i_fu_1330_p2),
    .din1(ref_tmp9_2_13_i_fu_1330_p4),
    .din2(sub_ln220_13_fu_1288_p2),
    .def(ref_tmp9_2_13_i_fu_1330_p7),
    .sel(ref_tmp9_2_13_i_fu_1330_p8),
    .dout(ref_tmp9_2_13_i_fu_1330_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U44(
    .din0(ref_tmp9_2_14_i_fu_1400_p2),
    .din1(ref_tmp9_2_14_i_fu_1400_p4),
    .din2(sub_ln220_14_fu_1358_p2),
    .def(ref_tmp9_2_14_i_fu_1400_p7),
    .sel(ref_tmp9_2_14_i_fu_1400_p8),
    .dout(ref_tmp9_2_14_i_fu_1400_p9)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U45(
    .din0(ref_tmp9_2_15_i_fu_1470_p2),
    .din1(ref_tmp9_2_15_i_fu_1470_p4),
    .din2(sub_ln220_15_fu_1428_p2),
    .def(ref_tmp9_2_15_i_fu_1470_p7),
    .sel(ref_tmp9_2_15_i_fu_1470_p8),
    .dout(ref_tmp9_2_15_i_fu_1470_p9)
);

top_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
            i3_fu_196 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i3_fu_196 <= i_fu_2887_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_157)) begin
        indvar_flatten2_fu_192 <= add_ln212_fu_1490_p2;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    if (((ap_start_int == 1'b1) & (ap_loop_init == 1'b1))) begin
        sum_abs4_fu_200 <= 36'd0;
    end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        sum_abs4_fu_200 <= sum_abs_fu_2873_p3;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        icmp_ln212_reg_3234 <= icmp_ln212_fu_1496_p2;
        icmp_ln212_reg_3234_pp0_iter1_reg <= icmp_ln212_reg_3234;
        ref_tmp9_2_10_i_reg_3204 <= ref_tmp9_2_10_i_fu_1120_p9;
        ref_tmp9_2_11_i_reg_3209 <= ref_tmp9_2_11_i_fu_1190_p9;
        ref_tmp9_2_12_i_reg_3214 <= ref_tmp9_2_12_i_fu_1260_p9;
        ref_tmp9_2_13_i_reg_3219 <= ref_tmp9_2_13_i_fu_1330_p9;
        ref_tmp9_2_14_i_reg_3224 <= ref_tmp9_2_14_i_fu_1400_p9;
        ref_tmp9_2_15_i_reg_3229 <= ref_tmp9_2_15_i_fu_1470_p9;
        ref_tmp9_2_1_i_reg_3159 <= ref_tmp9_2_1_i_fu_490_p9;
        ref_tmp9_2_2_i_reg_3164 <= ref_tmp9_2_2_i_fu_560_p9;
        ref_tmp9_2_3_i_reg_3169 <= ref_tmp9_2_3_i_fu_630_p9;
        ref_tmp9_2_4_i_reg_3174 <= ref_tmp9_2_4_i_fu_700_p9;
        ref_tmp9_2_5_i_reg_3179 <= ref_tmp9_2_5_i_fu_770_p9;
        ref_tmp9_2_6_i_reg_3184 <= ref_tmp9_2_6_i_fu_840_p9;
        ref_tmp9_2_7_i_reg_3189 <= ref_tmp9_2_7_i_fu_910_p9;
        ref_tmp9_2_8_i_reg_3194 <= ref_tmp9_2_8_i_fu_980_p9;
        ref_tmp9_2_9_i_reg_3199 <= ref_tmp9_2_9_i_fu_1050_p9;
        ref_tmp9_2_i_reg_3154 <= ref_tmp9_2_i_fu_420_p9;
        sum_abs_reg_3238 <= sum_abs_fu_2873_p3;
        tmp_283_reg_3248 <= sum_abs_fu_2873_p3[32'd35];
        tmp_48_reg_3253 <= {{sum_abs_fu_2873_p3[35:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln214_reg_3243 <= icmp_ln214_fu_2895_p2;
    end
end

always @ (*) begin
    if (((icmp_ln212_fu_1496_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln212_reg_3234_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_icmp_ln2145_phi_fu_221_p4 = icmp_ln214_reg_3243;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln2145_phi_fu_221_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln2145_phi_fu_221_p4 = icmp_ln214_reg_3243;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s0_b_blk_n = s0_b_empty_n;
    end else begin
        s0_b_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s0_b_read = 1'b1;
    end else begin
        s0_b_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln214_reg_3243 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_stats_blk_n = s_stats_full_n;
    end else begin
        s_stats_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln214_reg_3243 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_stats_write = 1'b1;
    end else begin
        s_stats_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln212_fu_1490_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 12'd1);

assign add_ln214_fu_2881_p2 = (i3_fu_196 + 5'd1);

assign add_ln220_10_fu_1965_p2 = ($signed(sum_abs_10_fu_1938_p3) + $signed(sext_ln220_15_fu_1953_p1));

assign add_ln220_11_fu_1971_p2 = ($signed(sext_ln220_16_fu_1957_p1) + $signed(sext_ln220_17_fu_1961_p1));

assign add_ln220_12_fu_2050_p2 = ($signed(sum_abs_12_fu_2023_p3) + $signed(sext_ln220_18_fu_2038_p1));

assign add_ln220_13_fu_2056_p2 = ($signed(sext_ln220_19_fu_2042_p1) + $signed(sext_ln220_20_fu_2046_p1));

assign add_ln220_14_fu_2135_p2 = ($signed(sum_abs_14_fu_2108_p3) + $signed(sext_ln220_21_fu_2123_p1));

assign add_ln220_15_fu_2141_p2 = ($signed(sext_ln220_22_fu_2127_p1) + $signed(sext_ln220_23_fu_2131_p1));

assign add_ln220_16_fu_2220_p2 = ($signed(sum_abs_16_fu_2193_p3) + $signed(sext_ln220_24_fu_2208_p1));

assign add_ln220_17_fu_2226_p2 = ($signed(sext_ln220_25_fu_2212_p1) + $signed(sext_ln220_26_fu_2216_p1));

assign add_ln220_18_fu_2305_p2 = ($signed(sum_abs_18_fu_2278_p3) + $signed(sext_ln220_27_fu_2293_p1));

assign add_ln220_19_fu_2311_p2 = ($signed(sext_ln220_28_fu_2297_p1) + $signed(sext_ln220_29_fu_2301_p1));

assign add_ln220_1_fu_1546_p2 = ($signed(sext_ln220_1_fu_1532_p1) + $signed(sext_ln220_2_fu_1536_p1));

assign add_ln220_20_fu_2390_p2 = ($signed(sum_abs_20_fu_2363_p3) + $signed(sext_ln220_30_fu_2378_p1));

assign add_ln220_21_fu_2396_p2 = ($signed(sext_ln220_31_fu_2382_p1) + $signed(sext_ln220_32_fu_2386_p1));

assign add_ln220_22_fu_2475_p2 = ($signed(sum_abs_22_fu_2448_p3) + $signed(sext_ln220_33_fu_2463_p1));

assign add_ln220_23_fu_2481_p2 = ($signed(sext_ln220_34_fu_2467_p1) + $signed(sext_ln220_35_fu_2471_p1));

assign add_ln220_24_fu_2560_p2 = ($signed(sum_abs_24_fu_2533_p3) + $signed(sext_ln220_36_fu_2548_p1));

assign add_ln220_25_fu_2566_p2 = ($signed(sext_ln220_37_fu_2552_p1) + $signed(sext_ln220_38_fu_2556_p1));

assign add_ln220_26_fu_2645_p2 = ($signed(sum_abs_26_fu_2618_p3) + $signed(sext_ln220_39_fu_2633_p1));

assign add_ln220_27_fu_2651_p2 = ($signed(sext_ln220_40_fu_2637_p1) + $signed(sext_ln220_41_fu_2641_p1));

assign add_ln220_28_fu_2730_p2 = ($signed(sum_abs_28_fu_2703_p3) + $signed(sext_ln220_42_fu_2718_p1));

assign add_ln220_29_fu_2736_p2 = ($signed(sext_ln220_43_fu_2722_p1) + $signed(sext_ln220_44_fu_2726_p1));

assign add_ln220_2_fu_1625_p2 = ($signed(sum_abs_2_fu_1598_p3) + $signed(sext_ln220_3_fu_1613_p1));

assign add_ln220_30_fu_2815_p2 = ($signed(sum_abs_30_fu_2788_p3) + $signed(sext_ln220_45_fu_2803_p1));

assign add_ln220_31_fu_2821_p2 = ($signed(sext_ln220_46_fu_2807_p1) + $signed(sext_ln220_47_fu_2811_p1));

assign add_ln220_3_fu_1631_p2 = ($signed(sext_ln220_4_fu_1617_p1) + $signed(sext_ln220_5_fu_1621_p1));

assign add_ln220_4_fu_1710_p2 = ($signed(sum_abs_4_fu_1683_p3) + $signed(sext_ln220_6_fu_1698_p1));

assign add_ln220_5_fu_1716_p2 = ($signed(sext_ln220_7_fu_1702_p1) + $signed(sext_ln220_8_fu_1706_p1));

assign add_ln220_6_fu_1795_p2 = ($signed(sum_abs_6_fu_1768_p3) + $signed(sext_ln220_9_fu_1783_p1));

assign add_ln220_7_fu_1801_p2 = ($signed(sext_ln220_10_fu_1787_p1) + $signed(sext_ln220_11_fu_1791_p1));

assign add_ln220_8_fu_1880_p2 = ($signed(sum_abs_8_fu_1853_p3) + $signed(sext_ln220_12_fu_1868_p1));

assign add_ln220_9_fu_1886_p2 = ($signed(sext_ln220_13_fu_1872_p1) + $signed(sext_ln220_14_fu_1876_p1));

assign add_ln220_fu_1540_p2 = ($signed(select_ln212_fu_1513_p3) + $signed(sext_ln220_fu_1528_p1));

assign add_ln225_fu_3072_p2 = ($signed(sext_ln225_fu_3068_p1) + $signed(29'd131072));

assign and_ln220_10_fu_750_p2 = (tmp_240_fu_734_p3 & tmp_239_fu_720_p3);

assign and_ln220_11_fu_2003_p2 = (xor_ln220_16_fu_1997_p2 & tmp_242_fu_1989_p3);

assign and_ln220_12_fu_820_p2 = (tmp_244_fu_804_p3 & tmp_243_fu_790_p3);

assign and_ln220_13_fu_2088_p2 = (xor_ln220_19_fu_2082_p2 & tmp_246_fu_2074_p3);

assign and_ln220_14_fu_890_p2 = (tmp_248_fu_874_p3 & tmp_247_fu_860_p3);

assign and_ln220_15_fu_2173_p2 = (xor_ln220_22_fu_2167_p2 & tmp_250_fu_2159_p3);

assign and_ln220_16_fu_960_p2 = (tmp_252_fu_944_p3 & tmp_251_fu_930_p3);

assign and_ln220_17_fu_2258_p2 = (xor_ln220_25_fu_2252_p2 & tmp_254_fu_2244_p3);

assign and_ln220_18_fu_1030_p2 = (tmp_256_fu_1014_p3 & tmp_255_fu_1000_p3);

assign and_ln220_19_fu_2343_p2 = (xor_ln220_28_fu_2337_p2 & tmp_258_fu_2329_p3);

assign and_ln220_1_fu_1578_p2 = (xor_ln220_1_fu_1572_p2 & tmp_222_fu_1564_p3);

assign and_ln220_20_fu_1100_p2 = (tmp_260_fu_1084_p3 & tmp_259_fu_1070_p3);

assign and_ln220_21_fu_2428_p2 = (xor_ln220_31_fu_2422_p2 & tmp_262_fu_2414_p3);

assign and_ln220_22_fu_1170_p2 = (tmp_264_fu_1154_p3 & tmp_263_fu_1140_p3);

assign and_ln220_23_fu_2513_p2 = (xor_ln220_34_fu_2507_p2 & tmp_266_fu_2499_p3);

assign and_ln220_24_fu_1240_p2 = (tmp_268_fu_1224_p3 & tmp_267_fu_1210_p3);

assign and_ln220_25_fu_2598_p2 = (xor_ln220_37_fu_2592_p2 & tmp_270_fu_2584_p3);

assign and_ln220_26_fu_1310_p2 = (tmp_272_fu_1294_p3 & tmp_271_fu_1280_p3);

assign and_ln220_27_fu_2683_p2 = (xor_ln220_40_fu_2677_p2 & tmp_274_fu_2669_p3);

assign and_ln220_28_fu_1380_p2 = (tmp_276_fu_1364_p3 & tmp_275_fu_1350_p3);

assign and_ln220_29_fu_2768_p2 = (xor_ln220_43_fu_2762_p2 & tmp_278_fu_2754_p3);

assign and_ln220_2_fu_470_p2 = (tmp_224_fu_454_p3 & tmp_223_fu_440_p3);

assign and_ln220_30_fu_1450_p2 = (tmp_280_fu_1434_p3 & tmp_279_fu_1420_p3);

assign and_ln220_31_fu_2853_p2 = (xor_ln220_46_fu_2847_p2 & tmp_282_fu_2839_p3);

assign and_ln220_3_fu_1663_p2 = (xor_ln220_4_fu_1657_p2 & tmp_226_fu_1649_p3);

assign and_ln220_4_fu_540_p2 = (tmp_228_fu_524_p3 & tmp_227_fu_510_p3);

assign and_ln220_5_fu_1748_p2 = (xor_ln220_7_fu_1742_p2 & tmp_230_fu_1734_p3);

assign and_ln220_6_fu_610_p2 = (tmp_232_fu_594_p3 & tmp_231_fu_580_p3);

assign and_ln220_7_fu_1833_p2 = (xor_ln220_10_fu_1827_p2 & tmp_234_fu_1819_p3);

assign and_ln220_8_fu_680_p2 = (tmp_236_fu_664_p3 & tmp_235_fu_650_p3);

assign and_ln220_9_fu_1918_p2 = (xor_ln220_13_fu_1912_p2 & tmp_238_fu_1904_p3);

assign and_ln220_fu_400_p2 = (tmp_220_fu_384_p3 & tmp_219_fu_370_p3);

assign and_ln223_fu_3054_p2 = (xor_ln223_fu_3024_p2 & or_ln223_fu_3048_p2);

assign and_ln225_fu_3104_p2 = (xor_ln225_fu_3098_p2 & tmp_288_fu_3090_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (s0_b_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln214_reg_3243 == 1'd1) & (s_stats_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_157 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign avg_abs_1_fu_3006_p2 = ($signed(sext_ln223_fu_2990_p1) + $signed(zext_ln223_fu_3002_p1));

assign avg_abs_2_fu_3060_p3 = ((and_ln223_fu_3054_p2[0:0] == 1'b1) ? 28'd134217727 : sext_ln223_1_fu_3012_p1);

assign avg_abs_fu_2980_p4 = {{select_ln223_fu_2965_p3[28:6]}};

assign i_fu_2887_p3 = ((ap_phi_mux_icmp_ln2145_phi_fu_221_p4[0:0] == 1'b1) ? 5'd1 : add_ln214_fu_2881_p2);

assign icmp_ln212_fu_1496_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 12'd4095) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_2895_p2 = ((i_fu_2887_p3 == 5'd16) ? 1'b1 : 1'b0);

assign or_ln223_1_fu_3030_p2 = (xor_ln223_fu_3024_p2 | tmp_286_fu_3016_p3);

assign or_ln223_fu_3048_p2 = (xor_ln223_2_fu_3042_p2 | tmp_286_fu_3016_p3);

assign ref_tmp9_2_10_i_fu_1120_p2 = ((tmp_260_fu_1084_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_10_i_fu_1120_p4 = {{s0_b_dout[339:320]}};

assign ref_tmp9_2_10_i_fu_1120_p7 = 'bx;

assign ref_tmp9_2_10_i_fu_1120_p8 = {{and_ln220_20_fu_1100_p2}, {xor_ln220_30_fu_1106_p2}};

assign ref_tmp9_2_11_i_fu_1190_p2 = ((tmp_264_fu_1154_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_11_i_fu_1190_p4 = {{s0_b_dout[371:352]}};

assign ref_tmp9_2_11_i_fu_1190_p7 = 'bx;

assign ref_tmp9_2_11_i_fu_1190_p8 = {{and_ln220_22_fu_1170_p2}, {xor_ln220_33_fu_1176_p2}};

assign ref_tmp9_2_12_i_fu_1260_p2 = ((tmp_268_fu_1224_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_12_i_fu_1260_p4 = {{s0_b_dout[403:384]}};

assign ref_tmp9_2_12_i_fu_1260_p7 = 'bx;

assign ref_tmp9_2_12_i_fu_1260_p8 = {{and_ln220_24_fu_1240_p2}, {xor_ln220_36_fu_1246_p2}};

assign ref_tmp9_2_13_i_fu_1330_p2 = ((tmp_272_fu_1294_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_13_i_fu_1330_p4 = {{s0_b_dout[435:416]}};

assign ref_tmp9_2_13_i_fu_1330_p7 = 'bx;

assign ref_tmp9_2_13_i_fu_1330_p8 = {{and_ln220_26_fu_1310_p2}, {xor_ln220_39_fu_1316_p2}};

assign ref_tmp9_2_14_i_fu_1400_p2 = ((tmp_276_fu_1364_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_14_i_fu_1400_p4 = {{s0_b_dout[467:448]}};

assign ref_tmp9_2_14_i_fu_1400_p7 = 'bx;

assign ref_tmp9_2_14_i_fu_1400_p8 = {{and_ln220_28_fu_1380_p2}, {xor_ln220_42_fu_1386_p2}};

assign ref_tmp9_2_15_i_fu_1470_p2 = ((tmp_280_fu_1434_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_15_i_fu_1470_p4 = {{s0_b_dout[499:480]}};

assign ref_tmp9_2_15_i_fu_1470_p7 = 'bx;

assign ref_tmp9_2_15_i_fu_1470_p8 = {{and_ln220_30_fu_1450_p2}, {xor_ln220_45_fu_1456_p2}};

assign ref_tmp9_2_1_i_fu_490_p2 = ((tmp_224_fu_454_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_1_i_fu_490_p4 = {{s0_b_dout[51:32]}};

assign ref_tmp9_2_1_i_fu_490_p7 = 'bx;

assign ref_tmp9_2_1_i_fu_490_p8 = {{and_ln220_2_fu_470_p2}, {xor_ln220_3_fu_476_p2}};

assign ref_tmp9_2_2_i_fu_560_p2 = ((tmp_228_fu_524_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_2_i_fu_560_p4 = {{s0_b_dout[83:64]}};

assign ref_tmp9_2_2_i_fu_560_p7 = 'bx;

assign ref_tmp9_2_2_i_fu_560_p8 = {{and_ln220_4_fu_540_p2}, {xor_ln220_6_fu_546_p2}};

assign ref_tmp9_2_3_i_fu_630_p2 = ((tmp_232_fu_594_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_3_i_fu_630_p4 = {{s0_b_dout[115:96]}};

assign ref_tmp9_2_3_i_fu_630_p7 = 'bx;

assign ref_tmp9_2_3_i_fu_630_p8 = {{and_ln220_6_fu_610_p2}, {xor_ln220_9_fu_616_p2}};

assign ref_tmp9_2_4_i_fu_700_p2 = ((tmp_236_fu_664_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_4_i_fu_700_p4 = {{s0_b_dout[147:128]}};

assign ref_tmp9_2_4_i_fu_700_p7 = 'bx;

assign ref_tmp9_2_4_i_fu_700_p8 = {{and_ln220_8_fu_680_p2}, {xor_ln220_12_fu_686_p2}};

assign ref_tmp9_2_5_i_fu_770_p2 = ((tmp_240_fu_734_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_5_i_fu_770_p4 = {{s0_b_dout[179:160]}};

assign ref_tmp9_2_5_i_fu_770_p7 = 'bx;

assign ref_tmp9_2_5_i_fu_770_p8 = {{and_ln220_10_fu_750_p2}, {xor_ln220_15_fu_756_p2}};

assign ref_tmp9_2_6_i_fu_840_p2 = ((tmp_244_fu_804_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_6_i_fu_840_p4 = {{s0_b_dout[211:192]}};

assign ref_tmp9_2_6_i_fu_840_p7 = 'bx;

assign ref_tmp9_2_6_i_fu_840_p8 = {{and_ln220_12_fu_820_p2}, {xor_ln220_18_fu_826_p2}};

assign ref_tmp9_2_7_i_fu_910_p2 = ((tmp_248_fu_874_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_7_i_fu_910_p4 = {{s0_b_dout[243:224]}};

assign ref_tmp9_2_7_i_fu_910_p7 = 'bx;

assign ref_tmp9_2_7_i_fu_910_p8 = {{and_ln220_14_fu_890_p2}, {xor_ln220_21_fu_896_p2}};

assign ref_tmp9_2_8_i_fu_980_p2 = ((tmp_252_fu_944_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_8_i_fu_980_p4 = {{s0_b_dout[275:256]}};

assign ref_tmp9_2_8_i_fu_980_p7 = 'bx;

assign ref_tmp9_2_8_i_fu_980_p8 = {{and_ln220_16_fu_960_p2}, {xor_ln220_24_fu_966_p2}};

assign ref_tmp9_2_9_i_fu_1050_p2 = ((tmp_256_fu_1014_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_9_i_fu_1050_p4 = {{s0_b_dout[307:288]}};

assign ref_tmp9_2_9_i_fu_1050_p7 = 'bx;

assign ref_tmp9_2_9_i_fu_1050_p8 = {{and_ln220_18_fu_1030_p2}, {xor_ln220_27_fu_1036_p2}};

assign ref_tmp9_2_i_fu_420_p2 = ((tmp_220_fu_384_p3[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign ref_tmp9_2_i_fu_420_p7 = 'bx;

assign ref_tmp9_2_i_fu_420_p8 = {{and_ln220_fu_400_p2}, {xor_ln220_fu_406_p2}};

assign s_stats_din = ((xor_ln225_1_fu_3110_p2[0:0] == 1'b1) ? select_ln225_fu_3116_p3 : trunc_ln225_fu_3086_p1);

assign select_ln212_fu_1513_p3 = ((ap_phi_mux_icmp_ln2145_phi_fu_221_p4[0:0] == 1'b1) ? 36'd0 : sum_abs4_fu_200);

assign select_ln220_10_fu_1845_p3 = ((and_ln220_7_fu_1833_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_13_fu_1930_p3 = ((and_ln220_9_fu_1918_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_16_fu_2015_p3 = ((and_ln220_11_fu_2003_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_19_fu_2100_p3 = ((and_ln220_13_fu_2088_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_1_fu_1590_p3 = ((and_ln220_1_fu_1578_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_22_fu_2185_p3 = ((and_ln220_15_fu_2173_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_25_fu_2270_p3 = ((and_ln220_17_fu_2258_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_28_fu_2355_p3 = ((and_ln220_19_fu_2343_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_31_fu_2440_p3 = ((and_ln220_21_fu_2428_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_34_fu_2525_p3 = ((and_ln220_23_fu_2513_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_37_fu_2610_p3 = ((and_ln220_25_fu_2598_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_40_fu_2695_p3 = ((and_ln220_27_fu_2683_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_43_fu_2780_p3 = ((and_ln220_29_fu_2768_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_46_fu_2865_p3 = ((and_ln220_31_fu_2853_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_4_fu_1675_p3 = ((and_ln220_3_fu_1663_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln220_7_fu_1760_p3 = ((and_ln220_5_fu_1748_p2[0:0] == 1'b1) ? 36'd34359738367 : 36'd34359738368);

assign select_ln223_fu_2965_p3 = ((tmp_283_reg_3248[0:0] == 1'b1) ? sub_ln223_1_fu_2956_p2 : zext_ln223_2_fu_2962_p1);

assign select_ln225_fu_3116_p3 = ((and_ln225_fu_3104_p2[0:0] == 1'b1) ? 28'd134217727 : 28'd134217728);

assign sext_ln220_10_fu_1787_p1 = sum_abs_6_fu_1768_p3;

assign sext_ln220_11_fu_1791_p1 = shl_ln220_3_fu_1776_p3;

assign sext_ln220_12_fu_1868_p1 = shl_ln220_4_fu_1861_p3;

assign sext_ln220_13_fu_1872_p1 = sum_abs_8_fu_1853_p3;

assign sext_ln220_14_fu_1876_p1 = shl_ln220_4_fu_1861_p3;

assign sext_ln220_15_fu_1953_p1 = shl_ln220_5_fu_1946_p3;

assign sext_ln220_16_fu_1957_p1 = sum_abs_10_fu_1938_p3;

assign sext_ln220_17_fu_1961_p1 = shl_ln220_5_fu_1946_p3;

assign sext_ln220_18_fu_2038_p1 = shl_ln220_6_fu_2031_p3;

assign sext_ln220_19_fu_2042_p1 = sum_abs_12_fu_2023_p3;

assign sext_ln220_1_fu_1532_p1 = select_ln212_fu_1513_p3;

assign sext_ln220_20_fu_2046_p1 = shl_ln220_6_fu_2031_p3;

assign sext_ln220_21_fu_2123_p1 = shl_ln220_7_fu_2116_p3;

assign sext_ln220_22_fu_2127_p1 = sum_abs_14_fu_2108_p3;

assign sext_ln220_23_fu_2131_p1 = shl_ln220_7_fu_2116_p3;

assign sext_ln220_24_fu_2208_p1 = shl_ln220_8_fu_2201_p3;

assign sext_ln220_25_fu_2212_p1 = sum_abs_16_fu_2193_p3;

assign sext_ln220_26_fu_2216_p1 = shl_ln220_8_fu_2201_p3;

assign sext_ln220_27_fu_2293_p1 = shl_ln220_9_fu_2286_p3;

assign sext_ln220_28_fu_2297_p1 = sum_abs_18_fu_2278_p3;

assign sext_ln220_29_fu_2301_p1 = shl_ln220_9_fu_2286_p3;

assign sext_ln220_2_fu_1536_p1 = shl_ln_fu_1521_p3;

assign sext_ln220_30_fu_2378_p1 = shl_ln220_s_fu_2371_p3;

assign sext_ln220_31_fu_2382_p1 = sum_abs_20_fu_2363_p3;

assign sext_ln220_32_fu_2386_p1 = shl_ln220_s_fu_2371_p3;

assign sext_ln220_33_fu_2463_p1 = shl_ln220_10_fu_2456_p3;

assign sext_ln220_34_fu_2467_p1 = sum_abs_22_fu_2448_p3;

assign sext_ln220_35_fu_2471_p1 = shl_ln220_10_fu_2456_p3;

assign sext_ln220_36_fu_2548_p1 = shl_ln220_11_fu_2541_p3;

assign sext_ln220_37_fu_2552_p1 = sum_abs_24_fu_2533_p3;

assign sext_ln220_38_fu_2556_p1 = shl_ln220_11_fu_2541_p3;

assign sext_ln220_39_fu_2633_p1 = shl_ln220_12_fu_2626_p3;

assign sext_ln220_3_fu_1613_p1 = shl_ln220_1_fu_1606_p3;

assign sext_ln220_40_fu_2637_p1 = sum_abs_26_fu_2618_p3;

assign sext_ln220_41_fu_2641_p1 = shl_ln220_12_fu_2626_p3;

assign sext_ln220_42_fu_2718_p1 = shl_ln220_13_fu_2711_p3;

assign sext_ln220_43_fu_2722_p1 = sum_abs_28_fu_2703_p3;

assign sext_ln220_44_fu_2726_p1 = shl_ln220_13_fu_2711_p3;

assign sext_ln220_45_fu_2803_p1 = shl_ln220_14_fu_2796_p3;

assign sext_ln220_46_fu_2807_p1 = sum_abs_30_fu_2788_p3;

assign sext_ln220_47_fu_2811_p1 = shl_ln220_14_fu_2796_p3;

assign sext_ln220_4_fu_1617_p1 = sum_abs_2_fu_1598_p3;

assign sext_ln220_5_fu_1621_p1 = shl_ln220_1_fu_1606_p3;

assign sext_ln220_6_fu_1698_p1 = shl_ln220_2_fu_1691_p3;

assign sext_ln220_7_fu_1702_p1 = sum_abs_4_fu_1683_p3;

assign sext_ln220_8_fu_1706_p1 = shl_ln220_2_fu_1691_p3;

assign sext_ln220_9_fu_1783_p1 = shl_ln220_3_fu_1776_p3;

assign sext_ln220_fu_1528_p1 = shl_ln_fu_1521_p3;

assign sext_ln223_1_fu_3012_p1 = avg_abs_1_fu_3006_p2;

assign sext_ln223_fu_2990_p1 = $signed(avg_abs_fu_2980_p4);

assign sext_ln225_fu_3068_p1 = $signed(avg_abs_2_fu_3060_p3);

assign shl_ln220_10_fu_2456_p3 = {{ref_tmp9_2_11_i_reg_3209}, {10'd0}};

assign shl_ln220_11_fu_2541_p3 = {{ref_tmp9_2_12_i_reg_3214}, {10'd0}};

assign shl_ln220_12_fu_2626_p3 = {{ref_tmp9_2_13_i_reg_3219}, {10'd0}};

assign shl_ln220_13_fu_2711_p3 = {{ref_tmp9_2_14_i_reg_3224}, {10'd0}};

assign shl_ln220_14_fu_2796_p3 = {{ref_tmp9_2_15_i_reg_3229}, {10'd0}};

assign shl_ln220_1_fu_1606_p3 = {{ref_tmp9_2_1_i_reg_3159}, {10'd0}};

assign shl_ln220_2_fu_1691_p3 = {{ref_tmp9_2_2_i_reg_3164}, {10'd0}};

assign shl_ln220_3_fu_1776_p3 = {{ref_tmp9_2_3_i_reg_3169}, {10'd0}};

assign shl_ln220_4_fu_1861_p3 = {{ref_tmp9_2_4_i_reg_3174}, {10'd0}};

assign shl_ln220_5_fu_1946_p3 = {{ref_tmp9_2_5_i_reg_3179}, {10'd0}};

assign shl_ln220_6_fu_2031_p3 = {{ref_tmp9_2_6_i_reg_3184}, {10'd0}};

assign shl_ln220_7_fu_2116_p3 = {{ref_tmp9_2_7_i_reg_3189}, {10'd0}};

assign shl_ln220_8_fu_2201_p3 = {{ref_tmp9_2_8_i_reg_3194}, {10'd0}};

assign shl_ln220_9_fu_2286_p3 = {{ref_tmp9_2_9_i_reg_3199}, {10'd0}};

assign shl_ln220_s_fu_2371_p3 = {{ref_tmp9_2_10_i_reg_3204}, {10'd0}};

assign shl_ln2_fu_2929_p3 = {{sum_abs_reg_3238}, {24'd0}};

assign shl_ln_fu_1521_p3 = {{ref_tmp9_2_i_reg_3154}, {10'd0}};

assign sub_ln220_10_fu_1078_p2 = (20'd0 - v_25_fu_322_p3);

assign sub_ln220_11_fu_1148_p2 = (20'd0 - v_26_fu_330_p3);

assign sub_ln220_12_fu_1218_p2 = (20'd0 - v_27_fu_338_p3);

assign sub_ln220_13_fu_1288_p2 = (20'd0 - v_28_fu_346_p3);

assign sub_ln220_14_fu_1358_p2 = (20'd0 - v_29_fu_354_p3);

assign sub_ln220_15_fu_1428_p2 = (20'd0 - v_30_fu_362_p3);

assign sub_ln220_1_fu_448_p2 = (20'd0 - v_16_fu_250_p3);

assign sub_ln220_2_fu_518_p2 = (20'd0 - v_17_fu_258_p3);

assign sub_ln220_3_fu_588_p2 = (20'd0 - v_18_fu_266_p3);

assign sub_ln220_4_fu_658_p2 = (20'd0 - v_19_fu_274_p3);

assign sub_ln220_5_fu_728_p2 = (20'd0 - v_20_fu_282_p3);

assign sub_ln220_6_fu_798_p2 = (20'd0 - v_21_fu_290_p3);

assign sub_ln220_7_fu_868_p2 = (20'd0 - v_22_fu_298_p3);

assign sub_ln220_8_fu_938_p2 = (20'd0 - v_23_fu_306_p3);

assign sub_ln220_9_fu_1008_p2 = (20'd0 - v_24_fu_314_p3);

assign sub_ln220_fu_378_p2 = (20'd0 - v_fu_246_p1);

assign sub_ln223_1_fu_2956_p2 = (29'd0 - zext_ln223_1_fu_2952_p1);

assign sub_ln223_fu_2936_p2 = (60'd0 - shl_ln2_fu_2929_p3);

assign sum_abs_10_fu_1938_p3 = ((xor_ln220_14_fu_1924_p2[0:0] == 1'b1) ? select_ln220_13_fu_1930_p3 : sum_abs_9_fu_1900_p1);

assign sum_abs_11_fu_1985_p1 = add_ln220_11_fu_1971_p2[35:0];

assign sum_abs_12_fu_2023_p3 = ((xor_ln220_17_fu_2009_p2[0:0] == 1'b1) ? select_ln220_16_fu_2015_p3 : sum_abs_11_fu_1985_p1);

assign sum_abs_13_fu_2070_p1 = add_ln220_13_fu_2056_p2[35:0];

assign sum_abs_14_fu_2108_p3 = ((xor_ln220_20_fu_2094_p2[0:0] == 1'b1) ? select_ln220_19_fu_2100_p3 : sum_abs_13_fu_2070_p1);

assign sum_abs_15_fu_2155_p1 = add_ln220_15_fu_2141_p2[35:0];

assign sum_abs_16_fu_2193_p3 = ((xor_ln220_23_fu_2179_p2[0:0] == 1'b1) ? select_ln220_22_fu_2185_p3 : sum_abs_15_fu_2155_p1);

assign sum_abs_17_fu_2240_p1 = add_ln220_17_fu_2226_p2[35:0];

assign sum_abs_18_fu_2278_p3 = ((xor_ln220_26_fu_2264_p2[0:0] == 1'b1) ? select_ln220_25_fu_2270_p3 : sum_abs_17_fu_2240_p1);

assign sum_abs_19_fu_2325_p1 = add_ln220_19_fu_2311_p2[35:0];

assign sum_abs_1_fu_1560_p1 = add_ln220_1_fu_1546_p2[35:0];

assign sum_abs_20_fu_2363_p3 = ((xor_ln220_29_fu_2349_p2[0:0] == 1'b1) ? select_ln220_28_fu_2355_p3 : sum_abs_19_fu_2325_p1);

assign sum_abs_21_fu_2410_p1 = add_ln220_21_fu_2396_p2[35:0];

assign sum_abs_22_fu_2448_p3 = ((xor_ln220_32_fu_2434_p2[0:0] == 1'b1) ? select_ln220_31_fu_2440_p3 : sum_abs_21_fu_2410_p1);

assign sum_abs_23_fu_2495_p1 = add_ln220_23_fu_2481_p2[35:0];

assign sum_abs_24_fu_2533_p3 = ((xor_ln220_35_fu_2519_p2[0:0] == 1'b1) ? select_ln220_34_fu_2525_p3 : sum_abs_23_fu_2495_p1);

assign sum_abs_25_fu_2580_p1 = add_ln220_25_fu_2566_p2[35:0];

assign sum_abs_26_fu_2618_p3 = ((xor_ln220_38_fu_2604_p2[0:0] == 1'b1) ? select_ln220_37_fu_2610_p3 : sum_abs_25_fu_2580_p1);

assign sum_abs_27_fu_2665_p1 = add_ln220_27_fu_2651_p2[35:0];

assign sum_abs_28_fu_2703_p3 = ((xor_ln220_41_fu_2689_p2[0:0] == 1'b1) ? select_ln220_40_fu_2695_p3 : sum_abs_27_fu_2665_p1);

assign sum_abs_29_fu_2750_p1 = add_ln220_29_fu_2736_p2[35:0];

assign sum_abs_2_fu_1598_p3 = ((xor_ln220_2_fu_1584_p2[0:0] == 1'b1) ? select_ln220_1_fu_1590_p3 : sum_abs_1_fu_1560_p1);

assign sum_abs_30_fu_2788_p3 = ((xor_ln220_44_fu_2774_p2[0:0] == 1'b1) ? select_ln220_43_fu_2780_p3 : sum_abs_29_fu_2750_p1);

assign sum_abs_31_fu_2835_p1 = add_ln220_31_fu_2821_p2[35:0];

assign sum_abs_3_fu_1645_p1 = add_ln220_3_fu_1631_p2[35:0];

assign sum_abs_4_fu_1683_p3 = ((xor_ln220_5_fu_1669_p2[0:0] == 1'b1) ? select_ln220_4_fu_1675_p3 : sum_abs_3_fu_1645_p1);

assign sum_abs_5_fu_1730_p1 = add_ln220_5_fu_1716_p2[35:0];

assign sum_abs_6_fu_1768_p3 = ((xor_ln220_8_fu_1754_p2[0:0] == 1'b1) ? select_ln220_7_fu_1760_p3 : sum_abs_5_fu_1730_p1);

assign sum_abs_7_fu_1815_p1 = add_ln220_7_fu_1801_p2[35:0];

assign sum_abs_8_fu_1853_p3 = ((xor_ln220_11_fu_1839_p2[0:0] == 1'b1) ? select_ln220_10_fu_1845_p3 : sum_abs_7_fu_1815_p1);

assign sum_abs_9_fu_1900_p1 = add_ln220_9_fu_1886_p2[35:0];

assign sum_abs_fu_2873_p3 = ((xor_ln220_47_fu_2859_p2[0:0] == 1'b1) ? select_ln220_46_fu_2865_p3 : sum_abs_31_fu_2835_p1);

assign tmp_219_fu_370_p3 = s0_b_dout[32'd19];

assign tmp_220_fu_384_p3 = sub_ln220_fu_378_p2[32'd19];

assign tmp_221_fu_1552_p3 = add_ln220_1_fu_1546_p2[32'd36];

assign tmp_222_fu_1564_p3 = add_ln220_fu_1540_p2[32'd35];

assign tmp_223_fu_440_p3 = s0_b_dout[512'd51];

assign tmp_224_fu_454_p3 = sub_ln220_1_fu_448_p2[32'd19];

assign tmp_225_fu_1637_p3 = add_ln220_3_fu_1631_p2[32'd36];

assign tmp_226_fu_1649_p3 = add_ln220_2_fu_1625_p2[32'd35];

assign tmp_227_fu_510_p3 = s0_b_dout[512'd83];

assign tmp_228_fu_524_p3 = sub_ln220_2_fu_518_p2[32'd19];

assign tmp_229_fu_1722_p3 = add_ln220_5_fu_1716_p2[32'd36];

assign tmp_230_fu_1734_p3 = add_ln220_4_fu_1710_p2[32'd35];

assign tmp_231_fu_580_p3 = s0_b_dout[512'd115];

assign tmp_232_fu_594_p3 = sub_ln220_3_fu_588_p2[32'd19];

assign tmp_233_fu_1807_p3 = add_ln220_7_fu_1801_p2[32'd36];

assign tmp_234_fu_1819_p3 = add_ln220_6_fu_1795_p2[32'd35];

assign tmp_235_fu_650_p3 = s0_b_dout[512'd147];

assign tmp_236_fu_664_p3 = sub_ln220_4_fu_658_p2[32'd19];

assign tmp_237_fu_1892_p3 = add_ln220_9_fu_1886_p2[32'd36];

assign tmp_238_fu_1904_p3 = add_ln220_8_fu_1880_p2[32'd35];

assign tmp_239_fu_720_p3 = s0_b_dout[512'd179];

assign tmp_240_fu_734_p3 = sub_ln220_5_fu_728_p2[32'd19];

assign tmp_241_fu_1977_p3 = add_ln220_11_fu_1971_p2[32'd36];

assign tmp_242_fu_1989_p3 = add_ln220_10_fu_1965_p2[32'd35];

assign tmp_243_fu_790_p3 = s0_b_dout[512'd211];

assign tmp_244_fu_804_p3 = sub_ln220_6_fu_798_p2[32'd19];

assign tmp_245_fu_2062_p3 = add_ln220_13_fu_2056_p2[32'd36];

assign tmp_246_fu_2074_p3 = add_ln220_12_fu_2050_p2[32'd35];

assign tmp_247_fu_860_p3 = s0_b_dout[512'd243];

assign tmp_248_fu_874_p3 = sub_ln220_7_fu_868_p2[32'd19];

assign tmp_249_fu_2147_p3 = add_ln220_15_fu_2141_p2[32'd36];

assign tmp_250_fu_2159_p3 = add_ln220_14_fu_2135_p2[32'd35];

assign tmp_251_fu_930_p3 = s0_b_dout[512'd275];

assign tmp_252_fu_944_p3 = sub_ln220_8_fu_938_p2[32'd19];

assign tmp_253_fu_2232_p3 = add_ln220_17_fu_2226_p2[32'd36];

assign tmp_254_fu_2244_p3 = add_ln220_16_fu_2220_p2[32'd35];

assign tmp_255_fu_1000_p3 = s0_b_dout[512'd307];

assign tmp_256_fu_1014_p3 = sub_ln220_9_fu_1008_p2[32'd19];

assign tmp_257_fu_2317_p3 = add_ln220_19_fu_2311_p2[32'd36];

assign tmp_258_fu_2329_p3 = add_ln220_18_fu_2305_p2[32'd35];

assign tmp_259_fu_1070_p3 = s0_b_dout[512'd339];

assign tmp_260_fu_1084_p3 = sub_ln220_10_fu_1078_p2[32'd19];

assign tmp_261_fu_2402_p3 = add_ln220_21_fu_2396_p2[32'd36];

assign tmp_262_fu_2414_p3 = add_ln220_20_fu_2390_p2[32'd35];

assign tmp_263_fu_1140_p3 = s0_b_dout[512'd371];

assign tmp_264_fu_1154_p3 = sub_ln220_11_fu_1148_p2[32'd19];

assign tmp_265_fu_2487_p3 = add_ln220_23_fu_2481_p2[32'd36];

assign tmp_266_fu_2499_p3 = add_ln220_22_fu_2475_p2[32'd35];

assign tmp_267_fu_1210_p3 = s0_b_dout[512'd403];

assign tmp_268_fu_1224_p3 = sub_ln220_12_fu_1218_p2[32'd19];

assign tmp_269_fu_2572_p3 = add_ln220_25_fu_2566_p2[32'd36];

assign tmp_270_fu_2584_p3 = add_ln220_24_fu_2560_p2[32'd35];

assign tmp_271_fu_1280_p3 = s0_b_dout[512'd435];

assign tmp_272_fu_1294_p3 = sub_ln220_13_fu_1288_p2[32'd19];

assign tmp_273_fu_2657_p3 = add_ln220_27_fu_2651_p2[32'd36];

assign tmp_274_fu_2669_p3 = add_ln220_26_fu_2645_p2[32'd35];

assign tmp_275_fu_1350_p3 = s0_b_dout[512'd467];

assign tmp_276_fu_1364_p3 = sub_ln220_14_fu_1358_p2[32'd19];

assign tmp_277_fu_2742_p3 = add_ln220_29_fu_2736_p2[32'd36];

assign tmp_278_fu_2754_p3 = add_ln220_28_fu_2730_p2[32'd35];

assign tmp_279_fu_1420_p3 = s0_b_dout[512'd499];

assign tmp_280_fu_1434_p3 = sub_ln220_15_fu_1428_p2[32'd19];

assign tmp_281_fu_2827_p3 = add_ln220_31_fu_2821_p2[32'd36];

assign tmp_282_fu_2839_p3 = add_ln220_30_fu_2815_p2[32'd35];

assign tmp_284_fu_2972_p3 = select_ln223_fu_2965_p3[32'd28];

assign tmp_285_fu_2994_p3 = select_ln223_fu_2965_p3[32'd5];

assign tmp_286_fu_3016_p3 = avg_abs_1_fu_3006_p2[32'd23];

assign tmp_287_fu_3078_p3 = add_ln225_fu_3072_p2[32'd28];

assign tmp_288_fu_3090_p3 = add_ln225_fu_3072_p2[32'd27];

assign tmp_fu_2942_p4 = {{sub_ln223_fu_2936_p2[59:32]}};

assign trunc_ln225_fu_3086_p1 = add_ln225_fu_3072_p2[27:0];

assign v_16_fu_250_p3 = {{s0_b_dout[51:32]}};

assign v_17_fu_258_p3 = {{s0_b_dout[83:64]}};

assign v_18_fu_266_p3 = {{s0_b_dout[115:96]}};

assign v_19_fu_274_p3 = {{s0_b_dout[147:128]}};

assign v_20_fu_282_p3 = {{s0_b_dout[179:160]}};

assign v_21_fu_290_p3 = {{s0_b_dout[211:192]}};

assign v_22_fu_298_p3 = {{s0_b_dout[243:224]}};

assign v_23_fu_306_p3 = {{s0_b_dout[275:256]}};

assign v_24_fu_314_p3 = {{s0_b_dout[307:288]}};

assign v_25_fu_322_p3 = {{s0_b_dout[339:320]}};

assign v_26_fu_330_p3 = {{s0_b_dout[371:352]}};

assign v_27_fu_338_p3 = {{s0_b_dout[403:384]}};

assign v_28_fu_346_p3 = {{s0_b_dout[435:416]}};

assign v_29_fu_354_p3 = {{s0_b_dout[467:448]}};

assign v_30_fu_362_p3 = {{s0_b_dout[499:480]}};

assign v_fu_246_p1 = s0_b_dout[19:0];

assign xor_ln220_10_fu_1827_p2 = (tmp_233_fu_1807_p3 ^ 1'd1);

assign xor_ln220_11_fu_1839_p2 = (tmp_234_fu_1819_p3 ^ tmp_233_fu_1807_p3);

assign xor_ln220_12_fu_686_p2 = (tmp_235_fu_650_p3 ^ 1'd1);

assign xor_ln220_13_fu_1912_p2 = (tmp_237_fu_1892_p3 ^ 1'd1);

assign xor_ln220_14_fu_1924_p2 = (tmp_238_fu_1904_p3 ^ tmp_237_fu_1892_p3);

assign xor_ln220_15_fu_756_p2 = (tmp_239_fu_720_p3 ^ 1'd1);

assign xor_ln220_16_fu_1997_p2 = (tmp_241_fu_1977_p3 ^ 1'd1);

assign xor_ln220_17_fu_2009_p2 = (tmp_242_fu_1989_p3 ^ tmp_241_fu_1977_p3);

assign xor_ln220_18_fu_826_p2 = (tmp_243_fu_790_p3 ^ 1'd1);

assign xor_ln220_19_fu_2082_p2 = (tmp_245_fu_2062_p3 ^ 1'd1);

assign xor_ln220_1_fu_1572_p2 = (tmp_221_fu_1552_p3 ^ 1'd1);

assign xor_ln220_20_fu_2094_p2 = (tmp_246_fu_2074_p3 ^ tmp_245_fu_2062_p3);

assign xor_ln220_21_fu_896_p2 = (tmp_247_fu_860_p3 ^ 1'd1);

assign xor_ln220_22_fu_2167_p2 = (tmp_249_fu_2147_p3 ^ 1'd1);

assign xor_ln220_23_fu_2179_p2 = (tmp_250_fu_2159_p3 ^ tmp_249_fu_2147_p3);

assign xor_ln220_24_fu_966_p2 = (tmp_251_fu_930_p3 ^ 1'd1);

assign xor_ln220_25_fu_2252_p2 = (tmp_253_fu_2232_p3 ^ 1'd1);

assign xor_ln220_26_fu_2264_p2 = (tmp_254_fu_2244_p3 ^ tmp_253_fu_2232_p3);

assign xor_ln220_27_fu_1036_p2 = (tmp_255_fu_1000_p3 ^ 1'd1);

assign xor_ln220_28_fu_2337_p2 = (tmp_257_fu_2317_p3 ^ 1'd1);

assign xor_ln220_29_fu_2349_p2 = (tmp_258_fu_2329_p3 ^ tmp_257_fu_2317_p3);

assign xor_ln220_2_fu_1584_p2 = (tmp_222_fu_1564_p3 ^ tmp_221_fu_1552_p3);

assign xor_ln220_30_fu_1106_p2 = (tmp_259_fu_1070_p3 ^ 1'd1);

assign xor_ln220_31_fu_2422_p2 = (tmp_261_fu_2402_p3 ^ 1'd1);

assign xor_ln220_32_fu_2434_p2 = (tmp_262_fu_2414_p3 ^ tmp_261_fu_2402_p3);

assign xor_ln220_33_fu_1176_p2 = (tmp_263_fu_1140_p3 ^ 1'd1);

assign xor_ln220_34_fu_2507_p2 = (tmp_265_fu_2487_p3 ^ 1'd1);

assign xor_ln220_35_fu_2519_p2 = (tmp_266_fu_2499_p3 ^ tmp_265_fu_2487_p3);

assign xor_ln220_36_fu_1246_p2 = (tmp_267_fu_1210_p3 ^ 1'd1);

assign xor_ln220_37_fu_2592_p2 = (tmp_269_fu_2572_p3 ^ 1'd1);

assign xor_ln220_38_fu_2604_p2 = (tmp_270_fu_2584_p3 ^ tmp_269_fu_2572_p3);

assign xor_ln220_39_fu_1316_p2 = (tmp_271_fu_1280_p3 ^ 1'd1);

assign xor_ln220_3_fu_476_p2 = (tmp_223_fu_440_p3 ^ 1'd1);

assign xor_ln220_40_fu_2677_p2 = (tmp_273_fu_2657_p3 ^ 1'd1);

assign xor_ln220_41_fu_2689_p2 = (tmp_274_fu_2669_p3 ^ tmp_273_fu_2657_p3);

assign xor_ln220_42_fu_1386_p2 = (tmp_275_fu_1350_p3 ^ 1'd1);

assign xor_ln220_43_fu_2762_p2 = (tmp_277_fu_2742_p3 ^ 1'd1);

assign xor_ln220_44_fu_2774_p2 = (tmp_278_fu_2754_p3 ^ tmp_277_fu_2742_p3);

assign xor_ln220_45_fu_1456_p2 = (tmp_279_fu_1420_p3 ^ 1'd1);

assign xor_ln220_46_fu_2847_p2 = (tmp_281_fu_2827_p3 ^ 1'd1);

assign xor_ln220_47_fu_2859_p2 = (tmp_282_fu_2839_p3 ^ tmp_281_fu_2827_p3);

assign xor_ln220_4_fu_1657_p2 = (tmp_225_fu_1637_p3 ^ 1'd1);

assign xor_ln220_5_fu_1669_p2 = (tmp_226_fu_1649_p3 ^ tmp_225_fu_1637_p3);

assign xor_ln220_6_fu_546_p2 = (tmp_227_fu_510_p3 ^ 1'd1);

assign xor_ln220_7_fu_1742_p2 = (tmp_229_fu_1722_p3 ^ 1'd1);

assign xor_ln220_8_fu_1754_p2 = (tmp_230_fu_1734_p3 ^ tmp_229_fu_1722_p3);

assign xor_ln220_9_fu_616_p2 = (tmp_231_fu_580_p3 ^ 1'd1);

assign xor_ln220_fu_406_p2 = (tmp_219_fu_370_p3 ^ 1'd1);

assign xor_ln223_1_fu_3036_p2 = (tmp_284_fu_2972_p3 ^ or_ln223_1_fu_3030_p2);

assign xor_ln223_2_fu_3042_p2 = (xor_ln223_1_fu_3036_p2 ^ 1'd1);

assign xor_ln223_fu_3024_p2 = (tmp_284_fu_2972_p3 ^ 1'd1);

assign xor_ln225_1_fu_3110_p2 = (tmp_288_fu_3090_p3 ^ tmp_287_fu_3078_p3);

assign xor_ln225_fu_3098_p2 = (tmp_287_fu_3078_p3 ^ 1'd1);

assign zext_ln223_1_fu_2952_p1 = tmp_fu_2942_p4;

assign zext_ln223_2_fu_2962_p1 = tmp_48_reg_3253;

assign zext_ln223_fu_3002_p1 = tmp_285_fu_2994_p3;

endmodule //top_kernel_k2_stats
