

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "7", "40", "42", "77", "79", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2131", "EstimateLatencyMax" : "2131",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "entry_proc_U0"},
			{"ID" : "5", "Name" : "load_dual_U0"}],
		"OutputProcess" : [
			{"ID" : "79", "Name" : "store_dual_U0"}],
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_dual_U0", "Port" : "gmem0"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "79", "SubInstance" : "store_dual_U0", "Port" : "gmem1"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "sa_in", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_dual_U0", "Port" : "sa_in"},
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "sa_in"}]},
			{"Name" : "sb_in", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "load_dual_U0", "Port" : "sb_in"},
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "sb_in"}]},
			{"Name" : "x_prev_0", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "x_prev_0"}]},
			{"Name" : "x_prev_1", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "x_prev_1"}]},
			{"Name" : "sa_stats", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "sa_stats"},
					{"ID" : "40", "SubInstance" : "k2_stats_dual_U0", "Port" : "sa_stats"}]},
			{"Name" : "sa_join", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "sa_join"},
					{"ID" : "42", "SubInstance" : "k3_dual_norm_U0", "Port" : "sa_join"}]},
			{"Name" : "sb_stats", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "sb_stats"},
					{"ID" : "40", "SubInstance" : "k2_stats_dual_U0", "Port" : "sb_stats"}]},
			{"Name" : "sb_join", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "super_kernel_32_U0", "Port" : "sb_join"},
					{"ID" : "42", "SubInstance" : "k3_dual_norm_U0", "Port" : "sb_join"}]},
			{"Name" : "s_st", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "k2_stats_dual_U0", "Port" : "s_st"},
					{"ID" : "42", "SubInstance" : "k3_dual_norm_U0", "Port" : "s_st"}]},
			{"Name" : "sa_norm", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "k3_dual_norm_U0", "Port" : "sa_norm"},
					{"ID" : "77", "SubInstance" : "k4_dual_post_U0", "Port" : "sa_norm"}]},
			{"Name" : "sb_norm", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "k3_dual_norm_U0", "Port" : "sb_norm"},
					{"ID" : "77", "SubInstance" : "k4_dual_post_U0", "Port" : "sb_norm"}]},
			{"Name" : "sa_post", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "77", "SubInstance" : "k4_dual_post_U0", "Port" : "sa_post"},
					{"ID" : "79", "SubInstance" : "store_dual_U0", "Port" : "sa_post"}]},
			{"Name" : "sb_post", "Type" : "Fifo", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "77", "SubInstance" : "k4_dual_post_U0", "Port" : "sb_post"},
					{"ID" : "79", "SubInstance" : "store_dual_U0", "Port" : "sb_post"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["79"], "DependentChan" : "81", "DependentChanDepth" : "7", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.load_dual_U0", "Parent" : "0", "Child" : ["6"],
		"CDFG" : "load_dual",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2059", "EstimateLatencyMax" : "2059",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "sa_in", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["7"], "DependentChan" : "82", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_in", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["7"], "DependentChan" : "83", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_in_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "LOAD_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter10", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter10", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_dual_U0.flow_control_loop_pipe_U", "Parent" : "5"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0", "Parent" : "0", "Child" : ["8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39"],
		"CDFG" : "super_kernel_32",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2051", "EstimateLatencyMax" : "2051",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "5",
		"StartFifo" : "start_for_super_kernel_32_U0_U",
		"Port" : [
			{"Name" : "x_prev_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "x_prev_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "sa_in", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "82", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_in", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["5"], "DependentChan" : "83", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_stats", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["40"], "DependentChan" : "84", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_stats_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_join", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["42"], "DependentChan" : "85", "DependentChanDepth" : "512", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_join_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_stats", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["40"], "DependentChan" : "86", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_stats_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_join", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["42"], "DependentChan" : "87", "DependentChanDepth" : "512", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_join_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "FRONT_32_LOOP", "PipelineType" : "pipeline",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "PreState" : ["ap_ST_fsm_state1"], "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "PostState" : ["ap_ST_fsm_state5"]}}]},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U7", "Parent" : "7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U8", "Parent" : "7"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U9", "Parent" : "7"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U10", "Parent" : "7"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U11", "Parent" : "7"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U12", "Parent" : "7"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U13", "Parent" : "7"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U14", "Parent" : "7"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U15", "Parent" : "7"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U16", "Parent" : "7"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U17", "Parent" : "7"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U18", "Parent" : "7"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U19", "Parent" : "7"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U20", "Parent" : "7"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U21", "Parent" : "7"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U22", "Parent" : "7"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U23", "Parent" : "7"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U24", "Parent" : "7"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U25", "Parent" : "7"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U26", "Parent" : "7"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U27", "Parent" : "7"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U28", "Parent" : "7"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U29", "Parent" : "7"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U30", "Parent" : "7"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U31", "Parent" : "7"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U32", "Parent" : "7"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U33", "Parent" : "7"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U34", "Parent" : "7"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U35", "Parent" : "7"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U36", "Parent" : "7"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U37", "Parent" : "7"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.super_kernel_32_U0.sparsemux_9_3_20_1_1_U38", "Parent" : "7"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k2_stats_dual_U0", "Parent" : "0", "Child" : ["41"],
		"CDFG" : "k2_stats_dual",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2051", "EstimateLatencyMax" : "2051",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "7",
		"StartFifo" : "start_for_k2_stats_dual_U0_U",
		"Port" : [
			{"Name" : "s_st", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["42"], "DependentChan" : "88", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "s_st_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_stats", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "84", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_stats_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_stats", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "86", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_stats_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_395_1_VITIS_LOOP_397_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_stats_dual_U0.flow_control_loop_pipe_U", "Parent" : "40"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0", "Parent" : "0", "Child" : ["43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76"],
		"CDFG" : "k3_dual_norm",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2106", "EstimateLatencyMax" : "2106",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "7",
		"StartFifo" : "start_for_k3_dual_norm_U0_U",
		"Port" : [
			{"Name" : "s_st", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["40"], "DependentChan" : "88", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "s_st_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_join", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "85", "DependentChanDepth" : "512", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_join_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_join", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "87", "DependentChanDepth" : "512", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_join_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_norm", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["77"], "DependentChan" : "89", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_norm_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_norm", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["77"], "DependentChan" : "90", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_norm_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_431_1_VITIS_LOOP_434_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter57", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter57", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U49", "Parent" : "42"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U50", "Parent" : "42"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U51", "Parent" : "42"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U52", "Parent" : "42"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U53", "Parent" : "42"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U54", "Parent" : "42"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U55", "Parent" : "42"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U56", "Parent" : "42"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U57", "Parent" : "42"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U58", "Parent" : "42"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U59", "Parent" : "42"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U60", "Parent" : "42"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U61", "Parent" : "42"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U62", "Parent" : "42"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U63", "Parent" : "42"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U64", "Parent" : "42"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U65", "Parent" : "42"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U66", "Parent" : "42"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U67", "Parent" : "42"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U68", "Parent" : "42"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U69", "Parent" : "42"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U70", "Parent" : "42"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U71", "Parent" : "42"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U72", "Parent" : "42"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U73", "Parent" : "42"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U74", "Parent" : "42"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U75", "Parent" : "42"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U76", "Parent" : "42"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U77", "Parent" : "42"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U78", "Parent" : "42"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U79", "Parent" : "42"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.mul_34s_30s_64_1_1_U80", "Parent" : "42"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.sdiv_50ns_34s_50_54_1_U81", "Parent" : "42"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dual_norm_U0.flow_control_loop_pipe_U", "Parent" : "42"},
	{"ID" : "77", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k4_dual_post_U0", "Parent" : "0", "Child" : ["78"],
		"CDFG" : "k4_dual_post",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2050", "EstimateLatencyMax" : "2050",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "42",
		"StartFifo" : "start_for_k4_dual_post_U0_U",
		"Port" : [
			{"Name" : "sa_norm", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["42"], "DependentChan" : "89", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_norm_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_norm", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["42"], "DependentChan" : "90", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_norm_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_post", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["79"], "DependentChan" : "91", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_post_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_post", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["79"], "DependentChan" : "92", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_post_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_455_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k4_dual_post_U0.flow_control_loop_pipe_U", "Parent" : "77"},
	{"ID" : "79", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.store_dual_U0", "Parent" : "0", "Child" : ["80"],
		"CDFG" : "store_dual",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2057", "EstimateLatencyMax" : "2057",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "4",
		"StartFifo" : "start_for_store_dual_U0_U",
		"Port" : [
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "out_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["4"], "DependentChan" : "81", "DependentChanDepth" : "7", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "out_r_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sa_post", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["77"], "DependentChan" : "91", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sa_post_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "sb_post", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["77"], "DependentChan" : "92", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "sb_post_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "STORE_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.store_dual_U0.flow_control_loop_pipe_U", "Parent" : "79"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_c_U", "Parent" : "0"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sa_in_U", "Parent" : "0"},
	{"ID" : "83", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sb_in_U", "Parent" : "0"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sa_stats_U", "Parent" : "0"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sa_join_U", "Parent" : "0"},
	{"ID" : "86", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sb_stats_U", "Parent" : "0"},
	{"ID" : "87", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sb_join_U", "Parent" : "0"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s_st_U", "Parent" : "0"},
	{"ID" : "89", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sa_norm_U", "Parent" : "0"},
	{"ID" : "90", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sb_norm_U", "Parent" : "0"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sa_post_U", "Parent" : "0"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sb_post_U", "Parent" : "0"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_store_dual_U0_U", "Parent" : "0"},
	{"ID" : "94", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_super_kernel_32_U0_U", "Parent" : "0"},
	{"ID" : "95", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k2_stats_dual_U0_U", "Parent" : "0"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k3_dual_norm_U0_U", "Parent" : "0"},
	{"ID" : "97", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k4_dual_post_U0_U", "Parent" : "0"}]}
