

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.load_input_U0"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.load_input_U0.flow_control_loop_pipe_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k0_preprocess_U0"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k0_preprocess_U0.flow_control_loop_pipe_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k_split_U0"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k_split_U0.flow_control_loop_pipe_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k1_transform_U0"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k1_transform_U0.sparsemux_7_2_20_1_1_U11"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k1_transform_U0.flow_control_loop_pipe_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k2_stats_U0"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_stats_U0.sparsemux_7_2_20_1_1_U15"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_stats_U0.sdiv_50ns_35s_50_54_1_U16"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_stats_U0.flow_control_loop_pipe_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k3_join_norm_U0"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_join_norm_U0.mul_34s_30s_64_1_1_U20"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_join_norm_U0.flow_control_loop_pipe_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k4_postprocess_U0"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k4_postprocess_U0.flow_control_loop_pipe_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.store_output_U0"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.store_output_U0.flow_control_loop_pipe_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_c_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s_in_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s0_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s0_a_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s0_b_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s_stats_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s_out_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_store_output_U0_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k0_preprocess_U0_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k_split_U0_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k1_transform_U0_U"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k2_stats_U0_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k3_join_norm_U0_U"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k4_postprocess_U0_U"}]}
set DependenceCheckSize 0
