// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_k4_postprocess (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s3_dout,
        s3_empty_n,
        s3_read,
        s3_num_data_valid,
        s3_fifo_cap,
        s_out_din,
        s_out_full_n,
        s_out_write,
        s_out_num_data_valid,
        s_out_fifo_cap
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] s3_dout;
input   s3_empty_n;
output   s3_read;
input  [2:0] s3_num_data_valid;
input  [2:0] s3_fifo_cap;
output  [511:0] s_out_din;
input   s_out_full_n;
output   s_out_write;
input  [31:0] s_out_num_data_valid;
input  [31:0] s_out_fifo_cap;

reg ap_idle;
reg s3_read;
reg s_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln248_fu_3681_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s3_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    s_out_blk_n;
wire   [16:0] v_out_fu_367_p3;
reg   [16:0] v_out_reg_3814;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [16:0] v_out_1_fu_587_p3;
reg   [16:0] v_out_1_reg_3819;
wire   [16:0] v_out_2_fu_807_p3;
reg   [16:0] v_out_2_reg_3824;
wire   [16:0] v_out_3_fu_1027_p3;
reg   [16:0] v_out_3_reg_3829;
wire   [16:0] v_out_4_fu_1247_p3;
reg   [16:0] v_out_4_reg_3834;
wire   [16:0] v_out_5_fu_1467_p3;
reg   [16:0] v_out_5_reg_3839;
wire   [16:0] v_out_6_fu_1687_p3;
reg   [16:0] v_out_6_reg_3844;
wire   [16:0] v_out_7_fu_1907_p3;
reg   [16:0] v_out_7_reg_3849;
wire   [16:0] v_out_8_fu_2127_p3;
reg   [16:0] v_out_8_reg_3854;
wire   [16:0] v_out_9_fu_2347_p3;
reg   [16:0] v_out_9_reg_3859;
wire   [16:0] v_out_10_fu_2567_p3;
reg   [16:0] v_out_10_reg_3864;
wire   [16:0] v_out_11_fu_2787_p3;
reg   [16:0] v_out_11_reg_3869;
wire   [16:0] v_out_12_fu_3007_p3;
reg   [16:0] v_out_12_reg_3874;
wire   [16:0] v_out_13_fu_3227_p3;
reg   [16:0] v_out_13_reg_3879;
wire   [16:0] v_out_14_fu_3447_p3;
reg   [16:0] v_out_14_reg_3884;
wire   [16:0] select_ln119_31_fu_3667_p3;
reg   [16:0] select_ln119_31_reg_3889;
reg    ap_block_pp0_stage0_11001;
reg   [11:0] k1_fu_136;
wire   [11:0] k_fu_3675_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_k1_load;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [19:0] trunc_ln254_fu_161_p1;
wire   [53:0] tmp_fu_165_p3;
wire   [51:0] tmp_1_fu_177_p3;
wire  signed [54:0] sext_ln254_fu_173_p1;
wire  signed [54:0] sext_ln254_1_fu_185_p1;
wire   [54:0] add_ln254_1_fu_189_p2;
wire   [54:0] add_ln254_fu_195_p2;
wire   [0:0] tmp_3_fu_219_p3;
wire   [19:0] z_fu_209_p4;
wire   [19:0] zext_ln254_fu_235_p1;
wire   [19:0] z_1_fu_239_p2;
wire   [0:0] tmp_4_fu_227_p3;
wire   [0:0] tmp_5_fu_245_p3;
wire   [0:0] xor_ln254_fu_253_p2;
wire   [0:0] tmp_2_fu_201_p3;
wire   [0:0] or_ln254_32_fu_259_p2;
wire   [0:0] xor_ln254_2_fu_271_p2;
wire   [0:0] xor_ln254_3_fu_277_p2;
wire   [0:0] or_ln254_fu_283_p2;
wire   [0:0] xor_ln254_1_fu_265_p2;
wire   [0:0] or_ln254_33_fu_295_p2;
wire   [0:0] xor_ln254_4_fu_301_p2;
wire   [0:0] and_ln254_fu_289_p2;
wire   [0:0] and_ln254_1_fu_307_p2;
wire   [0:0] or_ln254_1_fu_321_p2;
wire   [19:0] select_ln254_fu_313_p3;
wire   [19:0] z_48_fu_327_p3;
wire   [0:0] tmp_6_fu_339_p3;
wire   [0:0] icmp_ln120_fu_347_p2;
wire   [0:0] or_ln119_fu_361_p2;
wire   [16:0] select_ln119_fu_353_p3;
wire   [16:0] trunc_ln254_1_fu_335_p1;
wire   [19:0] tmp_s_fu_375_p4;
wire   [53:0] tmp_7_fu_385_p3;
wire   [51:0] tmp_8_fu_397_p3;
wire  signed [54:0] sext_ln254_2_fu_393_p1;
wire  signed [54:0] sext_ln254_3_fu_405_p1;
wire   [54:0] add_ln254_5_fu_409_p2;
wire   [54:0] add_ln254_2_fu_415_p2;
wire   [0:0] tmp_10_fu_439_p3;
wire   [19:0] z_3_fu_429_p4;
wire   [19:0] zext_ln254_1_fu_455_p1;
wire   [19:0] z_4_fu_459_p2;
wire   [0:0] tmp_11_fu_447_p3;
wire   [0:0] tmp_12_fu_465_p3;
wire   [0:0] xor_ln254_5_fu_473_p2;
wire   [0:0] tmp_9_fu_421_p3;
wire   [0:0] or_ln254_34_fu_479_p2;
wire   [0:0] xor_ln254_7_fu_491_p2;
wire   [0:0] xor_ln254_8_fu_497_p2;
wire   [0:0] or_ln254_2_fu_503_p2;
wire   [0:0] xor_ln254_6_fu_485_p2;
wire   [0:0] or_ln254_35_fu_515_p2;
wire   [0:0] xor_ln254_9_fu_521_p2;
wire   [0:0] and_ln254_2_fu_509_p2;
wire   [0:0] and_ln254_3_fu_527_p2;
wire   [0:0] or_ln254_3_fu_541_p2;
wire   [19:0] select_ln254_2_fu_533_p3;
wire   [19:0] z_49_fu_547_p3;
wire   [0:0] tmp_13_fu_559_p3;
wire   [0:0] icmp_ln120_1_fu_567_p2;
wire   [0:0] or_ln119_1_fu_581_p2;
wire   [16:0] select_ln119_2_fu_573_p3;
wire   [16:0] trunc_ln254_2_fu_555_p1;
wire   [19:0] tmp_14_fu_595_p4;
wire   [53:0] tmp_15_fu_605_p3;
wire   [51:0] tmp_16_fu_617_p3;
wire  signed [54:0] sext_ln254_4_fu_613_p1;
wire  signed [54:0] sext_ln254_5_fu_625_p1;
wire   [54:0] add_ln254_9_fu_629_p2;
wire   [54:0] add_ln254_4_fu_635_p2;
wire   [0:0] tmp_18_fu_659_p3;
wire   [19:0] z_6_fu_649_p4;
wire   [19:0] zext_ln254_2_fu_675_p1;
wire   [19:0] z_7_fu_679_p2;
wire   [0:0] tmp_19_fu_667_p3;
wire   [0:0] tmp_20_fu_685_p3;
wire   [0:0] xor_ln254_10_fu_693_p2;
wire   [0:0] tmp_17_fu_641_p3;
wire   [0:0] or_ln254_36_fu_699_p2;
wire   [0:0] xor_ln254_12_fu_711_p2;
wire   [0:0] xor_ln254_13_fu_717_p2;
wire   [0:0] or_ln254_4_fu_723_p2;
wire   [0:0] xor_ln254_11_fu_705_p2;
wire   [0:0] or_ln254_37_fu_735_p2;
wire   [0:0] xor_ln254_14_fu_741_p2;
wire   [0:0] and_ln254_4_fu_729_p2;
wire   [0:0] and_ln254_5_fu_747_p2;
wire   [0:0] or_ln254_5_fu_761_p2;
wire   [19:0] select_ln254_4_fu_753_p3;
wire   [19:0] z_50_fu_767_p3;
wire   [0:0] tmp_21_fu_779_p3;
wire   [0:0] icmp_ln120_2_fu_787_p2;
wire   [0:0] or_ln119_2_fu_801_p2;
wire   [16:0] select_ln119_4_fu_793_p3;
wire   [16:0] trunc_ln254_3_fu_775_p1;
wire   [19:0] tmp_22_fu_815_p4;
wire   [53:0] tmp_23_fu_825_p3;
wire   [51:0] tmp_24_fu_837_p3;
wire  signed [54:0] sext_ln254_6_fu_833_p1;
wire  signed [54:0] sext_ln254_7_fu_845_p1;
wire   [54:0] add_ln254_13_fu_849_p2;
wire   [54:0] add_ln254_6_fu_855_p2;
wire   [0:0] tmp_26_fu_879_p3;
wire   [19:0] z_9_fu_869_p4;
wire   [19:0] zext_ln254_3_fu_895_p1;
wire   [19:0] z_10_fu_899_p2;
wire   [0:0] tmp_27_fu_887_p3;
wire   [0:0] tmp_28_fu_905_p3;
wire   [0:0] xor_ln254_15_fu_913_p2;
wire   [0:0] tmp_25_fu_861_p3;
wire   [0:0] or_ln254_38_fu_919_p2;
wire   [0:0] xor_ln254_17_fu_931_p2;
wire   [0:0] xor_ln254_18_fu_937_p2;
wire   [0:0] or_ln254_6_fu_943_p2;
wire   [0:0] xor_ln254_16_fu_925_p2;
wire   [0:0] or_ln254_39_fu_955_p2;
wire   [0:0] xor_ln254_19_fu_961_p2;
wire   [0:0] and_ln254_6_fu_949_p2;
wire   [0:0] and_ln254_7_fu_967_p2;
wire   [0:0] or_ln254_7_fu_981_p2;
wire   [19:0] select_ln254_6_fu_973_p3;
wire   [19:0] z_51_fu_987_p3;
wire   [0:0] tmp_29_fu_999_p3;
wire   [0:0] icmp_ln120_3_fu_1007_p2;
wire   [0:0] or_ln119_3_fu_1021_p2;
wire   [16:0] select_ln119_6_fu_1013_p3;
wire   [16:0] trunc_ln254_4_fu_995_p1;
wire   [19:0] tmp_30_fu_1035_p4;
wire   [53:0] tmp_31_fu_1045_p3;
wire   [51:0] tmp_32_fu_1057_p3;
wire  signed [54:0] sext_ln254_8_fu_1053_p1;
wire  signed [54:0] sext_ln254_9_fu_1065_p1;
wire   [54:0] add_ln254_17_fu_1069_p2;
wire   [54:0] add_ln254_8_fu_1075_p2;
wire   [0:0] tmp_34_fu_1099_p3;
wire   [19:0] z_12_fu_1089_p4;
wire   [19:0] zext_ln254_4_fu_1115_p1;
wire   [19:0] z_13_fu_1119_p2;
wire   [0:0] tmp_35_fu_1107_p3;
wire   [0:0] tmp_36_fu_1125_p3;
wire   [0:0] xor_ln254_20_fu_1133_p2;
wire   [0:0] tmp_33_fu_1081_p3;
wire   [0:0] or_ln254_40_fu_1139_p2;
wire   [0:0] xor_ln254_22_fu_1151_p2;
wire   [0:0] xor_ln254_23_fu_1157_p2;
wire   [0:0] or_ln254_8_fu_1163_p2;
wire   [0:0] xor_ln254_21_fu_1145_p2;
wire   [0:0] or_ln254_41_fu_1175_p2;
wire   [0:0] xor_ln254_24_fu_1181_p2;
wire   [0:0] and_ln254_8_fu_1169_p2;
wire   [0:0] and_ln254_9_fu_1187_p2;
wire   [0:0] or_ln254_9_fu_1201_p2;
wire   [19:0] select_ln254_8_fu_1193_p3;
wire   [19:0] z_52_fu_1207_p3;
wire   [0:0] tmp_37_fu_1219_p3;
wire   [0:0] icmp_ln120_4_fu_1227_p2;
wire   [0:0] or_ln119_4_fu_1241_p2;
wire   [16:0] select_ln119_8_fu_1233_p3;
wire   [16:0] trunc_ln254_5_fu_1215_p1;
wire   [19:0] tmp_38_fu_1255_p4;
wire   [53:0] tmp_39_fu_1265_p3;
wire   [51:0] tmp_40_fu_1277_p3;
wire  signed [54:0] sext_ln254_10_fu_1273_p1;
wire  signed [54:0] sext_ln254_11_fu_1285_p1;
wire   [54:0] add_ln254_21_fu_1289_p2;
wire   [54:0] add_ln254_10_fu_1295_p2;
wire   [0:0] tmp_42_fu_1319_p3;
wire   [19:0] z_15_fu_1309_p4;
wire   [19:0] zext_ln254_5_fu_1335_p1;
wire   [19:0] z_16_fu_1339_p2;
wire   [0:0] tmp_43_fu_1327_p3;
wire   [0:0] tmp_44_fu_1345_p3;
wire   [0:0] xor_ln254_25_fu_1353_p2;
wire   [0:0] tmp_41_fu_1301_p3;
wire   [0:0] or_ln254_42_fu_1359_p2;
wire   [0:0] xor_ln254_27_fu_1371_p2;
wire   [0:0] xor_ln254_28_fu_1377_p2;
wire   [0:0] or_ln254_10_fu_1383_p2;
wire   [0:0] xor_ln254_26_fu_1365_p2;
wire   [0:0] or_ln254_43_fu_1395_p2;
wire   [0:0] xor_ln254_29_fu_1401_p2;
wire   [0:0] and_ln254_10_fu_1389_p2;
wire   [0:0] and_ln254_11_fu_1407_p2;
wire   [0:0] or_ln254_11_fu_1421_p2;
wire   [19:0] select_ln254_10_fu_1413_p3;
wire   [19:0] z_53_fu_1427_p3;
wire   [0:0] tmp_45_fu_1439_p3;
wire   [0:0] icmp_ln120_5_fu_1447_p2;
wire   [0:0] or_ln119_5_fu_1461_p2;
wire   [16:0] select_ln119_10_fu_1453_p3;
wire   [16:0] trunc_ln254_6_fu_1435_p1;
wire   [19:0] tmp_46_fu_1475_p4;
wire   [53:0] tmp_47_fu_1485_p3;
wire   [51:0] tmp_48_fu_1497_p3;
wire  signed [54:0] sext_ln254_12_fu_1493_p1;
wire  signed [54:0] sext_ln254_13_fu_1505_p1;
wire   [54:0] add_ln254_25_fu_1509_p2;
wire   [54:0] add_ln254_12_fu_1515_p2;
wire   [0:0] tmp_50_fu_1539_p3;
wire   [19:0] z_18_fu_1529_p4;
wire   [19:0] zext_ln254_6_fu_1555_p1;
wire   [19:0] z_19_fu_1559_p2;
wire   [0:0] tmp_51_fu_1547_p3;
wire   [0:0] tmp_52_fu_1565_p3;
wire   [0:0] xor_ln254_30_fu_1573_p2;
wire   [0:0] tmp_49_fu_1521_p3;
wire   [0:0] or_ln254_44_fu_1579_p2;
wire   [0:0] xor_ln254_32_fu_1591_p2;
wire   [0:0] xor_ln254_33_fu_1597_p2;
wire   [0:0] or_ln254_12_fu_1603_p2;
wire   [0:0] xor_ln254_31_fu_1585_p2;
wire   [0:0] or_ln254_45_fu_1615_p2;
wire   [0:0] xor_ln254_34_fu_1621_p2;
wire   [0:0] and_ln254_12_fu_1609_p2;
wire   [0:0] and_ln254_13_fu_1627_p2;
wire   [0:0] or_ln254_13_fu_1641_p2;
wire   [19:0] select_ln254_12_fu_1633_p3;
wire   [19:0] z_54_fu_1647_p3;
wire   [0:0] tmp_53_fu_1659_p3;
wire   [0:0] icmp_ln120_6_fu_1667_p2;
wire   [0:0] or_ln119_6_fu_1681_p2;
wire   [16:0] select_ln119_12_fu_1673_p3;
wire   [16:0] trunc_ln254_7_fu_1655_p1;
wire   [19:0] tmp_54_fu_1695_p4;
wire   [53:0] tmp_55_fu_1705_p3;
wire   [51:0] tmp_56_fu_1717_p3;
wire  signed [54:0] sext_ln254_14_fu_1713_p1;
wire  signed [54:0] sext_ln254_15_fu_1725_p1;
wire   [54:0] add_ln254_29_fu_1729_p2;
wire   [54:0] add_ln254_14_fu_1735_p2;
wire   [0:0] tmp_58_fu_1759_p3;
wire   [19:0] z_21_fu_1749_p4;
wire   [19:0] zext_ln254_7_fu_1775_p1;
wire   [19:0] z_22_fu_1779_p2;
wire   [0:0] tmp_59_fu_1767_p3;
wire   [0:0] tmp_60_fu_1785_p3;
wire   [0:0] xor_ln254_35_fu_1793_p2;
wire   [0:0] tmp_57_fu_1741_p3;
wire   [0:0] or_ln254_46_fu_1799_p2;
wire   [0:0] xor_ln254_37_fu_1811_p2;
wire   [0:0] xor_ln254_38_fu_1817_p2;
wire   [0:0] or_ln254_14_fu_1823_p2;
wire   [0:0] xor_ln254_36_fu_1805_p2;
wire   [0:0] or_ln254_47_fu_1835_p2;
wire   [0:0] xor_ln254_39_fu_1841_p2;
wire   [0:0] and_ln254_14_fu_1829_p2;
wire   [0:0] and_ln254_15_fu_1847_p2;
wire   [0:0] or_ln254_15_fu_1861_p2;
wire   [19:0] select_ln254_14_fu_1853_p3;
wire   [19:0] z_55_fu_1867_p3;
wire   [0:0] tmp_61_fu_1879_p3;
wire   [0:0] icmp_ln120_7_fu_1887_p2;
wire   [0:0] or_ln119_7_fu_1901_p2;
wire   [16:0] select_ln119_14_fu_1893_p3;
wire   [16:0] trunc_ln254_8_fu_1875_p1;
wire   [19:0] tmp_62_fu_1915_p4;
wire   [53:0] tmp_63_fu_1925_p3;
wire   [51:0] tmp_64_fu_1937_p3;
wire  signed [54:0] sext_ln254_16_fu_1933_p1;
wire  signed [54:0] sext_ln254_17_fu_1945_p1;
wire   [54:0] add_ln254_32_fu_1949_p2;
wire   [54:0] add_ln254_16_fu_1955_p2;
wire   [0:0] tmp_66_fu_1979_p3;
wire   [19:0] z_24_fu_1969_p4;
wire   [19:0] zext_ln254_8_fu_1995_p1;
wire   [19:0] z_25_fu_1999_p2;
wire   [0:0] tmp_67_fu_1987_p3;
wire   [0:0] tmp_68_fu_2005_p3;
wire   [0:0] xor_ln254_40_fu_2013_p2;
wire   [0:0] tmp_65_fu_1961_p3;
wire   [0:0] or_ln254_48_fu_2019_p2;
wire   [0:0] xor_ln254_42_fu_2031_p2;
wire   [0:0] xor_ln254_43_fu_2037_p2;
wire   [0:0] or_ln254_16_fu_2043_p2;
wire   [0:0] xor_ln254_41_fu_2025_p2;
wire   [0:0] or_ln254_49_fu_2055_p2;
wire   [0:0] xor_ln254_44_fu_2061_p2;
wire   [0:0] and_ln254_16_fu_2049_p2;
wire   [0:0] and_ln254_17_fu_2067_p2;
wire   [0:0] or_ln254_17_fu_2081_p2;
wire   [19:0] select_ln254_16_fu_2073_p3;
wire   [19:0] z_56_fu_2087_p3;
wire   [0:0] tmp_69_fu_2099_p3;
wire   [0:0] icmp_ln120_8_fu_2107_p2;
wire   [0:0] or_ln119_8_fu_2121_p2;
wire   [16:0] select_ln119_16_fu_2113_p3;
wire   [16:0] trunc_ln254_9_fu_2095_p1;
wire   [19:0] tmp_70_fu_2135_p4;
wire   [53:0] tmp_71_fu_2145_p3;
wire   [51:0] tmp_72_fu_2157_p3;
wire  signed [54:0] sext_ln254_18_fu_2153_p1;
wire  signed [54:0] sext_ln254_19_fu_2165_p1;
wire   [54:0] add_ln254_34_fu_2169_p2;
wire   [54:0] add_ln254_18_fu_2175_p2;
wire   [0:0] tmp_74_fu_2199_p3;
wire   [19:0] z_27_fu_2189_p4;
wire   [19:0] zext_ln254_9_fu_2215_p1;
wire   [19:0] z_28_fu_2219_p2;
wire   [0:0] tmp_75_fu_2207_p3;
wire   [0:0] tmp_76_fu_2225_p3;
wire   [0:0] xor_ln254_45_fu_2233_p2;
wire   [0:0] tmp_73_fu_2181_p3;
wire   [0:0] or_ln254_50_fu_2239_p2;
wire   [0:0] xor_ln254_47_fu_2251_p2;
wire   [0:0] xor_ln254_48_fu_2257_p2;
wire   [0:0] or_ln254_18_fu_2263_p2;
wire   [0:0] xor_ln254_46_fu_2245_p2;
wire   [0:0] or_ln254_51_fu_2275_p2;
wire   [0:0] xor_ln254_49_fu_2281_p2;
wire   [0:0] and_ln254_18_fu_2269_p2;
wire   [0:0] and_ln254_19_fu_2287_p2;
wire   [0:0] or_ln254_19_fu_2301_p2;
wire   [19:0] select_ln254_18_fu_2293_p3;
wire   [19:0] z_57_fu_2307_p3;
wire   [0:0] tmp_77_fu_2319_p3;
wire   [0:0] icmp_ln120_9_fu_2327_p2;
wire   [0:0] or_ln119_9_fu_2341_p2;
wire   [16:0] select_ln119_18_fu_2333_p3;
wire   [16:0] trunc_ln254_10_fu_2315_p1;
wire   [19:0] tmp_78_fu_2355_p4;
wire   [53:0] tmp_79_fu_2365_p3;
wire   [51:0] tmp_80_fu_2377_p3;
wire  signed [54:0] sext_ln254_20_fu_2373_p1;
wire  signed [54:0] sext_ln254_21_fu_2385_p1;
wire   [54:0] add_ln254_36_fu_2389_p2;
wire   [54:0] add_ln254_20_fu_2395_p2;
wire   [0:0] tmp_82_fu_2419_p3;
wire   [19:0] z_30_fu_2409_p4;
wire   [19:0] zext_ln254_10_fu_2435_p1;
wire   [19:0] z_31_fu_2439_p2;
wire   [0:0] tmp_83_fu_2427_p3;
wire   [0:0] tmp_84_fu_2445_p3;
wire   [0:0] xor_ln254_50_fu_2453_p2;
wire   [0:0] tmp_81_fu_2401_p3;
wire   [0:0] or_ln254_52_fu_2459_p2;
wire   [0:0] xor_ln254_52_fu_2471_p2;
wire   [0:0] xor_ln254_53_fu_2477_p2;
wire   [0:0] or_ln254_20_fu_2483_p2;
wire   [0:0] xor_ln254_51_fu_2465_p2;
wire   [0:0] or_ln254_53_fu_2495_p2;
wire   [0:0] xor_ln254_54_fu_2501_p2;
wire   [0:0] and_ln254_20_fu_2489_p2;
wire   [0:0] and_ln254_21_fu_2507_p2;
wire   [0:0] or_ln254_21_fu_2521_p2;
wire   [19:0] select_ln254_20_fu_2513_p3;
wire   [19:0] z_58_fu_2527_p3;
wire   [0:0] tmp_85_fu_2539_p3;
wire   [0:0] icmp_ln120_10_fu_2547_p2;
wire   [0:0] or_ln119_10_fu_2561_p2;
wire   [16:0] select_ln119_20_fu_2553_p3;
wire   [16:0] trunc_ln254_11_fu_2535_p1;
wire   [19:0] tmp_86_fu_2575_p4;
wire   [53:0] tmp_87_fu_2585_p3;
wire   [51:0] tmp_88_fu_2597_p3;
wire  signed [54:0] sext_ln254_22_fu_2593_p1;
wire  signed [54:0] sext_ln254_23_fu_2605_p1;
wire   [54:0] add_ln254_38_fu_2609_p2;
wire   [54:0] add_ln254_22_fu_2615_p2;
wire   [0:0] tmp_90_fu_2639_p3;
wire   [19:0] z_33_fu_2629_p4;
wire   [19:0] zext_ln254_11_fu_2655_p1;
wire   [19:0] z_34_fu_2659_p2;
wire   [0:0] tmp_91_fu_2647_p3;
wire   [0:0] tmp_92_fu_2665_p3;
wire   [0:0] xor_ln254_55_fu_2673_p2;
wire   [0:0] tmp_89_fu_2621_p3;
wire   [0:0] or_ln254_54_fu_2679_p2;
wire   [0:0] xor_ln254_57_fu_2691_p2;
wire   [0:0] xor_ln254_58_fu_2697_p2;
wire   [0:0] or_ln254_22_fu_2703_p2;
wire   [0:0] xor_ln254_56_fu_2685_p2;
wire   [0:0] or_ln254_55_fu_2715_p2;
wire   [0:0] xor_ln254_59_fu_2721_p2;
wire   [0:0] and_ln254_22_fu_2709_p2;
wire   [0:0] and_ln254_23_fu_2727_p2;
wire   [0:0] or_ln254_23_fu_2741_p2;
wire   [19:0] select_ln254_22_fu_2733_p3;
wire   [19:0] z_59_fu_2747_p3;
wire   [0:0] tmp_93_fu_2759_p3;
wire   [0:0] icmp_ln120_11_fu_2767_p2;
wire   [0:0] or_ln119_11_fu_2781_p2;
wire   [16:0] select_ln119_22_fu_2773_p3;
wire   [16:0] trunc_ln254_12_fu_2755_p1;
wire   [19:0] tmp_94_fu_2795_p4;
wire   [53:0] tmp_95_fu_2805_p3;
wire   [51:0] tmp_96_fu_2817_p3;
wire  signed [54:0] sext_ln254_24_fu_2813_p1;
wire  signed [54:0] sext_ln254_25_fu_2825_p1;
wire   [54:0] add_ln254_40_fu_2829_p2;
wire   [54:0] add_ln254_24_fu_2835_p2;
wire   [0:0] tmp_98_fu_2859_p3;
wire   [19:0] z_36_fu_2849_p4;
wire   [19:0] zext_ln254_12_fu_2875_p1;
wire   [19:0] z_37_fu_2879_p2;
wire   [0:0] tmp_99_fu_2867_p3;
wire   [0:0] tmp_100_fu_2885_p3;
wire   [0:0] xor_ln254_60_fu_2893_p2;
wire   [0:0] tmp_97_fu_2841_p3;
wire   [0:0] or_ln254_56_fu_2899_p2;
wire   [0:0] xor_ln254_62_fu_2911_p2;
wire   [0:0] xor_ln254_63_fu_2917_p2;
wire   [0:0] or_ln254_24_fu_2923_p2;
wire   [0:0] xor_ln254_61_fu_2905_p2;
wire   [0:0] or_ln254_57_fu_2935_p2;
wire   [0:0] xor_ln254_64_fu_2941_p2;
wire   [0:0] and_ln254_24_fu_2929_p2;
wire   [0:0] and_ln254_25_fu_2947_p2;
wire   [0:0] or_ln254_25_fu_2961_p2;
wire   [19:0] select_ln254_24_fu_2953_p3;
wire   [19:0] z_60_fu_2967_p3;
wire   [0:0] tmp_101_fu_2979_p3;
wire   [0:0] icmp_ln120_12_fu_2987_p2;
wire   [0:0] or_ln119_12_fu_3001_p2;
wire   [16:0] select_ln119_24_fu_2993_p3;
wire   [16:0] trunc_ln254_13_fu_2975_p1;
wire   [19:0] tmp_102_fu_3015_p4;
wire   [53:0] tmp_103_fu_3025_p3;
wire   [51:0] tmp_104_fu_3037_p3;
wire  signed [54:0] sext_ln254_26_fu_3033_p1;
wire  signed [54:0] sext_ln254_27_fu_3045_p1;
wire   [54:0] add_ln254_42_fu_3049_p2;
wire   [54:0] add_ln254_26_fu_3055_p2;
wire   [0:0] tmp_106_fu_3079_p3;
wire   [19:0] z_39_fu_3069_p4;
wire   [19:0] zext_ln254_13_fu_3095_p1;
wire   [19:0] z_40_fu_3099_p2;
wire   [0:0] tmp_107_fu_3087_p3;
wire   [0:0] tmp_108_fu_3105_p3;
wire   [0:0] xor_ln254_65_fu_3113_p2;
wire   [0:0] tmp_105_fu_3061_p3;
wire   [0:0] or_ln254_58_fu_3119_p2;
wire   [0:0] xor_ln254_67_fu_3131_p2;
wire   [0:0] xor_ln254_68_fu_3137_p2;
wire   [0:0] or_ln254_26_fu_3143_p2;
wire   [0:0] xor_ln254_66_fu_3125_p2;
wire   [0:0] or_ln254_59_fu_3155_p2;
wire   [0:0] xor_ln254_69_fu_3161_p2;
wire   [0:0] and_ln254_26_fu_3149_p2;
wire   [0:0] and_ln254_27_fu_3167_p2;
wire   [0:0] or_ln254_27_fu_3181_p2;
wire   [19:0] select_ln254_26_fu_3173_p3;
wire   [19:0] z_61_fu_3187_p3;
wire   [0:0] tmp_109_fu_3199_p3;
wire   [0:0] icmp_ln120_13_fu_3207_p2;
wire   [0:0] or_ln119_13_fu_3221_p2;
wire   [16:0] select_ln119_26_fu_3213_p3;
wire   [16:0] trunc_ln254_14_fu_3195_p1;
wire   [19:0] tmp_110_fu_3235_p4;
wire   [53:0] tmp_111_fu_3245_p3;
wire   [51:0] tmp_112_fu_3257_p3;
wire  signed [54:0] sext_ln254_28_fu_3253_p1;
wire  signed [54:0] sext_ln254_29_fu_3265_p1;
wire   [54:0] add_ln254_44_fu_3269_p2;
wire   [54:0] add_ln254_28_fu_3275_p2;
wire   [0:0] tmp_114_fu_3299_p3;
wire   [19:0] z_42_fu_3289_p4;
wire   [19:0] zext_ln254_14_fu_3315_p1;
wire   [19:0] z_43_fu_3319_p2;
wire   [0:0] tmp_115_fu_3307_p3;
wire   [0:0] tmp_116_fu_3325_p3;
wire   [0:0] xor_ln254_70_fu_3333_p2;
wire   [0:0] tmp_113_fu_3281_p3;
wire   [0:0] or_ln254_60_fu_3339_p2;
wire   [0:0] xor_ln254_72_fu_3351_p2;
wire   [0:0] xor_ln254_73_fu_3357_p2;
wire   [0:0] or_ln254_28_fu_3363_p2;
wire   [0:0] xor_ln254_71_fu_3345_p2;
wire   [0:0] or_ln254_61_fu_3375_p2;
wire   [0:0] xor_ln254_74_fu_3381_p2;
wire   [0:0] and_ln254_28_fu_3369_p2;
wire   [0:0] and_ln254_29_fu_3387_p2;
wire   [0:0] or_ln254_29_fu_3401_p2;
wire   [19:0] select_ln254_28_fu_3393_p3;
wire   [19:0] z_62_fu_3407_p3;
wire   [0:0] tmp_117_fu_3419_p3;
wire   [0:0] icmp_ln120_14_fu_3427_p2;
wire   [0:0] or_ln119_14_fu_3441_p2;
wire   [16:0] select_ln119_28_fu_3433_p3;
wire   [16:0] trunc_ln254_15_fu_3415_p1;
wire   [19:0] tmp_118_fu_3455_p4;
wire   [53:0] tmp_119_fu_3465_p3;
wire   [51:0] tmp_120_fu_3477_p3;
wire  signed [54:0] sext_ln254_30_fu_3473_p1;
wire  signed [54:0] sext_ln254_31_fu_3485_p1;
wire   [54:0] add_ln254_46_fu_3489_p2;
wire   [54:0] add_ln254_30_fu_3495_p2;
wire   [0:0] tmp_122_fu_3519_p3;
wire   [19:0] z_45_fu_3509_p4;
wire   [19:0] zext_ln254_15_fu_3535_p1;
wire   [19:0] z_46_fu_3539_p2;
wire   [0:0] tmp_123_fu_3527_p3;
wire   [0:0] tmp_124_fu_3545_p3;
wire   [0:0] xor_ln254_75_fu_3553_p2;
wire   [0:0] tmp_121_fu_3501_p3;
wire   [0:0] or_ln254_62_fu_3559_p2;
wire   [0:0] xor_ln254_77_fu_3571_p2;
wire   [0:0] xor_ln254_78_fu_3577_p2;
wire   [0:0] or_ln254_30_fu_3583_p2;
wire   [0:0] xor_ln254_76_fu_3565_p2;
wire   [0:0] or_ln254_63_fu_3595_p2;
wire   [0:0] xor_ln254_79_fu_3601_p2;
wire   [0:0] and_ln254_30_fu_3589_p2;
wire   [0:0] and_ln254_31_fu_3607_p2;
wire   [0:0] or_ln254_31_fu_3621_p2;
wire   [19:0] select_ln254_30_fu_3613_p3;
wire   [19:0] z_63_fu_3627_p3;
wire   [0:0] tmp_125_fu_3639_p3;
wire   [0:0] icmp_ln120_15_fu_3647_p2;
wire   [0:0] or_ln119_15_fu_3661_p2;
wire   [16:0] select_ln119_30_fu_3653_p3;
wire   [16:0] trunc_ln254_16_fu_3635_p1;
wire   [19:0] zext_ln251_14_fu_3734_p1;
wire   [19:0] zext_ln251_13_fu_3731_p1;
wire   [19:0] zext_ln251_12_fu_3728_p1;
wire   [19:0] zext_ln251_11_fu_3725_p1;
wire   [19:0] zext_ln251_10_fu_3722_p1;
wire   [19:0] zext_ln251_9_fu_3719_p1;
wire   [19:0] zext_ln251_8_fu_3716_p1;
wire   [19:0] zext_ln251_7_fu_3713_p1;
wire   [19:0] zext_ln251_6_fu_3710_p1;
wire   [19:0] zext_ln251_5_fu_3707_p1;
wire   [19:0] zext_ln251_4_fu_3704_p1;
wire   [19:0] zext_ln251_3_fu_3701_p1;
wire   [19:0] zext_ln251_2_fu_3698_p1;
wire   [19:0] zext_ln251_1_fu_3695_p1;
wire   [19:0] zext_ln251_fu_3692_p1;
wire   [496:0] tmp_124_i_fu_3737_p32;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_131;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 k1_fu_136 = 12'd0;
end

top_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_131)) begin
        k1_fu_136 <= k_fu_3675_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln119_31_reg_3889 <= select_ln119_31_fu_3667_p3;
        v_out_10_reg_3864 <= v_out_10_fu_2567_p3;
        v_out_11_reg_3869 <= v_out_11_fu_2787_p3;
        v_out_12_reg_3874 <= v_out_12_fu_3007_p3;
        v_out_13_reg_3879 <= v_out_13_fu_3227_p3;
        v_out_14_reg_3884 <= v_out_14_fu_3447_p3;
        v_out_1_reg_3819 <= v_out_1_fu_587_p3;
        v_out_2_reg_3824 <= v_out_2_fu_807_p3;
        v_out_3_reg_3829 <= v_out_3_fu_1027_p3;
        v_out_4_reg_3834 <= v_out_4_fu_1247_p3;
        v_out_5_reg_3839 <= v_out_5_fu_1467_p3;
        v_out_6_reg_3844 <= v_out_6_fu_1687_p3;
        v_out_7_reg_3849 <= v_out_7_fu_1907_p3;
        v_out_8_reg_3854 <= v_out_8_fu_2127_p3;
        v_out_9_reg_3859 <= v_out_9_fu_2347_p3;
        v_out_reg_3814 <= v_out_fu_367_p3;
    end
end

always @ (*) begin
    if (((icmp_ln248_fu_3681_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k1_load = 12'd0;
    end else begin
        ap_sig_allocacmp_k1_load = k1_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s3_blk_n = s3_empty_n;
    end else begin
        s3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s3_read = 1'b1;
    end else begin
        s3_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_out_blk_n = s_out_full_n;
    end else begin
        s_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_out_write = 1'b1;
    end else begin
        s_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln254_10_fu_1295_p2 = (add_ln254_21_fu_1289_p2 + 55'd14073752190976);

assign add_ln254_12_fu_1515_p2 = (add_ln254_25_fu_1509_p2 + 55'd14073752190976);

assign add_ln254_13_fu_849_p2 = ($signed(sext_ln254_6_fu_833_p1) + $signed(sext_ln254_7_fu_845_p1));

assign add_ln254_14_fu_1735_p2 = (add_ln254_29_fu_1729_p2 + 55'd14073752190976);

assign add_ln254_16_fu_1955_p2 = (add_ln254_32_fu_1949_p2 + 55'd14073752190976);

assign add_ln254_17_fu_1069_p2 = ($signed(sext_ln254_8_fu_1053_p1) + $signed(sext_ln254_9_fu_1065_p1));

assign add_ln254_18_fu_2175_p2 = (add_ln254_34_fu_2169_p2 + 55'd14073752190976);

assign add_ln254_1_fu_189_p2 = ($signed(sext_ln254_fu_173_p1) + $signed(sext_ln254_1_fu_185_p1));

assign add_ln254_20_fu_2395_p2 = (add_ln254_36_fu_2389_p2 + 55'd14073752190976);

assign add_ln254_21_fu_1289_p2 = ($signed(sext_ln254_10_fu_1273_p1) + $signed(sext_ln254_11_fu_1285_p1));

assign add_ln254_22_fu_2615_p2 = (add_ln254_38_fu_2609_p2 + 55'd14073752190976);

assign add_ln254_24_fu_2835_p2 = (add_ln254_40_fu_2829_p2 + 55'd14073752190976);

assign add_ln254_25_fu_1509_p2 = ($signed(sext_ln254_12_fu_1493_p1) + $signed(sext_ln254_13_fu_1505_p1));

assign add_ln254_26_fu_3055_p2 = (add_ln254_42_fu_3049_p2 + 55'd14073752190976);

assign add_ln254_28_fu_3275_p2 = (add_ln254_44_fu_3269_p2 + 55'd14073752190976);

assign add_ln254_29_fu_1729_p2 = ($signed(sext_ln254_14_fu_1713_p1) + $signed(sext_ln254_15_fu_1725_p1));

assign add_ln254_2_fu_415_p2 = (add_ln254_5_fu_409_p2 + 55'd14073752190976);

assign add_ln254_30_fu_3495_p2 = (add_ln254_46_fu_3489_p2 + 55'd14073752190976);

assign add_ln254_32_fu_1949_p2 = ($signed(sext_ln254_16_fu_1933_p1) + $signed(sext_ln254_17_fu_1945_p1));

assign add_ln254_34_fu_2169_p2 = ($signed(sext_ln254_18_fu_2153_p1) + $signed(sext_ln254_19_fu_2165_p1));

assign add_ln254_36_fu_2389_p2 = ($signed(sext_ln254_20_fu_2373_p1) + $signed(sext_ln254_21_fu_2385_p1));

assign add_ln254_38_fu_2609_p2 = ($signed(sext_ln254_22_fu_2593_p1) + $signed(sext_ln254_23_fu_2605_p1));

assign add_ln254_40_fu_2829_p2 = ($signed(sext_ln254_24_fu_2813_p1) + $signed(sext_ln254_25_fu_2825_p1));

assign add_ln254_42_fu_3049_p2 = ($signed(sext_ln254_26_fu_3033_p1) + $signed(sext_ln254_27_fu_3045_p1));

assign add_ln254_44_fu_3269_p2 = ($signed(sext_ln254_28_fu_3253_p1) + $signed(sext_ln254_29_fu_3265_p1));

assign add_ln254_46_fu_3489_p2 = ($signed(sext_ln254_30_fu_3473_p1) + $signed(sext_ln254_31_fu_3485_p1));

assign add_ln254_4_fu_635_p2 = (add_ln254_9_fu_629_p2 + 55'd14073752190976);

assign add_ln254_5_fu_409_p2 = ($signed(sext_ln254_2_fu_393_p1) + $signed(sext_ln254_3_fu_405_p1));

assign add_ln254_6_fu_855_p2 = (add_ln254_13_fu_849_p2 + 55'd14073752190976);

assign add_ln254_8_fu_1075_p2 = (add_ln254_17_fu_1069_p2 + 55'd14073752190976);

assign add_ln254_9_fu_629_p2 = ($signed(sext_ln254_4_fu_613_p1) + $signed(sext_ln254_5_fu_625_p1));

assign add_ln254_fu_195_p2 = (add_ln254_1_fu_189_p2 + 55'd14073752190976);

assign and_ln254_10_fu_1389_p2 = (xor_ln254_26_fu_1365_p2 & or_ln254_10_fu_1383_p2);

assign and_ln254_11_fu_1407_p2 = (xor_ln254_29_fu_1401_p2 & tmp_41_fu_1301_p3);

assign and_ln254_12_fu_1609_p2 = (xor_ln254_31_fu_1585_p2 & or_ln254_12_fu_1603_p2);

assign and_ln254_13_fu_1627_p2 = (xor_ln254_34_fu_1621_p2 & tmp_49_fu_1521_p3);

assign and_ln254_14_fu_1829_p2 = (xor_ln254_36_fu_1805_p2 & or_ln254_14_fu_1823_p2);

assign and_ln254_15_fu_1847_p2 = (xor_ln254_39_fu_1841_p2 & tmp_57_fu_1741_p3);

assign and_ln254_16_fu_2049_p2 = (xor_ln254_41_fu_2025_p2 & or_ln254_16_fu_2043_p2);

assign and_ln254_17_fu_2067_p2 = (xor_ln254_44_fu_2061_p2 & tmp_65_fu_1961_p3);

assign and_ln254_18_fu_2269_p2 = (xor_ln254_46_fu_2245_p2 & or_ln254_18_fu_2263_p2);

assign and_ln254_19_fu_2287_p2 = (xor_ln254_49_fu_2281_p2 & tmp_73_fu_2181_p3);

assign and_ln254_1_fu_307_p2 = (xor_ln254_4_fu_301_p2 & tmp_2_fu_201_p3);

assign and_ln254_20_fu_2489_p2 = (xor_ln254_51_fu_2465_p2 & or_ln254_20_fu_2483_p2);

assign and_ln254_21_fu_2507_p2 = (xor_ln254_54_fu_2501_p2 & tmp_81_fu_2401_p3);

assign and_ln254_22_fu_2709_p2 = (xor_ln254_56_fu_2685_p2 & or_ln254_22_fu_2703_p2);

assign and_ln254_23_fu_2727_p2 = (xor_ln254_59_fu_2721_p2 & tmp_89_fu_2621_p3);

assign and_ln254_24_fu_2929_p2 = (xor_ln254_61_fu_2905_p2 & or_ln254_24_fu_2923_p2);

assign and_ln254_25_fu_2947_p2 = (xor_ln254_64_fu_2941_p2 & tmp_97_fu_2841_p3);

assign and_ln254_26_fu_3149_p2 = (xor_ln254_66_fu_3125_p2 & or_ln254_26_fu_3143_p2);

assign and_ln254_27_fu_3167_p2 = (xor_ln254_69_fu_3161_p2 & tmp_105_fu_3061_p3);

assign and_ln254_28_fu_3369_p2 = (xor_ln254_71_fu_3345_p2 & or_ln254_28_fu_3363_p2);

assign and_ln254_29_fu_3387_p2 = (xor_ln254_74_fu_3381_p2 & tmp_113_fu_3281_p3);

assign and_ln254_2_fu_509_p2 = (xor_ln254_6_fu_485_p2 & or_ln254_2_fu_503_p2);

assign and_ln254_30_fu_3589_p2 = (xor_ln254_76_fu_3565_p2 & or_ln254_30_fu_3583_p2);

assign and_ln254_31_fu_3607_p2 = (xor_ln254_79_fu_3601_p2 & tmp_121_fu_3501_p3);

assign and_ln254_3_fu_527_p2 = (xor_ln254_9_fu_521_p2 & tmp_9_fu_421_p3);

assign and_ln254_4_fu_729_p2 = (xor_ln254_11_fu_705_p2 & or_ln254_4_fu_723_p2);

assign and_ln254_5_fu_747_p2 = (xor_ln254_14_fu_741_p2 & tmp_17_fu_641_p3);

assign and_ln254_6_fu_949_p2 = (xor_ln254_16_fu_925_p2 & or_ln254_6_fu_943_p2);

assign and_ln254_7_fu_967_p2 = (xor_ln254_19_fu_961_p2 & tmp_25_fu_861_p3);

assign and_ln254_8_fu_1169_p2 = (xor_ln254_21_fu_1145_p2 & or_ln254_8_fu_1163_p2);

assign and_ln254_9_fu_1187_p2 = (xor_ln254_24_fu_1181_p2 & tmp_33_fu_1081_p3);

assign and_ln254_fu_289_p2 = (xor_ln254_1_fu_265_p2 & or_ln254_fu_283_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((s_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((s_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((s_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((s_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (s3_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_131 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln120_10_fu_2547_p2 = (($signed(z_58_fu_2527_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_11_fu_2767_p2 = (($signed(z_59_fu_2747_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_12_fu_2987_p2 = (($signed(z_60_fu_2967_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_13_fu_3207_p2 = (($signed(z_61_fu_3187_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_14_fu_3427_p2 = (($signed(z_62_fu_3407_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_15_fu_3647_p2 = (($signed(z_63_fu_3627_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_1_fu_567_p2 = (($signed(z_49_fu_547_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_2_fu_787_p2 = (($signed(z_50_fu_767_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_3_fu_1007_p2 = (($signed(z_51_fu_987_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_4_fu_1227_p2 = (($signed(z_52_fu_1207_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_5_fu_1447_p2 = (($signed(z_53_fu_1427_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_6_fu_1667_p2 = (($signed(z_54_fu_1647_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_7_fu_1887_p2 = (($signed(z_55_fu_1867_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_8_fu_2107_p2 = (($signed(z_56_fu_2087_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_9_fu_2327_p2 = (($signed(z_57_fu_2307_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_347_p2 = (($signed(z_48_fu_327_p3) > $signed(20'd129434)) ? 1'b1 : 1'b0);

assign icmp_ln248_fu_3681_p2 = ((ap_sig_allocacmp_k1_load == 12'd4095) ? 1'b1 : 1'b0);

assign k_fu_3675_p2 = (ap_sig_allocacmp_k1_load + 12'd1);

assign or_ln119_10_fu_2561_p2 = (tmp_85_fu_2539_p3 | icmp_ln120_10_fu_2547_p2);

assign or_ln119_11_fu_2781_p2 = (tmp_93_fu_2759_p3 | icmp_ln120_11_fu_2767_p2);

assign or_ln119_12_fu_3001_p2 = (tmp_101_fu_2979_p3 | icmp_ln120_12_fu_2987_p2);

assign or_ln119_13_fu_3221_p2 = (tmp_109_fu_3199_p3 | icmp_ln120_13_fu_3207_p2);

assign or_ln119_14_fu_3441_p2 = (tmp_117_fu_3419_p3 | icmp_ln120_14_fu_3427_p2);

assign or_ln119_15_fu_3661_p2 = (tmp_125_fu_3639_p3 | icmp_ln120_15_fu_3647_p2);

assign or_ln119_1_fu_581_p2 = (tmp_13_fu_559_p3 | icmp_ln120_1_fu_567_p2);

assign or_ln119_2_fu_801_p2 = (tmp_21_fu_779_p3 | icmp_ln120_2_fu_787_p2);

assign or_ln119_3_fu_1021_p2 = (tmp_29_fu_999_p3 | icmp_ln120_3_fu_1007_p2);

assign or_ln119_4_fu_1241_p2 = (tmp_37_fu_1219_p3 | icmp_ln120_4_fu_1227_p2);

assign or_ln119_5_fu_1461_p2 = (tmp_45_fu_1439_p3 | icmp_ln120_5_fu_1447_p2);

assign or_ln119_6_fu_1681_p2 = (tmp_53_fu_1659_p3 | icmp_ln120_6_fu_1667_p2);

assign or_ln119_7_fu_1901_p2 = (tmp_61_fu_1879_p3 | icmp_ln120_7_fu_1887_p2);

assign or_ln119_8_fu_2121_p2 = (tmp_69_fu_2099_p3 | icmp_ln120_8_fu_2107_p2);

assign or_ln119_9_fu_2341_p2 = (tmp_77_fu_2319_p3 | icmp_ln120_9_fu_2327_p2);

assign or_ln119_fu_361_p2 = (tmp_6_fu_339_p3 | icmp_ln120_fu_347_p2);

assign or_ln254_10_fu_1383_p2 = (xor_ln254_28_fu_1377_p2 | tmp_44_fu_1345_p3);

assign or_ln254_11_fu_1421_p2 = (and_ln254_11_fu_1407_p2 | and_ln254_10_fu_1389_p2);

assign or_ln254_12_fu_1603_p2 = (xor_ln254_33_fu_1597_p2 | tmp_52_fu_1565_p3);

assign or_ln254_13_fu_1641_p2 = (and_ln254_13_fu_1627_p2 | and_ln254_12_fu_1609_p2);

assign or_ln254_14_fu_1823_p2 = (xor_ln254_38_fu_1817_p2 | tmp_60_fu_1785_p3);

assign or_ln254_15_fu_1861_p2 = (and_ln254_15_fu_1847_p2 | and_ln254_14_fu_1829_p2);

assign or_ln254_16_fu_2043_p2 = (xor_ln254_43_fu_2037_p2 | tmp_68_fu_2005_p3);

assign or_ln254_17_fu_2081_p2 = (and_ln254_17_fu_2067_p2 | and_ln254_16_fu_2049_p2);

assign or_ln254_18_fu_2263_p2 = (xor_ln254_48_fu_2257_p2 | tmp_76_fu_2225_p3);

assign or_ln254_19_fu_2301_p2 = (and_ln254_19_fu_2287_p2 | and_ln254_18_fu_2269_p2);

assign or_ln254_1_fu_321_p2 = (and_ln254_fu_289_p2 | and_ln254_1_fu_307_p2);

assign or_ln254_20_fu_2483_p2 = (xor_ln254_53_fu_2477_p2 | tmp_84_fu_2445_p3);

assign or_ln254_21_fu_2521_p2 = (and_ln254_21_fu_2507_p2 | and_ln254_20_fu_2489_p2);

assign or_ln254_22_fu_2703_p2 = (xor_ln254_58_fu_2697_p2 | tmp_92_fu_2665_p3);

assign or_ln254_23_fu_2741_p2 = (and_ln254_23_fu_2727_p2 | and_ln254_22_fu_2709_p2);

assign or_ln254_24_fu_2923_p2 = (xor_ln254_63_fu_2917_p2 | tmp_100_fu_2885_p3);

assign or_ln254_25_fu_2961_p2 = (and_ln254_25_fu_2947_p2 | and_ln254_24_fu_2929_p2);

assign or_ln254_26_fu_3143_p2 = (xor_ln254_68_fu_3137_p2 | tmp_108_fu_3105_p3);

assign or_ln254_27_fu_3181_p2 = (and_ln254_27_fu_3167_p2 | and_ln254_26_fu_3149_p2);

assign or_ln254_28_fu_3363_p2 = (xor_ln254_73_fu_3357_p2 | tmp_116_fu_3325_p3);

assign or_ln254_29_fu_3401_p2 = (and_ln254_29_fu_3387_p2 | and_ln254_28_fu_3369_p2);

assign or_ln254_2_fu_503_p2 = (xor_ln254_8_fu_497_p2 | tmp_12_fu_465_p3);

assign or_ln254_30_fu_3583_p2 = (xor_ln254_78_fu_3577_p2 | tmp_124_fu_3545_p3);

assign or_ln254_31_fu_3621_p2 = (and_ln254_31_fu_3607_p2 | and_ln254_30_fu_3589_p2);

assign or_ln254_32_fu_259_p2 = (xor_ln254_fu_253_p2 | tmp_5_fu_245_p3);

assign or_ln254_33_fu_295_p2 = (tmp_5_fu_245_p3 | tmp_4_fu_227_p3);

assign or_ln254_34_fu_479_p2 = (xor_ln254_5_fu_473_p2 | tmp_12_fu_465_p3);

assign or_ln254_35_fu_515_p2 = (tmp_12_fu_465_p3 | tmp_11_fu_447_p3);

assign or_ln254_36_fu_699_p2 = (xor_ln254_10_fu_693_p2 | tmp_20_fu_685_p3);

assign or_ln254_37_fu_735_p2 = (tmp_20_fu_685_p3 | tmp_19_fu_667_p3);

assign or_ln254_38_fu_919_p2 = (xor_ln254_15_fu_913_p2 | tmp_28_fu_905_p3);

assign or_ln254_39_fu_955_p2 = (tmp_28_fu_905_p3 | tmp_27_fu_887_p3);

assign or_ln254_3_fu_541_p2 = (and_ln254_3_fu_527_p2 | and_ln254_2_fu_509_p2);

assign or_ln254_40_fu_1139_p2 = (xor_ln254_20_fu_1133_p2 | tmp_36_fu_1125_p3);

assign or_ln254_41_fu_1175_p2 = (tmp_36_fu_1125_p3 | tmp_35_fu_1107_p3);

assign or_ln254_42_fu_1359_p2 = (xor_ln254_25_fu_1353_p2 | tmp_44_fu_1345_p3);

assign or_ln254_43_fu_1395_p2 = (tmp_44_fu_1345_p3 | tmp_43_fu_1327_p3);

assign or_ln254_44_fu_1579_p2 = (xor_ln254_30_fu_1573_p2 | tmp_52_fu_1565_p3);

assign or_ln254_45_fu_1615_p2 = (tmp_52_fu_1565_p3 | tmp_51_fu_1547_p3);

assign or_ln254_46_fu_1799_p2 = (xor_ln254_35_fu_1793_p2 | tmp_60_fu_1785_p3);

assign or_ln254_47_fu_1835_p2 = (tmp_60_fu_1785_p3 | tmp_59_fu_1767_p3);

assign or_ln254_48_fu_2019_p2 = (xor_ln254_40_fu_2013_p2 | tmp_68_fu_2005_p3);

assign or_ln254_49_fu_2055_p2 = (tmp_68_fu_2005_p3 | tmp_67_fu_1987_p3);

assign or_ln254_4_fu_723_p2 = (xor_ln254_13_fu_717_p2 | tmp_20_fu_685_p3);

assign or_ln254_50_fu_2239_p2 = (xor_ln254_45_fu_2233_p2 | tmp_76_fu_2225_p3);

assign or_ln254_51_fu_2275_p2 = (tmp_76_fu_2225_p3 | tmp_75_fu_2207_p3);

assign or_ln254_52_fu_2459_p2 = (xor_ln254_50_fu_2453_p2 | tmp_84_fu_2445_p3);

assign or_ln254_53_fu_2495_p2 = (tmp_84_fu_2445_p3 | tmp_83_fu_2427_p3);

assign or_ln254_54_fu_2679_p2 = (xor_ln254_55_fu_2673_p2 | tmp_92_fu_2665_p3);

assign or_ln254_55_fu_2715_p2 = (tmp_92_fu_2665_p3 | tmp_91_fu_2647_p3);

assign or_ln254_56_fu_2899_p2 = (xor_ln254_60_fu_2893_p2 | tmp_100_fu_2885_p3);

assign or_ln254_57_fu_2935_p2 = (tmp_99_fu_2867_p3 | tmp_100_fu_2885_p3);

assign or_ln254_58_fu_3119_p2 = (xor_ln254_65_fu_3113_p2 | tmp_108_fu_3105_p3);

assign or_ln254_59_fu_3155_p2 = (tmp_108_fu_3105_p3 | tmp_107_fu_3087_p3);

assign or_ln254_5_fu_761_p2 = (and_ln254_5_fu_747_p2 | and_ln254_4_fu_729_p2);

assign or_ln254_60_fu_3339_p2 = (xor_ln254_70_fu_3333_p2 | tmp_116_fu_3325_p3);

assign or_ln254_61_fu_3375_p2 = (tmp_116_fu_3325_p3 | tmp_115_fu_3307_p3);

assign or_ln254_62_fu_3559_p2 = (xor_ln254_75_fu_3553_p2 | tmp_124_fu_3545_p3);

assign or_ln254_63_fu_3595_p2 = (tmp_124_fu_3545_p3 | tmp_123_fu_3527_p3);

assign or_ln254_6_fu_943_p2 = (xor_ln254_18_fu_937_p2 | tmp_28_fu_905_p3);

assign or_ln254_7_fu_981_p2 = (and_ln254_7_fu_967_p2 | and_ln254_6_fu_949_p2);

assign or_ln254_8_fu_1163_p2 = (xor_ln254_23_fu_1157_p2 | tmp_36_fu_1125_p3);

assign or_ln254_9_fu_1201_p2 = (and_ln254_9_fu_1187_p2 | and_ln254_8_fu_1169_p2);

assign or_ln254_fu_283_p2 = (xor_ln254_3_fu_277_p2 | tmp_5_fu_245_p3);

assign s_out_din = tmp_124_i_fu_3737_p32;

assign select_ln119_10_fu_1453_p3 = ((tmp_45_fu_1439_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_12_fu_1673_p3 = ((tmp_53_fu_1659_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_14_fu_1893_p3 = ((tmp_61_fu_1879_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_16_fu_2113_p3 = ((tmp_69_fu_2099_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_18_fu_2333_p3 = ((tmp_77_fu_2319_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_20_fu_2553_p3 = ((tmp_85_fu_2539_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_22_fu_2773_p3 = ((tmp_93_fu_2759_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_24_fu_2993_p3 = ((tmp_101_fu_2979_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_26_fu_3213_p3 = ((tmp_109_fu_3199_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_28_fu_3433_p3 = ((tmp_117_fu_3419_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_2_fu_573_p3 = ((tmp_13_fu_559_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_30_fu_3653_p3 = ((tmp_125_fu_3639_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_31_fu_3667_p3 = ((or_ln119_15_fu_3661_p2[0:0] == 1'b1) ? select_ln119_30_fu_3653_p3 : trunc_ln254_16_fu_3635_p1);

assign select_ln119_4_fu_793_p3 = ((tmp_21_fu_779_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_6_fu_1013_p3 = ((tmp_29_fu_999_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_8_fu_1233_p3 = ((tmp_37_fu_1219_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln119_fu_353_p3 = ((tmp_6_fu_339_p3[0:0] == 1'b1) ? 17'd0 : 17'd129434);

assign select_ln254_10_fu_1413_p3 = ((and_ln254_10_fu_1389_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_12_fu_1633_p3 = ((and_ln254_12_fu_1609_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_14_fu_1853_p3 = ((and_ln254_14_fu_1829_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_16_fu_2073_p3 = ((and_ln254_16_fu_2049_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_18_fu_2293_p3 = ((and_ln254_18_fu_2269_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_20_fu_2513_p3 = ((and_ln254_20_fu_2489_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_22_fu_2733_p3 = ((and_ln254_22_fu_2709_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_24_fu_2953_p3 = ((and_ln254_24_fu_2929_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_26_fu_3173_p3 = ((and_ln254_26_fu_3149_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_28_fu_3393_p3 = ((and_ln254_28_fu_3369_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_2_fu_533_p3 = ((and_ln254_2_fu_509_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_30_fu_3613_p3 = ((and_ln254_30_fu_3589_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_4_fu_753_p3 = ((and_ln254_4_fu_729_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_6_fu_973_p3 = ((and_ln254_6_fu_949_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_8_fu_1193_p3 = ((and_ln254_8_fu_1169_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign select_ln254_fu_313_p3 = ((and_ln254_fu_289_p2[0:0] == 1'b1) ? 20'd524287 : 20'd524288);

assign sext_ln254_10_fu_1273_p1 = $signed(tmp_39_fu_1265_p3);

assign sext_ln254_11_fu_1285_p1 = $signed(tmp_40_fu_1277_p3);

assign sext_ln254_12_fu_1493_p1 = $signed(tmp_47_fu_1485_p3);

assign sext_ln254_13_fu_1505_p1 = $signed(tmp_48_fu_1497_p3);

assign sext_ln254_14_fu_1713_p1 = $signed(tmp_55_fu_1705_p3);

assign sext_ln254_15_fu_1725_p1 = $signed(tmp_56_fu_1717_p3);

assign sext_ln254_16_fu_1933_p1 = $signed(tmp_63_fu_1925_p3);

assign sext_ln254_17_fu_1945_p1 = $signed(tmp_64_fu_1937_p3);

assign sext_ln254_18_fu_2153_p1 = $signed(tmp_71_fu_2145_p3);

assign sext_ln254_19_fu_2165_p1 = $signed(tmp_72_fu_2157_p3);

assign sext_ln254_1_fu_185_p1 = $signed(tmp_1_fu_177_p3);

assign sext_ln254_20_fu_2373_p1 = $signed(tmp_79_fu_2365_p3);

assign sext_ln254_21_fu_2385_p1 = $signed(tmp_80_fu_2377_p3);

assign sext_ln254_22_fu_2593_p1 = $signed(tmp_87_fu_2585_p3);

assign sext_ln254_23_fu_2605_p1 = $signed(tmp_88_fu_2597_p3);

assign sext_ln254_24_fu_2813_p1 = $signed(tmp_95_fu_2805_p3);

assign sext_ln254_25_fu_2825_p1 = $signed(tmp_96_fu_2817_p3);

assign sext_ln254_26_fu_3033_p1 = $signed(tmp_103_fu_3025_p3);

assign sext_ln254_27_fu_3045_p1 = $signed(tmp_104_fu_3037_p3);

assign sext_ln254_28_fu_3253_p1 = $signed(tmp_111_fu_3245_p3);

assign sext_ln254_29_fu_3265_p1 = $signed(tmp_112_fu_3257_p3);

assign sext_ln254_2_fu_393_p1 = $signed(tmp_7_fu_385_p3);

assign sext_ln254_30_fu_3473_p1 = $signed(tmp_119_fu_3465_p3);

assign sext_ln254_31_fu_3485_p1 = $signed(tmp_120_fu_3477_p3);

assign sext_ln254_3_fu_405_p1 = $signed(tmp_8_fu_397_p3);

assign sext_ln254_4_fu_613_p1 = $signed(tmp_15_fu_605_p3);

assign sext_ln254_5_fu_625_p1 = $signed(tmp_16_fu_617_p3);

assign sext_ln254_6_fu_833_p1 = $signed(tmp_23_fu_825_p3);

assign sext_ln254_7_fu_845_p1 = $signed(tmp_24_fu_837_p3);

assign sext_ln254_8_fu_1053_p1 = $signed(tmp_31_fu_1045_p3);

assign sext_ln254_9_fu_1065_p1 = $signed(tmp_32_fu_1057_p3);

assign sext_ln254_fu_173_p1 = $signed(tmp_fu_165_p3);

assign tmp_100_fu_2885_p3 = z_37_fu_2879_p2[32'd19];

assign tmp_101_fu_2979_p3 = z_60_fu_2967_p3[32'd19];

assign tmp_102_fu_3015_p4 = {{s3_dout[435:416]}};

assign tmp_103_fu_3025_p3 = {{tmp_102_fu_3015_p4}, {34'd0}};

assign tmp_104_fu_3037_p3 = {{tmp_102_fu_3015_p4}, {32'd0}};

assign tmp_105_fu_3061_p3 = add_ln254_26_fu_3055_p2[32'd54];

assign tmp_106_fu_3079_p3 = add_ln254_26_fu_3055_p2[32'd33];

assign tmp_107_fu_3087_p3 = add_ln254_26_fu_3055_p2[32'd53];

assign tmp_108_fu_3105_p3 = z_40_fu_3099_p2[32'd19];

assign tmp_109_fu_3199_p3 = z_61_fu_3187_p3[32'd19];

assign tmp_10_fu_439_p3 = add_ln254_2_fu_415_p2[32'd33];

assign tmp_110_fu_3235_p4 = {{s3_dout[467:448]}};

assign tmp_111_fu_3245_p3 = {{tmp_110_fu_3235_p4}, {34'd0}};

assign tmp_112_fu_3257_p3 = {{tmp_110_fu_3235_p4}, {32'd0}};

assign tmp_113_fu_3281_p3 = add_ln254_28_fu_3275_p2[32'd54];

assign tmp_114_fu_3299_p3 = add_ln254_28_fu_3275_p2[32'd33];

assign tmp_115_fu_3307_p3 = add_ln254_28_fu_3275_p2[32'd53];

assign tmp_116_fu_3325_p3 = z_43_fu_3319_p2[32'd19];

assign tmp_117_fu_3419_p3 = z_62_fu_3407_p3[32'd19];

assign tmp_118_fu_3455_p4 = {{s3_dout[499:480]}};

assign tmp_119_fu_3465_p3 = {{tmp_118_fu_3455_p4}, {34'd0}};

assign tmp_11_fu_447_p3 = add_ln254_2_fu_415_p2[32'd53];

assign tmp_120_fu_3477_p3 = {{tmp_118_fu_3455_p4}, {32'd0}};

assign tmp_121_fu_3501_p3 = add_ln254_30_fu_3495_p2[32'd54];

assign tmp_122_fu_3519_p3 = add_ln254_30_fu_3495_p2[32'd33];

assign tmp_123_fu_3527_p3 = add_ln254_30_fu_3495_p2[32'd53];

assign tmp_124_fu_3545_p3 = z_46_fu_3539_p2[32'd19];

assign tmp_124_i_fu_3737_p32 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln119_31_reg_3889}, {12'd0}}, {zext_ln251_14_fu_3734_p1}}, {12'd0}}, {zext_ln251_13_fu_3731_p1}}, {12'd0}}, {zext_ln251_12_fu_3728_p1}}, {12'd0}}, {zext_ln251_11_fu_3725_p1}}, {12'd0}}, {zext_ln251_10_fu_3722_p1}}, {12'd0}}, {zext_ln251_9_fu_3719_p1}}, {12'd0}}, {zext_ln251_8_fu_3716_p1}}, {12'd0}}, {zext_ln251_7_fu_3713_p1}}, {12'd0}}, {zext_ln251_6_fu_3710_p1}}, {12'd0}}, {zext_ln251_5_fu_3707_p1}}, {12'd0}}, {zext_ln251_4_fu_3704_p1}}, {12'd0}}, {zext_ln251_3_fu_3701_p1}}, {12'd0}}, {zext_ln251_2_fu_3698_p1}}, {12'd0}}, {zext_ln251_1_fu_3695_p1}}, {12'd0}}, {zext_ln251_fu_3692_p1}};

assign tmp_125_fu_3639_p3 = z_63_fu_3627_p3[32'd19];

assign tmp_12_fu_465_p3 = z_4_fu_459_p2[32'd19];

assign tmp_13_fu_559_p3 = z_49_fu_547_p3[32'd19];

assign tmp_14_fu_595_p4 = {{s3_dout[83:64]}};

assign tmp_15_fu_605_p3 = {{tmp_14_fu_595_p4}, {34'd0}};

assign tmp_16_fu_617_p3 = {{tmp_14_fu_595_p4}, {32'd0}};

assign tmp_17_fu_641_p3 = add_ln254_4_fu_635_p2[32'd54];

assign tmp_18_fu_659_p3 = add_ln254_4_fu_635_p2[32'd33];

assign tmp_19_fu_667_p3 = add_ln254_4_fu_635_p2[32'd53];

assign tmp_1_fu_177_p3 = {{trunc_ln254_fu_161_p1}, {32'd0}};

assign tmp_20_fu_685_p3 = z_7_fu_679_p2[32'd19];

assign tmp_21_fu_779_p3 = z_50_fu_767_p3[32'd19];

assign tmp_22_fu_815_p4 = {{s3_dout[115:96]}};

assign tmp_23_fu_825_p3 = {{tmp_22_fu_815_p4}, {34'd0}};

assign tmp_24_fu_837_p3 = {{tmp_22_fu_815_p4}, {32'd0}};

assign tmp_25_fu_861_p3 = add_ln254_6_fu_855_p2[32'd54];

assign tmp_26_fu_879_p3 = add_ln254_6_fu_855_p2[32'd33];

assign tmp_27_fu_887_p3 = add_ln254_6_fu_855_p2[32'd53];

assign tmp_28_fu_905_p3 = z_10_fu_899_p2[32'd19];

assign tmp_29_fu_999_p3 = z_51_fu_987_p3[32'd19];

assign tmp_2_fu_201_p3 = add_ln254_fu_195_p2[32'd54];

assign tmp_30_fu_1035_p4 = {{s3_dout[147:128]}};

assign tmp_31_fu_1045_p3 = {{tmp_30_fu_1035_p4}, {34'd0}};

assign tmp_32_fu_1057_p3 = {{tmp_30_fu_1035_p4}, {32'd0}};

assign tmp_33_fu_1081_p3 = add_ln254_8_fu_1075_p2[32'd54];

assign tmp_34_fu_1099_p3 = add_ln254_8_fu_1075_p2[32'd33];

assign tmp_35_fu_1107_p3 = add_ln254_8_fu_1075_p2[32'd53];

assign tmp_36_fu_1125_p3 = z_13_fu_1119_p2[32'd19];

assign tmp_37_fu_1219_p3 = z_52_fu_1207_p3[32'd19];

assign tmp_38_fu_1255_p4 = {{s3_dout[179:160]}};

assign tmp_39_fu_1265_p3 = {{tmp_38_fu_1255_p4}, {34'd0}};

assign tmp_3_fu_219_p3 = add_ln254_fu_195_p2[32'd33];

assign tmp_40_fu_1277_p3 = {{tmp_38_fu_1255_p4}, {32'd0}};

assign tmp_41_fu_1301_p3 = add_ln254_10_fu_1295_p2[32'd54];

assign tmp_42_fu_1319_p3 = add_ln254_10_fu_1295_p2[32'd33];

assign tmp_43_fu_1327_p3 = add_ln254_10_fu_1295_p2[32'd53];

assign tmp_44_fu_1345_p3 = z_16_fu_1339_p2[32'd19];

assign tmp_45_fu_1439_p3 = z_53_fu_1427_p3[32'd19];

assign tmp_46_fu_1475_p4 = {{s3_dout[211:192]}};

assign tmp_47_fu_1485_p3 = {{tmp_46_fu_1475_p4}, {34'd0}};

assign tmp_48_fu_1497_p3 = {{tmp_46_fu_1475_p4}, {32'd0}};

assign tmp_49_fu_1521_p3 = add_ln254_12_fu_1515_p2[32'd54];

assign tmp_4_fu_227_p3 = add_ln254_fu_195_p2[32'd53];

assign tmp_50_fu_1539_p3 = add_ln254_12_fu_1515_p2[32'd33];

assign tmp_51_fu_1547_p3 = add_ln254_12_fu_1515_p2[32'd53];

assign tmp_52_fu_1565_p3 = z_19_fu_1559_p2[32'd19];

assign tmp_53_fu_1659_p3 = z_54_fu_1647_p3[32'd19];

assign tmp_54_fu_1695_p4 = {{s3_dout[243:224]}};

assign tmp_55_fu_1705_p3 = {{tmp_54_fu_1695_p4}, {34'd0}};

assign tmp_56_fu_1717_p3 = {{tmp_54_fu_1695_p4}, {32'd0}};

assign tmp_57_fu_1741_p3 = add_ln254_14_fu_1735_p2[32'd54];

assign tmp_58_fu_1759_p3 = add_ln254_14_fu_1735_p2[32'd33];

assign tmp_59_fu_1767_p3 = add_ln254_14_fu_1735_p2[32'd53];

assign tmp_5_fu_245_p3 = z_1_fu_239_p2[32'd19];

assign tmp_60_fu_1785_p3 = z_22_fu_1779_p2[32'd19];

assign tmp_61_fu_1879_p3 = z_55_fu_1867_p3[32'd19];

assign tmp_62_fu_1915_p4 = {{s3_dout[275:256]}};

assign tmp_63_fu_1925_p3 = {{tmp_62_fu_1915_p4}, {34'd0}};

assign tmp_64_fu_1937_p3 = {{tmp_62_fu_1915_p4}, {32'd0}};

assign tmp_65_fu_1961_p3 = add_ln254_16_fu_1955_p2[32'd54];

assign tmp_66_fu_1979_p3 = add_ln254_16_fu_1955_p2[32'd33];

assign tmp_67_fu_1987_p3 = add_ln254_16_fu_1955_p2[32'd53];

assign tmp_68_fu_2005_p3 = z_25_fu_1999_p2[32'd19];

assign tmp_69_fu_2099_p3 = z_56_fu_2087_p3[32'd19];

assign tmp_6_fu_339_p3 = z_48_fu_327_p3[32'd19];

assign tmp_70_fu_2135_p4 = {{s3_dout[307:288]}};

assign tmp_71_fu_2145_p3 = {{tmp_70_fu_2135_p4}, {34'd0}};

assign tmp_72_fu_2157_p3 = {{tmp_70_fu_2135_p4}, {32'd0}};

assign tmp_73_fu_2181_p3 = add_ln254_18_fu_2175_p2[32'd54];

assign tmp_74_fu_2199_p3 = add_ln254_18_fu_2175_p2[32'd33];

assign tmp_75_fu_2207_p3 = add_ln254_18_fu_2175_p2[32'd53];

assign tmp_76_fu_2225_p3 = z_28_fu_2219_p2[32'd19];

assign tmp_77_fu_2319_p3 = z_57_fu_2307_p3[32'd19];

assign tmp_78_fu_2355_p4 = {{s3_dout[339:320]}};

assign tmp_79_fu_2365_p3 = {{tmp_78_fu_2355_p4}, {34'd0}};

assign tmp_7_fu_385_p3 = {{tmp_s_fu_375_p4}, {34'd0}};

assign tmp_80_fu_2377_p3 = {{tmp_78_fu_2355_p4}, {32'd0}};

assign tmp_81_fu_2401_p3 = add_ln254_20_fu_2395_p2[32'd54];

assign tmp_82_fu_2419_p3 = add_ln254_20_fu_2395_p2[32'd33];

assign tmp_83_fu_2427_p3 = add_ln254_20_fu_2395_p2[32'd53];

assign tmp_84_fu_2445_p3 = z_31_fu_2439_p2[32'd19];

assign tmp_85_fu_2539_p3 = z_58_fu_2527_p3[32'd19];

assign tmp_86_fu_2575_p4 = {{s3_dout[371:352]}};

assign tmp_87_fu_2585_p3 = {{tmp_86_fu_2575_p4}, {34'd0}};

assign tmp_88_fu_2597_p3 = {{tmp_86_fu_2575_p4}, {32'd0}};

assign tmp_89_fu_2621_p3 = add_ln254_22_fu_2615_p2[32'd54];

assign tmp_8_fu_397_p3 = {{tmp_s_fu_375_p4}, {32'd0}};

assign tmp_90_fu_2639_p3 = add_ln254_22_fu_2615_p2[32'd33];

assign tmp_91_fu_2647_p3 = add_ln254_22_fu_2615_p2[32'd53];

assign tmp_92_fu_2665_p3 = z_34_fu_2659_p2[32'd19];

assign tmp_93_fu_2759_p3 = z_59_fu_2747_p3[32'd19];

assign tmp_94_fu_2795_p4 = {{s3_dout[403:384]}};

assign tmp_95_fu_2805_p3 = {{tmp_94_fu_2795_p4}, {34'd0}};

assign tmp_96_fu_2817_p3 = {{tmp_94_fu_2795_p4}, {32'd0}};

assign tmp_97_fu_2841_p3 = add_ln254_24_fu_2835_p2[32'd54];

assign tmp_98_fu_2859_p3 = add_ln254_24_fu_2835_p2[32'd33];

assign tmp_99_fu_2867_p3 = add_ln254_24_fu_2835_p2[32'd53];

assign tmp_9_fu_421_p3 = add_ln254_2_fu_415_p2[32'd54];

assign tmp_fu_165_p3 = {{trunc_ln254_fu_161_p1}, {34'd0}};

assign tmp_s_fu_375_p4 = {{s3_dout[51:32]}};

assign trunc_ln254_10_fu_2315_p1 = z_57_fu_2307_p3[16:0];

assign trunc_ln254_11_fu_2535_p1 = z_58_fu_2527_p3[16:0];

assign trunc_ln254_12_fu_2755_p1 = z_59_fu_2747_p3[16:0];

assign trunc_ln254_13_fu_2975_p1 = z_60_fu_2967_p3[16:0];

assign trunc_ln254_14_fu_3195_p1 = z_61_fu_3187_p3[16:0];

assign trunc_ln254_15_fu_3415_p1 = z_62_fu_3407_p3[16:0];

assign trunc_ln254_16_fu_3635_p1 = z_63_fu_3627_p3[16:0];

assign trunc_ln254_1_fu_335_p1 = z_48_fu_327_p3[16:0];

assign trunc_ln254_2_fu_555_p1 = z_49_fu_547_p3[16:0];

assign trunc_ln254_3_fu_775_p1 = z_50_fu_767_p3[16:0];

assign trunc_ln254_4_fu_995_p1 = z_51_fu_987_p3[16:0];

assign trunc_ln254_5_fu_1215_p1 = z_52_fu_1207_p3[16:0];

assign trunc_ln254_6_fu_1435_p1 = z_53_fu_1427_p3[16:0];

assign trunc_ln254_7_fu_1655_p1 = z_54_fu_1647_p3[16:0];

assign trunc_ln254_8_fu_1875_p1 = z_55_fu_1867_p3[16:0];

assign trunc_ln254_9_fu_2095_p1 = z_56_fu_2087_p3[16:0];

assign trunc_ln254_fu_161_p1 = s3_dout[19:0];

assign v_out_10_fu_2567_p3 = ((or_ln119_10_fu_2561_p2[0:0] == 1'b1) ? select_ln119_20_fu_2553_p3 : trunc_ln254_11_fu_2535_p1);

assign v_out_11_fu_2787_p3 = ((or_ln119_11_fu_2781_p2[0:0] == 1'b1) ? select_ln119_22_fu_2773_p3 : trunc_ln254_12_fu_2755_p1);

assign v_out_12_fu_3007_p3 = ((or_ln119_12_fu_3001_p2[0:0] == 1'b1) ? select_ln119_24_fu_2993_p3 : trunc_ln254_13_fu_2975_p1);

assign v_out_13_fu_3227_p3 = ((or_ln119_13_fu_3221_p2[0:0] == 1'b1) ? select_ln119_26_fu_3213_p3 : trunc_ln254_14_fu_3195_p1);

assign v_out_14_fu_3447_p3 = ((or_ln119_14_fu_3441_p2[0:0] == 1'b1) ? select_ln119_28_fu_3433_p3 : trunc_ln254_15_fu_3415_p1);

assign v_out_1_fu_587_p3 = ((or_ln119_1_fu_581_p2[0:0] == 1'b1) ? select_ln119_2_fu_573_p3 : trunc_ln254_2_fu_555_p1);

assign v_out_2_fu_807_p3 = ((or_ln119_2_fu_801_p2[0:0] == 1'b1) ? select_ln119_4_fu_793_p3 : trunc_ln254_3_fu_775_p1);

assign v_out_3_fu_1027_p3 = ((or_ln119_3_fu_1021_p2[0:0] == 1'b1) ? select_ln119_6_fu_1013_p3 : trunc_ln254_4_fu_995_p1);

assign v_out_4_fu_1247_p3 = ((or_ln119_4_fu_1241_p2[0:0] == 1'b1) ? select_ln119_8_fu_1233_p3 : trunc_ln254_5_fu_1215_p1);

assign v_out_5_fu_1467_p3 = ((or_ln119_5_fu_1461_p2[0:0] == 1'b1) ? select_ln119_10_fu_1453_p3 : trunc_ln254_6_fu_1435_p1);

assign v_out_6_fu_1687_p3 = ((or_ln119_6_fu_1681_p2[0:0] == 1'b1) ? select_ln119_12_fu_1673_p3 : trunc_ln254_7_fu_1655_p1);

assign v_out_7_fu_1907_p3 = ((or_ln119_7_fu_1901_p2[0:0] == 1'b1) ? select_ln119_14_fu_1893_p3 : trunc_ln254_8_fu_1875_p1);

assign v_out_8_fu_2127_p3 = ((or_ln119_8_fu_2121_p2[0:0] == 1'b1) ? select_ln119_16_fu_2113_p3 : trunc_ln254_9_fu_2095_p1);

assign v_out_9_fu_2347_p3 = ((or_ln119_9_fu_2341_p2[0:0] == 1'b1) ? select_ln119_18_fu_2333_p3 : trunc_ln254_10_fu_2315_p1);

assign v_out_fu_367_p3 = ((or_ln119_fu_361_p2[0:0] == 1'b1) ? select_ln119_fu_353_p3 : trunc_ln254_1_fu_335_p1);

assign xor_ln254_10_fu_693_p2 = (tmp_19_fu_667_p3 ^ 1'd1);

assign xor_ln254_11_fu_705_p2 = (tmp_17_fu_641_p3 ^ 1'd1);

assign xor_ln254_12_fu_711_p2 = (tmp_17_fu_641_p3 ^ or_ln254_36_fu_699_p2);

assign xor_ln254_13_fu_717_p2 = (xor_ln254_12_fu_711_p2 ^ 1'd1);

assign xor_ln254_14_fu_741_p2 = (or_ln254_37_fu_735_p2 ^ 1'd1);

assign xor_ln254_15_fu_913_p2 = (tmp_27_fu_887_p3 ^ 1'd1);

assign xor_ln254_16_fu_925_p2 = (tmp_25_fu_861_p3 ^ 1'd1);

assign xor_ln254_17_fu_931_p2 = (tmp_25_fu_861_p3 ^ or_ln254_38_fu_919_p2);

assign xor_ln254_18_fu_937_p2 = (xor_ln254_17_fu_931_p2 ^ 1'd1);

assign xor_ln254_19_fu_961_p2 = (or_ln254_39_fu_955_p2 ^ 1'd1);

assign xor_ln254_1_fu_265_p2 = (tmp_2_fu_201_p3 ^ 1'd1);

assign xor_ln254_20_fu_1133_p2 = (tmp_35_fu_1107_p3 ^ 1'd1);

assign xor_ln254_21_fu_1145_p2 = (tmp_33_fu_1081_p3 ^ 1'd1);

assign xor_ln254_22_fu_1151_p2 = (tmp_33_fu_1081_p3 ^ or_ln254_40_fu_1139_p2);

assign xor_ln254_23_fu_1157_p2 = (xor_ln254_22_fu_1151_p2 ^ 1'd1);

assign xor_ln254_24_fu_1181_p2 = (or_ln254_41_fu_1175_p2 ^ 1'd1);

assign xor_ln254_25_fu_1353_p2 = (tmp_43_fu_1327_p3 ^ 1'd1);

assign xor_ln254_26_fu_1365_p2 = (tmp_41_fu_1301_p3 ^ 1'd1);

assign xor_ln254_27_fu_1371_p2 = (tmp_41_fu_1301_p3 ^ or_ln254_42_fu_1359_p2);

assign xor_ln254_28_fu_1377_p2 = (xor_ln254_27_fu_1371_p2 ^ 1'd1);

assign xor_ln254_29_fu_1401_p2 = (or_ln254_43_fu_1395_p2 ^ 1'd1);

assign xor_ln254_2_fu_271_p2 = (tmp_2_fu_201_p3 ^ or_ln254_32_fu_259_p2);

assign xor_ln254_30_fu_1573_p2 = (tmp_51_fu_1547_p3 ^ 1'd1);

assign xor_ln254_31_fu_1585_p2 = (tmp_49_fu_1521_p3 ^ 1'd1);

assign xor_ln254_32_fu_1591_p2 = (tmp_49_fu_1521_p3 ^ or_ln254_44_fu_1579_p2);

assign xor_ln254_33_fu_1597_p2 = (xor_ln254_32_fu_1591_p2 ^ 1'd1);

assign xor_ln254_34_fu_1621_p2 = (or_ln254_45_fu_1615_p2 ^ 1'd1);

assign xor_ln254_35_fu_1793_p2 = (tmp_59_fu_1767_p3 ^ 1'd1);

assign xor_ln254_36_fu_1805_p2 = (tmp_57_fu_1741_p3 ^ 1'd1);

assign xor_ln254_37_fu_1811_p2 = (tmp_57_fu_1741_p3 ^ or_ln254_46_fu_1799_p2);

assign xor_ln254_38_fu_1817_p2 = (xor_ln254_37_fu_1811_p2 ^ 1'd1);

assign xor_ln254_39_fu_1841_p2 = (or_ln254_47_fu_1835_p2 ^ 1'd1);

assign xor_ln254_3_fu_277_p2 = (xor_ln254_2_fu_271_p2 ^ 1'd1);

assign xor_ln254_40_fu_2013_p2 = (tmp_67_fu_1987_p3 ^ 1'd1);

assign xor_ln254_41_fu_2025_p2 = (tmp_65_fu_1961_p3 ^ 1'd1);

assign xor_ln254_42_fu_2031_p2 = (tmp_65_fu_1961_p3 ^ or_ln254_48_fu_2019_p2);

assign xor_ln254_43_fu_2037_p2 = (xor_ln254_42_fu_2031_p2 ^ 1'd1);

assign xor_ln254_44_fu_2061_p2 = (or_ln254_49_fu_2055_p2 ^ 1'd1);

assign xor_ln254_45_fu_2233_p2 = (tmp_75_fu_2207_p3 ^ 1'd1);

assign xor_ln254_46_fu_2245_p2 = (tmp_73_fu_2181_p3 ^ 1'd1);

assign xor_ln254_47_fu_2251_p2 = (tmp_73_fu_2181_p3 ^ or_ln254_50_fu_2239_p2);

assign xor_ln254_48_fu_2257_p2 = (xor_ln254_47_fu_2251_p2 ^ 1'd1);

assign xor_ln254_49_fu_2281_p2 = (or_ln254_51_fu_2275_p2 ^ 1'd1);

assign xor_ln254_4_fu_301_p2 = (or_ln254_33_fu_295_p2 ^ 1'd1);

assign xor_ln254_50_fu_2453_p2 = (tmp_83_fu_2427_p3 ^ 1'd1);

assign xor_ln254_51_fu_2465_p2 = (tmp_81_fu_2401_p3 ^ 1'd1);

assign xor_ln254_52_fu_2471_p2 = (tmp_81_fu_2401_p3 ^ or_ln254_52_fu_2459_p2);

assign xor_ln254_53_fu_2477_p2 = (xor_ln254_52_fu_2471_p2 ^ 1'd1);

assign xor_ln254_54_fu_2501_p2 = (or_ln254_53_fu_2495_p2 ^ 1'd1);

assign xor_ln254_55_fu_2673_p2 = (tmp_91_fu_2647_p3 ^ 1'd1);

assign xor_ln254_56_fu_2685_p2 = (tmp_89_fu_2621_p3 ^ 1'd1);

assign xor_ln254_57_fu_2691_p2 = (tmp_89_fu_2621_p3 ^ or_ln254_54_fu_2679_p2);

assign xor_ln254_58_fu_2697_p2 = (xor_ln254_57_fu_2691_p2 ^ 1'd1);

assign xor_ln254_59_fu_2721_p2 = (or_ln254_55_fu_2715_p2 ^ 1'd1);

assign xor_ln254_5_fu_473_p2 = (tmp_11_fu_447_p3 ^ 1'd1);

assign xor_ln254_60_fu_2893_p2 = (tmp_99_fu_2867_p3 ^ 1'd1);

assign xor_ln254_61_fu_2905_p2 = (tmp_97_fu_2841_p3 ^ 1'd1);

assign xor_ln254_62_fu_2911_p2 = (tmp_97_fu_2841_p3 ^ or_ln254_56_fu_2899_p2);

assign xor_ln254_63_fu_2917_p2 = (xor_ln254_62_fu_2911_p2 ^ 1'd1);

assign xor_ln254_64_fu_2941_p2 = (or_ln254_57_fu_2935_p2 ^ 1'd1);

assign xor_ln254_65_fu_3113_p2 = (tmp_107_fu_3087_p3 ^ 1'd1);

assign xor_ln254_66_fu_3125_p2 = (tmp_105_fu_3061_p3 ^ 1'd1);

assign xor_ln254_67_fu_3131_p2 = (tmp_105_fu_3061_p3 ^ or_ln254_58_fu_3119_p2);

assign xor_ln254_68_fu_3137_p2 = (xor_ln254_67_fu_3131_p2 ^ 1'd1);

assign xor_ln254_69_fu_3161_p2 = (or_ln254_59_fu_3155_p2 ^ 1'd1);

assign xor_ln254_6_fu_485_p2 = (tmp_9_fu_421_p3 ^ 1'd1);

assign xor_ln254_70_fu_3333_p2 = (tmp_115_fu_3307_p3 ^ 1'd1);

assign xor_ln254_71_fu_3345_p2 = (tmp_113_fu_3281_p3 ^ 1'd1);

assign xor_ln254_72_fu_3351_p2 = (tmp_113_fu_3281_p3 ^ or_ln254_60_fu_3339_p2);

assign xor_ln254_73_fu_3357_p2 = (xor_ln254_72_fu_3351_p2 ^ 1'd1);

assign xor_ln254_74_fu_3381_p2 = (or_ln254_61_fu_3375_p2 ^ 1'd1);

assign xor_ln254_75_fu_3553_p2 = (tmp_123_fu_3527_p3 ^ 1'd1);

assign xor_ln254_76_fu_3565_p2 = (tmp_121_fu_3501_p3 ^ 1'd1);

assign xor_ln254_77_fu_3571_p2 = (tmp_121_fu_3501_p3 ^ or_ln254_62_fu_3559_p2);

assign xor_ln254_78_fu_3577_p2 = (xor_ln254_77_fu_3571_p2 ^ 1'd1);

assign xor_ln254_79_fu_3601_p2 = (or_ln254_63_fu_3595_p2 ^ 1'd1);

assign xor_ln254_7_fu_491_p2 = (tmp_9_fu_421_p3 ^ or_ln254_34_fu_479_p2);

assign xor_ln254_8_fu_497_p2 = (xor_ln254_7_fu_491_p2 ^ 1'd1);

assign xor_ln254_9_fu_521_p2 = (or_ln254_35_fu_515_p2 ^ 1'd1);

assign xor_ln254_fu_253_p2 = (tmp_4_fu_227_p3 ^ 1'd1);

assign z_10_fu_899_p2 = (z_9_fu_869_p4 + zext_ln254_3_fu_895_p1);

assign z_12_fu_1089_p4 = {{add_ln254_8_fu_1075_p2[53:34]}};

assign z_13_fu_1119_p2 = (z_12_fu_1089_p4 + zext_ln254_4_fu_1115_p1);

assign z_15_fu_1309_p4 = {{add_ln254_10_fu_1295_p2[53:34]}};

assign z_16_fu_1339_p2 = (z_15_fu_1309_p4 + zext_ln254_5_fu_1335_p1);

assign z_18_fu_1529_p4 = {{add_ln254_12_fu_1515_p2[53:34]}};

assign z_19_fu_1559_p2 = (z_18_fu_1529_p4 + zext_ln254_6_fu_1555_p1);

assign z_1_fu_239_p2 = (z_fu_209_p4 + zext_ln254_fu_235_p1);

assign z_21_fu_1749_p4 = {{add_ln254_14_fu_1735_p2[53:34]}};

assign z_22_fu_1779_p2 = (z_21_fu_1749_p4 + zext_ln254_7_fu_1775_p1);

assign z_24_fu_1969_p4 = {{add_ln254_16_fu_1955_p2[53:34]}};

assign z_25_fu_1999_p2 = (z_24_fu_1969_p4 + zext_ln254_8_fu_1995_p1);

assign z_27_fu_2189_p4 = {{add_ln254_18_fu_2175_p2[53:34]}};

assign z_28_fu_2219_p2 = (z_27_fu_2189_p4 + zext_ln254_9_fu_2215_p1);

assign z_30_fu_2409_p4 = {{add_ln254_20_fu_2395_p2[53:34]}};

assign z_31_fu_2439_p2 = (z_30_fu_2409_p4 + zext_ln254_10_fu_2435_p1);

assign z_33_fu_2629_p4 = {{add_ln254_22_fu_2615_p2[53:34]}};

assign z_34_fu_2659_p2 = (z_33_fu_2629_p4 + zext_ln254_11_fu_2655_p1);

assign z_36_fu_2849_p4 = {{add_ln254_24_fu_2835_p2[53:34]}};

assign z_37_fu_2879_p2 = (z_36_fu_2849_p4 + zext_ln254_12_fu_2875_p1);

assign z_39_fu_3069_p4 = {{add_ln254_26_fu_3055_p2[53:34]}};

assign z_3_fu_429_p4 = {{add_ln254_2_fu_415_p2[53:34]}};

assign z_40_fu_3099_p2 = (z_39_fu_3069_p4 + zext_ln254_13_fu_3095_p1);

assign z_42_fu_3289_p4 = {{add_ln254_28_fu_3275_p2[53:34]}};

assign z_43_fu_3319_p2 = (z_42_fu_3289_p4 + zext_ln254_14_fu_3315_p1);

assign z_45_fu_3509_p4 = {{add_ln254_30_fu_3495_p2[53:34]}};

assign z_46_fu_3539_p2 = (z_45_fu_3509_p4 + zext_ln254_15_fu_3535_p1);

assign z_48_fu_327_p3 = ((or_ln254_1_fu_321_p2[0:0] == 1'b1) ? select_ln254_fu_313_p3 : z_1_fu_239_p2);

assign z_49_fu_547_p3 = ((or_ln254_3_fu_541_p2[0:0] == 1'b1) ? select_ln254_2_fu_533_p3 : z_4_fu_459_p2);

assign z_4_fu_459_p2 = (z_3_fu_429_p4 + zext_ln254_1_fu_455_p1);

assign z_50_fu_767_p3 = ((or_ln254_5_fu_761_p2[0:0] == 1'b1) ? select_ln254_4_fu_753_p3 : z_7_fu_679_p2);

assign z_51_fu_987_p3 = ((or_ln254_7_fu_981_p2[0:0] == 1'b1) ? select_ln254_6_fu_973_p3 : z_10_fu_899_p2);

assign z_52_fu_1207_p3 = ((or_ln254_9_fu_1201_p2[0:0] == 1'b1) ? select_ln254_8_fu_1193_p3 : z_13_fu_1119_p2);

assign z_53_fu_1427_p3 = ((or_ln254_11_fu_1421_p2[0:0] == 1'b1) ? select_ln254_10_fu_1413_p3 : z_16_fu_1339_p2);

assign z_54_fu_1647_p3 = ((or_ln254_13_fu_1641_p2[0:0] == 1'b1) ? select_ln254_12_fu_1633_p3 : z_19_fu_1559_p2);

assign z_55_fu_1867_p3 = ((or_ln254_15_fu_1861_p2[0:0] == 1'b1) ? select_ln254_14_fu_1853_p3 : z_22_fu_1779_p2);

assign z_56_fu_2087_p3 = ((or_ln254_17_fu_2081_p2[0:0] == 1'b1) ? select_ln254_16_fu_2073_p3 : z_25_fu_1999_p2);

assign z_57_fu_2307_p3 = ((or_ln254_19_fu_2301_p2[0:0] == 1'b1) ? select_ln254_18_fu_2293_p3 : z_28_fu_2219_p2);

assign z_58_fu_2527_p3 = ((or_ln254_21_fu_2521_p2[0:0] == 1'b1) ? select_ln254_20_fu_2513_p3 : z_31_fu_2439_p2);

assign z_59_fu_2747_p3 = ((or_ln254_23_fu_2741_p2[0:0] == 1'b1) ? select_ln254_22_fu_2733_p3 : z_34_fu_2659_p2);

assign z_60_fu_2967_p3 = ((or_ln254_25_fu_2961_p2[0:0] == 1'b1) ? select_ln254_24_fu_2953_p3 : z_37_fu_2879_p2);

assign z_61_fu_3187_p3 = ((or_ln254_27_fu_3181_p2[0:0] == 1'b1) ? select_ln254_26_fu_3173_p3 : z_40_fu_3099_p2);

assign z_62_fu_3407_p3 = ((or_ln254_29_fu_3401_p2[0:0] == 1'b1) ? select_ln254_28_fu_3393_p3 : z_43_fu_3319_p2);

assign z_63_fu_3627_p3 = ((or_ln254_31_fu_3621_p2[0:0] == 1'b1) ? select_ln254_30_fu_3613_p3 : z_46_fu_3539_p2);

assign z_6_fu_649_p4 = {{add_ln254_4_fu_635_p2[53:34]}};

assign z_7_fu_679_p2 = (z_6_fu_649_p4 + zext_ln254_2_fu_675_p1);

assign z_9_fu_869_p4 = {{add_ln254_6_fu_855_p2[53:34]}};

assign z_fu_209_p4 = {{add_ln254_fu_195_p2[53:34]}};

assign zext_ln251_10_fu_3722_p1 = v_out_10_reg_3864;

assign zext_ln251_11_fu_3725_p1 = v_out_11_reg_3869;

assign zext_ln251_12_fu_3728_p1 = v_out_12_reg_3874;

assign zext_ln251_13_fu_3731_p1 = v_out_13_reg_3879;

assign zext_ln251_14_fu_3734_p1 = v_out_14_reg_3884;

assign zext_ln251_1_fu_3695_p1 = v_out_1_reg_3819;

assign zext_ln251_2_fu_3698_p1 = v_out_2_reg_3824;

assign zext_ln251_3_fu_3701_p1 = v_out_3_reg_3829;

assign zext_ln251_4_fu_3704_p1 = v_out_4_reg_3834;

assign zext_ln251_5_fu_3707_p1 = v_out_5_reg_3839;

assign zext_ln251_6_fu_3710_p1 = v_out_6_reg_3844;

assign zext_ln251_7_fu_3713_p1 = v_out_7_reg_3849;

assign zext_ln251_8_fu_3716_p1 = v_out_8_reg_3854;

assign zext_ln251_9_fu_3719_p1 = v_out_9_reg_3859;

assign zext_ln251_fu_3692_p1 = v_out_reg_3814;

assign zext_ln254_10_fu_2435_p1 = tmp_82_fu_2419_p3;

assign zext_ln254_11_fu_2655_p1 = tmp_90_fu_2639_p3;

assign zext_ln254_12_fu_2875_p1 = tmp_98_fu_2859_p3;

assign zext_ln254_13_fu_3095_p1 = tmp_106_fu_3079_p3;

assign zext_ln254_14_fu_3315_p1 = tmp_114_fu_3299_p3;

assign zext_ln254_15_fu_3535_p1 = tmp_122_fu_3519_p3;

assign zext_ln254_1_fu_455_p1 = tmp_10_fu_439_p3;

assign zext_ln254_2_fu_675_p1 = tmp_18_fu_659_p3;

assign zext_ln254_3_fu_895_p1 = tmp_26_fu_879_p3;

assign zext_ln254_4_fu_1115_p1 = tmp_34_fu_1099_p3;

assign zext_ln254_5_fu_1335_p1 = tmp_42_fu_1319_p3;

assign zext_ln254_6_fu_1555_p1 = tmp_50_fu_1539_p3;

assign zext_ln254_7_fu_1775_p1 = tmp_58_fu_1759_p3;

assign zext_ln254_8_fu_1995_p1 = tmp_66_fu_1979_p3;

assign zext_ln254_9_fu_2215_p1 = tmp_74_fu_2199_p3;

assign zext_ln254_fu_235_p1 = tmp_3_fu_219_p3;

endmodule //top_kernel_k4_postprocess
