// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_stage_gaussian (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        equalized_stream_dout,
        equalized_stream_empty_n,
        equalized_stream_read,
        equalized_stream_num_data_valid,
        equalized_stream_fifo_cap,
        gaussian_stream_din,
        gaussian_stream_full_n,
        gaussian_stream_write,
        gaussian_stream_num_data_valid,
        gaussian_stream_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] equalized_stream_dout;
input   equalized_stream_empty_n;
output   equalized_stream_read;
input  [7:0] equalized_stream_num_data_valid;
input  [7:0] equalized_stream_fifo_cap;
output  [15:0] gaussian_stream_din;
input   gaussian_stream_full_n;
output   gaussian_stream_write;
input  [31:0] gaussian_stream_num_data_valid;
input  [31:0] gaussian_stream_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    grid_ce0;
wire   [15:0] grid_q0;
reg    grid_ce1;
reg    grid_we1;
reg    grid_1_ce0;
wire   [15:0] grid_1_q0;
reg    grid_1_ce1;
reg    grid_1_we1;
reg    grid_2_ce0;
wire   [15:0] grid_2_q0;
reg    grid_2_ce1;
reg    grid_2_we1;
reg    grid_3_ce0;
wire   [15:0] grid_3_q0;
reg    grid_3_ce1;
reg    grid_3_we1;
reg    grid_4_ce0;
wire   [15:0] grid_4_q0;
reg    grid_4_ce1;
reg    grid_4_we1;
reg    grid_5_ce0;
wire   [15:0] grid_5_q0;
reg    grid_5_ce1;
reg    grid_5_we1;
reg    grid_6_ce0;
wire   [15:0] grid_6_q0;
reg    grid_6_ce1;
reg    grid_6_we1;
reg    grid_7_ce0;
wire   [15:0] grid_7_q0;
reg    grid_7_ce1;
reg    grid_7_we1;
reg    grid_8_ce0;
wire   [15:0] grid_8_q0;
reg    grid_8_ce1;
reg    grid_8_we1;
reg    grid_9_ce0;
wire   [15:0] grid_9_q0;
reg    grid_9_ce1;
reg    grid_9_we1;
reg    grid_10_ce0;
wire   [15:0] grid_10_q0;
reg    grid_10_ce1;
reg    grid_10_we1;
reg    grid_11_ce0;
wire   [15:0] grid_11_q0;
reg    grid_11_ce1;
reg    grid_11_we1;
reg    grid_12_ce0;
wire   [15:0] grid_12_q0;
reg    grid_12_ce1;
reg    grid_12_we1;
reg    grid_13_ce0;
wire   [15:0] grid_13_q0;
reg    grid_13_ce1;
reg    grid_13_we1;
reg    grid_14_ce0;
wire   [15:0] grid_14_q0;
reg    grid_14_ce1;
reg    grid_14_we1;
reg    grid_15_ce0;
wire   [15:0] grid_15_q0;
reg    grid_15_ce1;
reg    grid_15_we1;
reg    grid_16_ce0;
wire   [15:0] grid_16_q0;
reg    grid_16_ce1;
reg    grid_16_we1;
reg    grid_17_ce0;
wire   [15:0] grid_17_q0;
reg    grid_17_ce1;
reg    grid_17_we1;
reg    grid_18_ce0;
wire   [15:0] grid_18_q0;
reg    grid_18_ce1;
reg    grid_18_we1;
reg    grid_19_ce0;
wire   [15:0] grid_19_q0;
reg    grid_19_ce1;
reg    grid_19_we1;
reg    grid_20_ce0;
wire   [15:0] grid_20_q0;
reg    grid_20_ce1;
reg    grid_20_we1;
reg    grid_21_ce0;
wire   [15:0] grid_21_q0;
reg    grid_21_ce1;
reg    grid_21_we1;
reg    grid_22_ce0;
wire   [15:0] grid_22_q0;
reg    grid_22_ce1;
reg    grid_22_we1;
reg    grid_23_ce0;
wire   [15:0] grid_23_q0;
reg    grid_23_ce1;
reg    grid_23_we1;
reg    grid_24_ce0;
wire   [15:0] grid_24_q0;
reg    grid_24_ce1;
reg    grid_24_we1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_done;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_idle;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_ready;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_equalized_stream_read;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_d1;
wire   [7:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_address1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_ce1;
wire    grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_we1;
wire   [15:0] grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_d1;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_idle;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_ready;
wire   [15:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_gaussian_stream_din;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_gaussian_stream_write;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_1_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_1_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_2_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_2_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_3_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_3_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_4_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_4_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_5_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_5_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_6_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_6_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_7_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_7_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_8_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_8_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_9_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_9_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_10_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_10_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_11_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_11_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_12_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_12_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_13_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_13_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_14_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_14_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_15_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_15_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_16_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_16_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_17_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_17_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_18_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_18_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_19_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_19_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_20_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_20_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_21_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_21_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_22_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_22_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_23_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_23_ce0;
wire   [7:0] grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_24_address0;
wire    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_24_ce0;
reg    grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start_reg;
reg    ap_block_state1_ignore_call52;
wire    ap_CS_fsm_state2;
reg    grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start_reg = 1'b0;
#0 grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start_reg = 1'b0;
end

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_address0),
    .ce0(grid_ce0),
    .q0(grid_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_address1),
    .ce1(grid_ce1),
    .we1(grid_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_1_address0),
    .ce0(grid_1_ce0),
    .q0(grid_1_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_address1),
    .ce1(grid_1_ce1),
    .we1(grid_1_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_2_address0),
    .ce0(grid_2_ce0),
    .q0(grid_2_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_address1),
    .ce1(grid_2_ce1),
    .we1(grid_2_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_3_address0),
    .ce0(grid_3_ce0),
    .q0(grid_3_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_address1),
    .ce1(grid_3_ce1),
    .we1(grid_3_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_4_address0),
    .ce0(grid_4_ce0),
    .q0(grid_4_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_address1),
    .ce1(grid_4_ce1),
    .we1(grid_4_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_5_address0),
    .ce0(grid_5_ce0),
    .q0(grid_5_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_address1),
    .ce1(grid_5_ce1),
    .we1(grid_5_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_6_address0),
    .ce0(grid_6_ce0),
    .q0(grid_6_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_address1),
    .ce1(grid_6_ce1),
    .we1(grid_6_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_7_address0),
    .ce0(grid_7_ce0),
    .q0(grid_7_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_address1),
    .ce1(grid_7_ce1),
    .we1(grid_7_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_8_address0),
    .ce0(grid_8_ce0),
    .q0(grid_8_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_address1),
    .ce1(grid_8_ce1),
    .we1(grid_8_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_9_address0),
    .ce0(grid_9_ce0),
    .q0(grid_9_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_address1),
    .ce1(grid_9_ce1),
    .we1(grid_9_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_10_address0),
    .ce0(grid_10_ce0),
    .q0(grid_10_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_address1),
    .ce1(grid_10_ce1),
    .we1(grid_10_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_11_address0),
    .ce0(grid_11_ce0),
    .q0(grid_11_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_address1),
    .ce1(grid_11_ce1),
    .we1(grid_11_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_12_address0),
    .ce0(grid_12_ce0),
    .q0(grid_12_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_address1),
    .ce1(grid_12_ce1),
    .we1(grid_12_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_13_address0),
    .ce0(grid_13_ce0),
    .q0(grid_13_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_address1),
    .ce1(grid_13_ce1),
    .we1(grid_13_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_14_address0),
    .ce0(grid_14_ce0),
    .q0(grid_14_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_address1),
    .ce1(grid_14_ce1),
    .we1(grid_14_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_15_address0),
    .ce0(grid_15_ce0),
    .q0(grid_15_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_address1),
    .ce1(grid_15_ce1),
    .we1(grid_15_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_16_address0),
    .ce0(grid_16_ce0),
    .q0(grid_16_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_address1),
    .ce1(grid_16_ce1),
    .we1(grid_16_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_17_address0),
    .ce0(grid_17_ce0),
    .q0(grid_17_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_address1),
    .ce1(grid_17_ce1),
    .we1(grid_17_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_18_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_18_address0),
    .ce0(grid_18_ce0),
    .q0(grid_18_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_address1),
    .ce1(grid_18_ce1),
    .we1(grid_18_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_19_address0),
    .ce0(grid_19_ce0),
    .q0(grid_19_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_address1),
    .ce1(grid_19_ce1),
    .we1(grid_19_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_20_address0),
    .ce0(grid_20_ce0),
    .q0(grid_20_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_address1),
    .ce1(grid_20_ce1),
    .we1(grid_20_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_21_address0),
    .ce0(grid_21_ce0),
    .q0(grid_21_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_address1),
    .ce1(grid_21_ce1),
    .we1(grid_21_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_22_address0),
    .ce0(grid_22_ce0),
    .q0(grid_22_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_address1),
    .ce1(grid_22_ce1),
    .we1(grid_22_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_23_address0),
    .ce0(grid_23_ce0),
    .q0(grid_23_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_address1),
    .ce1(grid_23_ce1),
    .we1(grid_23_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_d1)
);

top_kernel_stage_gaussian_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 169 ),
    .AddressWidth( 8 ))
grid_24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_24_address0),
    .ce0(grid_24_ce0),
    .q0(grid_24_q0),
    .address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_address1),
    .ce1(grid_24_ce1),
    .we1(grid_24_we1),
    .d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_d1)
);

top_kernel_stage_gaussian_Pipeline_READ_IN grp_stage_gaussian_Pipeline_READ_IN_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start),
    .ap_done(grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_done),
    .ap_idle(grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_idle),
    .ap_ready(grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_ready),
    .equalized_stream_dout(equalized_stream_dout),
    .equalized_stream_empty_n(equalized_stream_empty_n),
    .equalized_stream_read(grp_stage_gaussian_Pipeline_READ_IN_fu_130_equalized_stream_read),
    .equalized_stream_num_data_valid(8'd0),
    .equalized_stream_fifo_cap(8'd0),
    .grid_24_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_address1),
    .grid_24_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_ce1),
    .grid_24_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_we1),
    .grid_24_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_d1),
    .grid_23_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_address1),
    .grid_23_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_ce1),
    .grid_23_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_we1),
    .grid_23_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_d1),
    .grid_22_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_address1),
    .grid_22_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_ce1),
    .grid_22_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_we1),
    .grid_22_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_d1),
    .grid_21_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_address1),
    .grid_21_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_ce1),
    .grid_21_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_we1),
    .grid_21_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_d1),
    .grid_20_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_address1),
    .grid_20_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_ce1),
    .grid_20_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_we1),
    .grid_20_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_d1),
    .grid_19_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_address1),
    .grid_19_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_ce1),
    .grid_19_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_we1),
    .grid_19_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_d1),
    .grid_18_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_address1),
    .grid_18_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_ce1),
    .grid_18_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_we1),
    .grid_18_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_d1),
    .grid_17_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_address1),
    .grid_17_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_ce1),
    .grid_17_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_we1),
    .grid_17_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_d1),
    .grid_16_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_address1),
    .grid_16_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_ce1),
    .grid_16_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_we1),
    .grid_16_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_d1),
    .grid_15_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_address1),
    .grid_15_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_ce1),
    .grid_15_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_we1),
    .grid_15_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_d1),
    .grid_14_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_address1),
    .grid_14_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_ce1),
    .grid_14_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_we1),
    .grid_14_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_d1),
    .grid_13_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_address1),
    .grid_13_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_ce1),
    .grid_13_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_we1),
    .grid_13_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_d1),
    .grid_12_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_address1),
    .grid_12_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_ce1),
    .grid_12_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_we1),
    .grid_12_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_d1),
    .grid_11_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_address1),
    .grid_11_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_ce1),
    .grid_11_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_we1),
    .grid_11_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_d1),
    .grid_10_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_address1),
    .grid_10_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_ce1),
    .grid_10_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_we1),
    .grid_10_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_d1),
    .grid_9_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_address1),
    .grid_9_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_ce1),
    .grid_9_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_we1),
    .grid_9_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_d1),
    .grid_8_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_address1),
    .grid_8_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_ce1),
    .grid_8_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_we1),
    .grid_8_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_d1),
    .grid_7_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_address1),
    .grid_7_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_ce1),
    .grid_7_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_we1),
    .grid_7_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_d1),
    .grid_6_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_address1),
    .grid_6_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_ce1),
    .grid_6_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_we1),
    .grid_6_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_d1),
    .grid_5_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_address1),
    .grid_5_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_ce1),
    .grid_5_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_we1),
    .grid_5_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_d1),
    .grid_4_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_address1),
    .grid_4_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_ce1),
    .grid_4_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_we1),
    .grid_4_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_d1),
    .grid_3_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_address1),
    .grid_3_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_ce1),
    .grid_3_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_we1),
    .grid_3_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_d1),
    .grid_2_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_address1),
    .grid_2_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_ce1),
    .grid_2_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_we1),
    .grid_2_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_d1),
    .grid_1_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_address1),
    .grid_1_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_ce1),
    .grid_1_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_we1),
    .grid_1_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_d1),
    .grid_address1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_address1),
    .grid_ce1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_ce1),
    .grid_we1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_we1),
    .grid_d1(grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_d1)
);

top_kernel_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1 grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start),
    .ap_done(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done),
    .ap_idle(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_idle),
    .ap_ready(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_ready),
    .gaussian_stream_din(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_gaussian_stream_din),
    .gaussian_stream_full_n(gaussian_stream_full_n),
    .gaussian_stream_write(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_gaussian_stream_write),
    .gaussian_stream_num_data_valid(gaussian_stream_num_data_valid),
    .gaussian_stream_fifo_cap(gaussian_stream_fifo_cap),
    .grid_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_address0),
    .grid_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_ce0),
    .grid_q0(grid_q0),
    .grid_1_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_1_address0),
    .grid_1_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_1_ce0),
    .grid_1_q0(grid_1_q0),
    .grid_2_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_2_address0),
    .grid_2_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_2_ce0),
    .grid_2_q0(grid_2_q0),
    .grid_3_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_3_address0),
    .grid_3_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_3_ce0),
    .grid_3_q0(grid_3_q0),
    .grid_4_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_4_address0),
    .grid_4_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_4_ce0),
    .grid_4_q0(grid_4_q0),
    .grid_5_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_5_address0),
    .grid_5_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_5_ce0),
    .grid_5_q0(grid_5_q0),
    .grid_6_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_6_address0),
    .grid_6_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_6_ce0),
    .grid_6_q0(grid_6_q0),
    .grid_7_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_7_address0),
    .grid_7_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_7_ce0),
    .grid_7_q0(grid_7_q0),
    .grid_8_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_8_address0),
    .grid_8_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_8_ce0),
    .grid_8_q0(grid_8_q0),
    .grid_9_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_9_address0),
    .grid_9_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_9_ce0),
    .grid_9_q0(grid_9_q0),
    .grid_10_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_10_address0),
    .grid_10_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_10_ce0),
    .grid_10_q0(grid_10_q0),
    .grid_11_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_11_address0),
    .grid_11_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_11_ce0),
    .grid_11_q0(grid_11_q0),
    .grid_12_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_12_address0),
    .grid_12_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_12_ce0),
    .grid_12_q0(grid_12_q0),
    .grid_13_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_13_address0),
    .grid_13_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_13_ce0),
    .grid_13_q0(grid_13_q0),
    .grid_14_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_14_address0),
    .grid_14_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_14_ce0),
    .grid_14_q0(grid_14_q0),
    .grid_15_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_15_address0),
    .grid_15_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_15_ce0),
    .grid_15_q0(grid_15_q0),
    .grid_16_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_16_address0),
    .grid_16_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_16_ce0),
    .grid_16_q0(grid_16_q0),
    .grid_17_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_17_address0),
    .grid_17_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_17_ce0),
    .grid_17_q0(grid_17_q0),
    .grid_18_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_18_address0),
    .grid_18_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_18_ce0),
    .grid_18_q0(grid_18_q0),
    .grid_19_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_19_address0),
    .grid_19_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_19_ce0),
    .grid_19_q0(grid_19_q0),
    .grid_20_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_20_address0),
    .grid_20_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_20_ce0),
    .grid_20_q0(grid_20_q0),
    .grid_21_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_21_address0),
    .grid_21_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_21_ce0),
    .grid_21_q0(grid_21_q0),
    .grid_22_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_22_address0),
    .grid_22_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_22_ce0),
    .grid_22_q0(grid_22_q0),
    .grid_23_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_23_address0),
    .grid_23_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_23_ce0),
    .grid_23_q0(grid_23_q0),
    .grid_24_address0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_24_address0),
    .grid_24_ce0(grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_24_ce0),
    .grid_24_q0(grid_24_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_ready == 1'b1)) begin
            grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call52) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_ready == 1'b1)) begin
            grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_10_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_10_ce0;
    end else begin
        grid_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_10_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_ce1;
    end else begin
        grid_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_10_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_10_we1;
    end else begin
        grid_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_11_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_11_ce0;
    end else begin
        grid_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_11_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_ce1;
    end else begin
        grid_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_11_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_11_we1;
    end else begin
        grid_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_12_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_12_ce0;
    end else begin
        grid_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_12_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_ce1;
    end else begin
        grid_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_12_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_12_we1;
    end else begin
        grid_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_13_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_13_ce0;
    end else begin
        grid_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_13_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_ce1;
    end else begin
        grid_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_13_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_13_we1;
    end else begin
        grid_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_14_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_14_ce0;
    end else begin
        grid_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_14_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_ce1;
    end else begin
        grid_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_14_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_14_we1;
    end else begin
        grid_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_15_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_15_ce0;
    end else begin
        grid_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_15_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_ce1;
    end else begin
        grid_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_15_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_15_we1;
    end else begin
        grid_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_16_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_16_ce0;
    end else begin
        grid_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_16_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_ce1;
    end else begin
        grid_16_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_16_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_16_we1;
    end else begin
        grid_16_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_17_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_17_ce0;
    end else begin
        grid_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_17_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_ce1;
    end else begin
        grid_17_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_17_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_17_we1;
    end else begin
        grid_17_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_18_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_18_ce0;
    end else begin
        grid_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_18_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_ce1;
    end else begin
        grid_18_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_18_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_18_we1;
    end else begin
        grid_18_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_19_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_19_ce0;
    end else begin
        grid_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_19_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_ce1;
    end else begin
        grid_19_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_19_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_19_we1;
    end else begin
        grid_19_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_1_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_1_ce0;
    end else begin
        grid_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_1_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_ce1;
    end else begin
        grid_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_1_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_1_we1;
    end else begin
        grid_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_20_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_20_ce0;
    end else begin
        grid_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_20_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_ce1;
    end else begin
        grid_20_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_20_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_20_we1;
    end else begin
        grid_20_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_21_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_21_ce0;
    end else begin
        grid_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_21_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_ce1;
    end else begin
        grid_21_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_21_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_21_we1;
    end else begin
        grid_21_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_22_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_22_ce0;
    end else begin
        grid_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_22_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_ce1;
    end else begin
        grid_22_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_22_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_22_we1;
    end else begin
        grid_22_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_23_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_23_ce0;
    end else begin
        grid_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_23_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_ce1;
    end else begin
        grid_23_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_23_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_23_we1;
    end else begin
        grid_23_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_24_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_24_ce0;
    end else begin
        grid_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_24_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_ce1;
    end else begin
        grid_24_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_24_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_24_we1;
    end else begin
        grid_24_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_2_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_2_ce0;
    end else begin
        grid_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_2_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_ce1;
    end else begin
        grid_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_2_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_2_we1;
    end else begin
        grid_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_3_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_3_ce0;
    end else begin
        grid_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_3_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_ce1;
    end else begin
        grid_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_3_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_3_we1;
    end else begin
        grid_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_4_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_4_ce0;
    end else begin
        grid_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_4_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_ce1;
    end else begin
        grid_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_4_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_4_we1;
    end else begin
        grid_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_5_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_5_ce0;
    end else begin
        grid_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_5_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_ce1;
    end else begin
        grid_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_5_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_5_we1;
    end else begin
        grid_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_6_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_6_ce0;
    end else begin
        grid_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_6_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_ce1;
    end else begin
        grid_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_6_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_6_we1;
    end else begin
        grid_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_7_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_7_ce0;
    end else begin
        grid_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_7_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_ce1;
    end else begin
        grid_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_7_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_7_we1;
    end else begin
        grid_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_8_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_8_ce0;
    end else begin
        grid_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_8_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_ce1;
    end else begin
        grid_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_8_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_8_we1;
    end else begin
        grid_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_9_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_9_ce0;
    end else begin
        grid_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_9_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_ce1;
    end else begin
        grid_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_9_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_9_we1;
    end else begin
        grid_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_ce0 = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_grid_ce0;
    end else begin
        grid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_ce1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_ce1;
    end else begin
        grid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_we1 = grp_stage_gaussian_Pipeline_READ_IN_fu_130_grid_we1;
    end else begin
        grid_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call52 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign equalized_stream_read = grp_stage_gaussian_Pipeline_READ_IN_fu_130_equalized_stream_read;

assign gaussian_stream_din = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_gaussian_stream_din;

assign gaussian_stream_write = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_gaussian_stream_write;

assign grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start = grp_stage_gaussian_Pipeline_GAUSSIAN_OUT_VITIS_LOOP_144_1_fu_186_ap_start_reg;

assign grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start = grp_stage_gaussian_Pipeline_READ_IN_fu_130_ap_start_reg;

assign start_out = real_start;

endmodule //top_kernel_stage_gaussian
