-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    C_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_we0 : OUT STD_LOGIC;
    C_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.276500,HLS_SYN_LAT=78658,HLS_SYN_TPT=none,HLS_SYN_MEM=22,HLS_SYN_DSP=0,HLS_SYN_FF=3658,HLS_SYN_LUT=3702,HLS_VERSION=2025_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv25_4000 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_ce0 : STD_LOGIC;
    signal tmp_we0 : STD_LOGIC;
    signal tmp_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_4_fu_172_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_4_reg_374 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal denom_1_fu_250_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal denom_1_reg_387 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln33_fu_274_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln33_reg_395 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal scale_fu_343_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal scale_reg_401 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_done : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_idle : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_ready : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_p_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_p_out_ap_vld : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_done : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_idle : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_ready : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_we0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_d0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_done : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_idle : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_ready : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out_ap_vld : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_done : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_idle : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_ready : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_we0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_d0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_ce0 : STD_LOGIC;
    signal grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln11_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln33_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal i_fu_96 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln11_fu_162_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal j_fu_108 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln33_fu_268_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln11_fu_168_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln22_fu_194_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln22_fu_198_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1_fu_204_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_216_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln22_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_1_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_242_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal denom_fu_212_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln_fu_287_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sub_ln44_fu_303_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_5_fu_309_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln44_fu_319_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_6_fu_329_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_295_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln44_1_fu_323_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln44_1_fu_339_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_top_kernel_Pipeline_VITIS_LOOP_16_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln28 : IN STD_LOGIC_VECTOR (13 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;


    component top_kernel_top_kernel_Pipeline_VITIS_LOOP_26_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln28 : IN STD_LOGIC_VECTOR (13 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        conv_i362 : IN STD_LOGIC_VECTOR (23 downto 0);
        tmp_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_we0 : OUT STD_LOGIC;
        tmp_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_top_kernel_Pipeline_VITIS_LOOP_38_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln33 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        tmp_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_top_kernel_Pipeline_VITIS_LOOP_48_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln33 : IN STD_LOGIC_VECTOR (5 downto 0);
        C_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        C_ce0 : OUT STD_LOGIC;
        C_we0 : OUT STD_LOGIC;
        C_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
        conv7_i : IN STD_LOGIC_VECTOR (16 downto 0);
        tmp_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        tmp_ce0 : OUT STD_LOGIC;
        tmp_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_tmp_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    tmp_U : component top_kernel_tmp_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tmp_address0,
        ce0 => tmp_ce0,
        we0 => tmp_we0,
        d0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_d0,
        q0 => tmp_q0);

    grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112 : component top_kernel_top_kernel_Pipeline_VITIS_LOOP_16_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start,
        ap_done => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_done,
        ap_idle => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_idle,
        ap_ready => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_ready,
        zext_ln28 => tmp_4_reg_374,
        A_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_address0,
        A_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_ce0,
        A_q0 => A_q0,
        p_out => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_p_out,
        p_out_ap_vld => grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_p_out_ap_vld);

    grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120 : component top_kernel_top_kernel_Pipeline_VITIS_LOOP_26_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start,
        ap_done => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_done,
        ap_idle => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_idle,
        ap_ready => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_ready,
        zext_ln28 => tmp_4_reg_374,
        A_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_address0,
        A_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_ce0,
        A_q0 => A_q0,
        conv_i362 => denom_1_reg_387,
        tmp_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_address0,
        tmp_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_ce0,
        tmp_we0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_we0,
        tmp_d0 => grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_d0);

    grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130 : component top_kernel_top_kernel_Pipeline_VITIS_LOOP_38_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start,
        ap_done => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_done,
        ap_idle => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_idle,
        ap_ready => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_ready,
        zext_ln33 => trunc_ln33_reg_395,
        p_out => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out,
        p_out_ap_vld => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out_ap_vld,
        tmp_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_address0,
        tmp_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_ce0,
        tmp_q0 => tmp_q0);

    grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138 : component top_kernel_top_kernel_Pipeline_VITIS_LOOP_48_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start,
        ap_done => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_done,
        ap_idle => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_idle,
        ap_ready => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_ready,
        zext_ln33 => trunc_ln33_reg_395,
        C_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_address0,
        C_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_ce0,
        C_we0 => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_we0,
        C_d0 => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_d0,
        conv7_i => scale_reg_401,
        tmp_address0 => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_address0,
        tmp_ce0 => grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_ce0,
        tmp_q0 => tmp_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_156_p2 = ap_const_lv1_0))) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_ready = ap_const_logic_1)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln33_fu_262_p2 = ap_const_lv1_0))) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_ready = ap_const_logic_1)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_ready = ap_const_logic_1)) then 
                    grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_96 <= ap_const_lv9_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_156_p2 = ap_const_lv1_0))) then 
                i_fu_96 <= add_ln11_fu_162_p2;
            end if; 
        end if;
    end process;

    j_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_156_p2 = ap_const_lv1_1))) then 
                j_fu_108 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln33_fu_262_p2 = ap_const_lv1_0))) then 
                j_fu_108 <= add_ln33_fu_268_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                denom_1_reg_387 <= denom_1_fu_250_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                scale_reg_401 <= scale_fu_343_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    tmp_4_reg_374(13 downto 6) <= tmp_4_fu_172_p3(13 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                trunc_ln33_reg_395 <= trunc_ln33_fu_274_p1;
            end if;
        end if;
    end process;
    tmp_4_reg_374(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state6, grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_done, grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_done, grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_done, grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_done, icmp_ln11_fu_156_p2, ap_CS_fsm_state3, ap_CS_fsm_state5, icmp_ln33_fu_262_p2, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln11_fu_156_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln33_fu_262_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;

    A_address0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_address0, grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            A_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            A_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_address0;
        else 
            A_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    A_ce0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_ce0, grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            A_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            A_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_A_ce0;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_address0;
    C_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_ce0;
    C_d0 <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_d0;
    C_we0 <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_C_we0;
    add_ln11_fu_162_p2 <= std_logic_vector(unsigned(i_fu_96) + unsigned(ap_const_lv9_1));
    add_ln22_fu_198_p2 <= std_logic_vector(signed(sext_ln22_fu_194_p1) + signed(ap_const_lv25_4000));
    add_ln33_fu_268_p2 <= std_logic_vector(unsigned(j_fu_108) + unsigned(ap_const_lv7_1));
    and_ln22_fu_230_p2 <= (xor_ln22_fu_224_p2 and tmp_10_fu_216_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_done)
    begin
        if ((grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_done)
    begin
        if ((grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_done)
    begin
        if ((grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_done)
    begin
        if ((grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, icmp_ln33_fu_262_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln33_fu_262_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, icmp_ln33_fu_262_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln33_fu_262_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    denom_1_fu_250_p3 <= 
        select_ln22_fu_242_p3 when (xor_ln22_1_fu_236_p2(0) = '1') else 
        denom_fu_212_p1;
    denom_fu_212_p1 <= add_ln22_fu_198_p2(24 - 1 downto 0);
    grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start <= grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_ap_start_reg;
    grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start <= grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_ap_start_reg;
    grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start <= grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_ap_start_reg;
    grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_ap_start_reg;
    icmp_ln11_fu_156_p2 <= "1" when (i_fu_96 = ap_const_lv9_100) else "0";
    icmp_ln33_fu_262_p2 <= "1" when (j_fu_108 = ap_const_lv7_40) else "0";
    scale_fu_343_p3 <= 
        sub_ln44_1_fu_323_p2 when (tmp_11_fu_295_p3(0) = '1') else 
        zext_ln44_1_fu_339_p1;
    select_ln22_fu_242_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln22_fu_230_p2(0) = '1') else 
        ap_const_lv24_800000;
        sext_ln22_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_top_kernel_Pipeline_VITIS_LOOP_16_2_fu_112_p_out),25));

    shl_ln_fu_287_p3 <= (grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out & ap_const_lv14_0);
    sub_ln44_1_fu_323_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(zext_ln44_fu_319_p1));
    sub_ln44_fu_303_p2 <= std_logic_vector(unsigned(ap_const_lv38_0) - unsigned(shl_ln_fu_287_p3));
    tmp_10_fu_216_p3 <= add_ln22_fu_198_p2(23 downto 23);
    tmp_11_fu_295_p3 <= grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out(23 downto 23);
    tmp_1_fu_204_p3 <= add_ln22_fu_198_p2(24 downto 24);
    tmp_4_fu_172_p3 <= (trunc_ln11_fu_168_p1 & ap_const_lv6_0);
    tmp_5_fu_309_p4 <= sub_ln44_fu_303_p2(37 downto 22);
    tmp_6_fu_329_p4 <= grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_p_out(23 downto 8);

    tmp_address0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_address0, grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_address0, grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_address0, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            tmp_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            tmp_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_address0 <= grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_address0;
        else 
            tmp_address0 <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    tmp_ce0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_ce0, grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_ce0, grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            tmp_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_48_6_fu_138_tmp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            tmp_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_38_5_fu_130_tmp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_ce0 <= grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_ce0;
        else 
            tmp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tmp_we0_assign_proc : process(grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tmp_we0 <= grp_top_kernel_Pipeline_VITIS_LOOP_26_3_fu_120_tmp_we0;
        else 
            tmp_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln11_fu_168_p1 <= i_fu_96(8 - 1 downto 0);
    trunc_ln33_fu_274_p1 <= j_fu_108(6 - 1 downto 0);
    xor_ln22_1_fu_236_p2 <= (tmp_1_fu_204_p3 xor tmp_10_fu_216_p3);
    xor_ln22_fu_224_p2 <= (tmp_1_fu_204_p3 xor ap_const_lv1_1);
    zext_ln44_1_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_329_p4),17));
    zext_ln44_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_309_p4),17));
end behav;
