

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_145_1_proc_U0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k1_contrast_U0"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k1_contrast_U0.k1_contrast_stream_ap_fixed_0_stream_ap_fixed_16_8_5_3_0_0_lb_1_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k1_contrast_U0.k1_contrast_stream_ap_fixed_0_stream_ap_fixed_16_8_5_3_0_0_lb_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k1_contrast_U0.flow_control_loop_pipe_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k2_erosion_U0"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_erosion_U0.k2_erosion_stream_ap_fixed_0_stream_ap_fixed_16_8_5_3_0_0_lb_3_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_erosion_U0.k2_erosion_stream_ap_fixed_0_stream_ap_fixed_16_8_5_3_0_0_lb_2_U"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_erosion_U0.k2_erosion_stream_ap_fixed_0_stream_ap_fixed_16_8_5_3_0_0_lb_1_U"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_erosion_U0.k2_erosion_stream_ap_fixed_0_stream_ap_fixed_16_8_5_3_0_0_lb_U"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k2_erosion_U0.flow_control_loop_pipe_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k3_dilation_U0"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dilation_U0.k3_dilation_stream_stream_stream_ap_fixed_16_8_5_3_0_0_lb_3_U"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dilation_U0.k3_dilation_stream_stream_stream_ap_fixed_16_8_5_3_0_0_lb_2_U"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dilation_U0.k3_dilation_stream_stream_stream_ap_fixed_16_8_5_3_0_0_lb_1_U"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dilation_U0.k3_dilation_stream_stream_stream_ap_fixed_16_8_5_3_0_0_lb_U"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k3_dilation_U0.flow_control_loop_pipe_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k4_gradient_U0"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k4_gradient_U0.flow_control_loop_pipe_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k5_threshold_U0"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k5_threshold_U0.local_storage_U"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k5_threshold_U0.grp_k5_threshold_Pipeline_VITIS_LOOP_116_1_fu_102"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.k5_threshold_U0.grp_k5_threshold_Pipeline_VITIS_LOOP_116_1_fu_102.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.k5_threshold_U0.grp_k5_threshold_Pipeline_VITIS_LOOP_125_2_fu_111"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.k5_threshold_U0.grp_k5_threshold_Pipeline_VITIS_LOOP_125_2_fu_111.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_c_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_stream_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s2_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_dil_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_ero_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s4_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k5_threshold_U0_U"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k1_contrast_U0_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k2_erosion_U0_U"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k3_dilation_U0_U"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_k4_gradient_U0_U"}]}
set DependenceCheckSize 0
