// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_stage_morphology (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        bilateral_stream_dout,
        bilateral_stream_empty_n,
        bilateral_stream_read,
        bilateral_stream_num_data_valid,
        bilateral_stream_fifo_cap,
        morphology_stream_din,
        morphology_stream_full_n,
        morphology_stream_write,
        morphology_stream_num_data_valid,
        morphology_stream_fifo_cap
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [13:0] bilateral_stream_dout;
input   bilateral_stream_empty_n;
output   bilateral_stream_read;
input  [8:0] bilateral_stream_num_data_valid;
input  [8:0] bilateral_stream_fifo_cap;
output  [13:0] morphology_stream_din;
input   morphology_stream_full_n;
output   morphology_stream_write;
input  [31:0] morphology_stream_num_data_valid;
input  [31:0] morphology_stream_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bilateral_buf_ce0;
wire   [13:0] bilateral_buf_q0;
reg    bilateral_buf_ce1;
reg    bilateral_buf_we1;
reg    bilateral_buf_1_ce0;
wire   [13:0] bilateral_buf_1_q0;
reg    bilateral_buf_1_ce1;
reg    bilateral_buf_1_we1;
reg    bilateral_buf_2_ce0;
wire   [13:0] bilateral_buf_2_q0;
reg    bilateral_buf_2_ce1;
reg    bilateral_buf_2_we1;
reg    bilateral_buf_3_ce0;
wire   [13:0] bilateral_buf_3_q0;
reg    bilateral_buf_3_ce1;
reg    bilateral_buf_3_we1;
reg    bilateral_buf_4_ce0;
wire   [13:0] bilateral_buf_4_q0;
reg    bilateral_buf_4_ce1;
reg    bilateral_buf_4_we1;
reg    bilateral_buf_5_ce0;
wire   [13:0] bilateral_buf_5_q0;
reg    bilateral_buf_5_ce1;
reg    bilateral_buf_5_we1;
reg    bilateral_buf_6_ce0;
wire   [13:0] bilateral_buf_6_q0;
reg    bilateral_buf_6_ce1;
reg    bilateral_buf_6_we1;
reg    bilateral_buf_7_ce0;
wire   [13:0] bilateral_buf_7_q0;
reg    bilateral_buf_7_ce1;
reg    bilateral_buf_7_we1;
reg    bilateral_buf_8_ce0;
wire   [13:0] bilateral_buf_8_q0;
reg    bilateral_buf_8_ce1;
reg    bilateral_buf_8_we1;
reg    eroded_buf_ce0;
wire   [13:0] eroded_buf_q0;
reg    eroded_buf_ce1;
reg    eroded_buf_we1;
reg    eroded_buf_1_ce0;
wire   [13:0] eroded_buf_1_q0;
reg    eroded_buf_1_ce1;
reg    eroded_buf_1_we1;
reg    eroded_buf_2_ce0;
wire   [13:0] eroded_buf_2_q0;
reg    eroded_buf_2_ce1;
reg    eroded_buf_2_we1;
reg    eroded_buf_3_ce0;
wire   [13:0] eroded_buf_3_q0;
reg    eroded_buf_3_ce1;
reg    eroded_buf_3_we1;
reg    eroded_buf_4_ce0;
wire   [13:0] eroded_buf_4_q0;
reg    eroded_buf_4_ce1;
reg    eroded_buf_4_we1;
reg    eroded_buf_5_ce0;
wire   [13:0] eroded_buf_5_q0;
reg    eroded_buf_5_ce1;
reg    eroded_buf_5_we1;
reg    eroded_buf_6_ce0;
wire   [13:0] eroded_buf_6_q0;
reg    eroded_buf_6_ce1;
reg    eroded_buf_6_we1;
reg    eroded_buf_7_ce0;
wire   [13:0] eroded_buf_7_q0;
reg    eroded_buf_7_ce1;
reg    eroded_buf_7_we1;
reg    eroded_buf_8_ce0;
wire   [13:0] eroded_buf_8_q0;
reg    eroded_buf_8_ce1;
reg    eroded_buf_8_we1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_done;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_idle;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_ready;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_stream_read;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_d1;
wire   [8:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_address1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_ce1;
wire    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_we1;
wire   [13:0] grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_d1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_done;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_idle;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_ready;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_1_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_1_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_2_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_2_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_3_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_3_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_4_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_4_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_5_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_5_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_6_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_6_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_7_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_7_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_8_address0;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_8_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_d1;
wire   [8:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_address1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_ce1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_we1;
wire   [13:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_d1;
wire   [63:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_din0;
wire   [65:0] grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_din1;
wire    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_ce;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_idle;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_ready;
wire   [13:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_morphology_stream_din;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_morphology_stream_write;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_1_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_1_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_2_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_2_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_3_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_3_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_4_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_4_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_5_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_5_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_6_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_6_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_7_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_7_ce0;
wire   [8:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_8_address0;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_8_ce0;
wire   [63:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_din0;
wire   [65:0] grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_din1;
wire    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_ce;
reg    grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start_reg;
reg    ap_block_state1_ignore_call38;
wire    ap_CS_fsm_state2;
reg    grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [128:0] grp_fu_201_p2;
reg   [63:0] grp_fu_201_p0;
reg   [65:0] grp_fu_201_p1;
reg    grp_fu_201_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start_reg = 1'b0;
#0 grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start_reg = 1'b0;
#0 grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start_reg = 1'b0;
end

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_address0),
    .ce0(bilateral_buf_ce0),
    .q0(bilateral_buf_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_address1),
    .ce1(bilateral_buf_ce1),
    .we1(bilateral_buf_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_1_address0),
    .ce0(bilateral_buf_1_ce0),
    .q0(bilateral_buf_1_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_address1),
    .ce1(bilateral_buf_1_ce1),
    .we1(bilateral_buf_1_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_2_address0),
    .ce0(bilateral_buf_2_ce0),
    .q0(bilateral_buf_2_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_address1),
    .ce1(bilateral_buf_2_ce1),
    .we1(bilateral_buf_2_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_3_address0),
    .ce0(bilateral_buf_3_ce0),
    .q0(bilateral_buf_3_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_address1),
    .ce1(bilateral_buf_3_ce1),
    .we1(bilateral_buf_3_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_4_address0),
    .ce0(bilateral_buf_4_ce0),
    .q0(bilateral_buf_4_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_address1),
    .ce1(bilateral_buf_4_ce1),
    .we1(bilateral_buf_4_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_5_address0),
    .ce0(bilateral_buf_5_ce0),
    .q0(bilateral_buf_5_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_address1),
    .ce1(bilateral_buf_5_ce1),
    .we1(bilateral_buf_5_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_6_address0),
    .ce0(bilateral_buf_6_ce0),
    .q0(bilateral_buf_6_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_address1),
    .ce1(bilateral_buf_6_ce1),
    .we1(bilateral_buf_6_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_7_address0),
    .ce0(bilateral_buf_7_ce0),
    .q0(bilateral_buf_7_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_address1),
    .ce1(bilateral_buf_7_ce1),
    .we1(bilateral_buf_7_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
bilateral_buf_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_8_address0),
    .ce0(bilateral_buf_8_ce0),
    .q0(bilateral_buf_8_q0),
    .address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_address1),
    .ce1(bilateral_buf_8_ce1),
    .we1(bilateral_buf_8_we1),
    .d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_address0),
    .ce0(eroded_buf_ce0),
    .q0(eroded_buf_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_address1),
    .ce1(eroded_buf_ce1),
    .we1(eroded_buf_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_1_address0),
    .ce0(eroded_buf_1_ce0),
    .q0(eroded_buf_1_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_address1),
    .ce1(eroded_buf_1_ce1),
    .we1(eroded_buf_1_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_2_address0),
    .ce0(eroded_buf_2_ce0),
    .q0(eroded_buf_2_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_address1),
    .ce1(eroded_buf_2_ce1),
    .we1(eroded_buf_2_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_3_address0),
    .ce0(eroded_buf_3_ce0),
    .q0(eroded_buf_3_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_address1),
    .ce1(eroded_buf_3_ce1),
    .we1(eroded_buf_3_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_4_address0),
    .ce0(eroded_buf_4_ce0),
    .q0(eroded_buf_4_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_address1),
    .ce1(eroded_buf_4_ce1),
    .we1(eroded_buf_4_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_5_address0),
    .ce0(eroded_buf_5_ce0),
    .q0(eroded_buf_5_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_address1),
    .ce1(eroded_buf_5_ce1),
    .we1(eroded_buf_5_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_6_address0),
    .ce0(eroded_buf_6_ce0),
    .q0(eroded_buf_6_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_address1),
    .ce1(eroded_buf_6_ce1),
    .we1(eroded_buf_6_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_7_address0),
    .ce0(eroded_buf_7_ce0),
    .q0(eroded_buf_7_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_address1),
    .ce1(eroded_buf_7_ce1),
    .we1(eroded_buf_7_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_d1)
);

top_kernel_stage_bilateral_grid_RAM_2P_BRAM_1R1W #(
    .DataWidth( 14 ),
    .AddressRange( 484 ),
    .AddressWidth( 9 ))
eroded_buf_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_8_address0),
    .ce0(eroded_buf_8_ce0),
    .q0(eroded_buf_8_q0),
    .address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_address1),
    .ce1(eroded_buf_8_ce1),
    .we1(eroded_buf_8_we1),
    .d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_d1)
);

top_kernel_stage_morphology_Pipeline_READ_BILATERAL grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start),
    .ap_done(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_done),
    .ap_idle(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_idle),
    .ap_ready(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_ready),
    .bilateral_stream_dout(bilateral_stream_dout),
    .bilateral_stream_empty_n(bilateral_stream_empty_n),
    .bilateral_stream_read(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_stream_read),
    .bilateral_stream_num_data_valid(9'd0),
    .bilateral_stream_fifo_cap(9'd0),
    .bilateral_buf_8_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_address1),
    .bilateral_buf_8_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_ce1),
    .bilateral_buf_8_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_we1),
    .bilateral_buf_8_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_d1),
    .bilateral_buf_7_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_address1),
    .bilateral_buf_7_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_ce1),
    .bilateral_buf_7_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_we1),
    .bilateral_buf_7_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_d1),
    .bilateral_buf_6_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_address1),
    .bilateral_buf_6_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_ce1),
    .bilateral_buf_6_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_we1),
    .bilateral_buf_6_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_d1),
    .bilateral_buf_5_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_address1),
    .bilateral_buf_5_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_ce1),
    .bilateral_buf_5_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_we1),
    .bilateral_buf_5_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_d1),
    .bilateral_buf_4_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_address1),
    .bilateral_buf_4_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_ce1),
    .bilateral_buf_4_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_we1),
    .bilateral_buf_4_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_d1),
    .bilateral_buf_3_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_address1),
    .bilateral_buf_3_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_ce1),
    .bilateral_buf_3_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_we1),
    .bilateral_buf_3_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_d1),
    .bilateral_buf_2_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_address1),
    .bilateral_buf_2_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_ce1),
    .bilateral_buf_2_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_we1),
    .bilateral_buf_2_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_d1),
    .bilateral_buf_1_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_address1),
    .bilateral_buf_1_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_ce1),
    .bilateral_buf_1_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_we1),
    .bilateral_buf_1_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_d1),
    .bilateral_buf_address1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_address1),
    .bilateral_buf_ce1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_ce1),
    .bilateral_buf_we1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_we1),
    .bilateral_buf_d1(grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_d1)
);

top_kernel_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1 grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start),
    .ap_done(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_done),
    .ap_idle(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_idle),
    .ap_ready(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_ready),
    .bilateral_buf_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_address0),
    .bilateral_buf_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_ce0),
    .bilateral_buf_q0(bilateral_buf_q0),
    .bilateral_buf_1_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_1_address0),
    .bilateral_buf_1_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_1_ce0),
    .bilateral_buf_1_q0(bilateral_buf_1_q0),
    .bilateral_buf_2_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_2_address0),
    .bilateral_buf_2_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_2_ce0),
    .bilateral_buf_2_q0(bilateral_buf_2_q0),
    .bilateral_buf_3_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_3_address0),
    .bilateral_buf_3_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_3_ce0),
    .bilateral_buf_3_q0(bilateral_buf_3_q0),
    .bilateral_buf_4_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_4_address0),
    .bilateral_buf_4_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_4_ce0),
    .bilateral_buf_4_q0(bilateral_buf_4_q0),
    .bilateral_buf_5_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_5_address0),
    .bilateral_buf_5_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_5_ce0),
    .bilateral_buf_5_q0(bilateral_buf_5_q0),
    .bilateral_buf_6_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_6_address0),
    .bilateral_buf_6_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_6_ce0),
    .bilateral_buf_6_q0(bilateral_buf_6_q0),
    .bilateral_buf_7_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_7_address0),
    .bilateral_buf_7_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_7_ce0),
    .bilateral_buf_7_q0(bilateral_buf_7_q0),
    .bilateral_buf_8_address0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_8_address0),
    .bilateral_buf_8_ce0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_8_ce0),
    .bilateral_buf_8_q0(bilateral_buf_8_q0),
    .eroded_buf_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_address1),
    .eroded_buf_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_ce1),
    .eroded_buf_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_we1),
    .eroded_buf_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_d1),
    .eroded_buf_1_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_address1),
    .eroded_buf_1_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_ce1),
    .eroded_buf_1_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_we1),
    .eroded_buf_1_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_d1),
    .eroded_buf_2_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_address1),
    .eroded_buf_2_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_ce1),
    .eroded_buf_2_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_we1),
    .eroded_buf_2_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_d1),
    .eroded_buf_3_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_address1),
    .eroded_buf_3_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_ce1),
    .eroded_buf_3_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_we1),
    .eroded_buf_3_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_d1),
    .eroded_buf_4_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_address1),
    .eroded_buf_4_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_ce1),
    .eroded_buf_4_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_we1),
    .eroded_buf_4_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_d1),
    .eroded_buf_5_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_address1),
    .eroded_buf_5_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_ce1),
    .eroded_buf_5_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_we1),
    .eroded_buf_5_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_d1),
    .eroded_buf_6_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_address1),
    .eroded_buf_6_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_ce1),
    .eroded_buf_6_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_we1),
    .eroded_buf_6_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_d1),
    .eroded_buf_7_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_address1),
    .eroded_buf_7_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_ce1),
    .eroded_buf_7_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_we1),
    .eroded_buf_7_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_d1),
    .eroded_buf_8_address1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_address1),
    .eroded_buf_8_ce1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_ce1),
    .eroded_buf_8_we1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_we1),
    .eroded_buf_8_d1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_d1),
    .grp_fu_201_p_din0(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_din0),
    .grp_fu_201_p_din1(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_din1),
    .grp_fu_201_p_dout0(grp_fu_201_p2),
    .grp_fu_201_p_ce(grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_ce)
);

top_kernel_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4 grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start),
    .ap_done(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done),
    .ap_idle(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_idle),
    .ap_ready(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_ready),
    .morphology_stream_din(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_morphology_stream_din),
    .morphology_stream_full_n(morphology_stream_full_n),
    .morphology_stream_write(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_morphology_stream_write),
    .morphology_stream_num_data_valid(morphology_stream_num_data_valid),
    .morphology_stream_fifo_cap(morphology_stream_fifo_cap),
    .eroded_buf_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_address0),
    .eroded_buf_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_ce0),
    .eroded_buf_q0(eroded_buf_q0),
    .eroded_buf_1_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_1_address0),
    .eroded_buf_1_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_1_ce0),
    .eroded_buf_1_q0(eroded_buf_1_q0),
    .eroded_buf_2_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_2_address0),
    .eroded_buf_2_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_2_ce0),
    .eroded_buf_2_q0(eroded_buf_2_q0),
    .eroded_buf_3_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_3_address0),
    .eroded_buf_3_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_3_ce0),
    .eroded_buf_3_q0(eroded_buf_3_q0),
    .eroded_buf_4_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_4_address0),
    .eroded_buf_4_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_4_ce0),
    .eroded_buf_4_q0(eroded_buf_4_q0),
    .eroded_buf_5_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_5_address0),
    .eroded_buf_5_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_5_ce0),
    .eroded_buf_5_q0(eroded_buf_5_q0),
    .eroded_buf_6_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_6_address0),
    .eroded_buf_6_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_6_ce0),
    .eroded_buf_6_q0(eroded_buf_6_q0),
    .eroded_buf_7_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_7_address0),
    .eroded_buf_7_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_7_ce0),
    .eroded_buf_7_q0(eroded_buf_7_q0),
    .eroded_buf_8_address0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_8_address0),
    .eroded_buf_8_ce0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_8_ce0),
    .eroded_buf_8_q0(eroded_buf_8_q0),
    .grp_fu_201_p_din0(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_din0),
    .grp_fu_201_p_din1(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_din1),
    .grp_fu_201_p_dout0(grp_fu_201_p2),
    .grp_fu_201_p_ce(grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_ce)
);

top_kernel_mul_64ns_66ns_129_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 66 ),
    .dout_WIDTH( 129 ))
mul_64ns_66ns_129_5_1_U1620(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_201_p0),
    .din1(grp_fu_201_p1),
    .ce(grp_fu_201_ce),
    .dout(grp_fu_201_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start_reg <= 1'b1;
        end else if ((grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_ready == 1'b1)) begin
            grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_ready == 1'b1)) begin
            grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call38) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_ready == 1'b1)) begin
            grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_1_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_1_ce0;
    end else begin
        bilateral_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_1_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_ce1;
    end else begin
        bilateral_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_1_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_1_we1;
    end else begin
        bilateral_buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_2_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_2_ce0;
    end else begin
        bilateral_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_2_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_ce1;
    end else begin
        bilateral_buf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_2_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_2_we1;
    end else begin
        bilateral_buf_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_3_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_3_ce0;
    end else begin
        bilateral_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_3_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_ce1;
    end else begin
        bilateral_buf_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_3_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_3_we1;
    end else begin
        bilateral_buf_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_4_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_4_ce0;
    end else begin
        bilateral_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_4_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_ce1;
    end else begin
        bilateral_buf_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_4_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_4_we1;
    end else begin
        bilateral_buf_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_5_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_5_ce0;
    end else begin
        bilateral_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_5_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_ce1;
    end else begin
        bilateral_buf_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_5_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_5_we1;
    end else begin
        bilateral_buf_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_6_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_6_ce0;
    end else begin
        bilateral_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_6_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_ce1;
    end else begin
        bilateral_buf_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_6_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_6_we1;
    end else begin
        bilateral_buf_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_7_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_7_ce0;
    end else begin
        bilateral_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_7_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_ce1;
    end else begin
        bilateral_buf_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_7_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_7_we1;
    end else begin
        bilateral_buf_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_8_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_8_ce0;
    end else begin
        bilateral_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_8_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_ce1;
    end else begin
        bilateral_buf_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_8_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_8_we1;
    end else begin
        bilateral_buf_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bilateral_buf_ce0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_bilateral_buf_ce0;
    end else begin
        bilateral_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_ce1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_ce1;
    end else begin
        bilateral_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bilateral_buf_we1 = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_buf_we1;
    end else begin
        bilateral_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_1_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_1_ce0;
    end else begin
        eroded_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_1_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_ce1;
    end else begin
        eroded_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_1_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_1_we1;
    end else begin
        eroded_buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_2_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_2_ce0;
    end else begin
        eroded_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_2_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_ce1;
    end else begin
        eroded_buf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_2_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_2_we1;
    end else begin
        eroded_buf_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_3_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_3_ce0;
    end else begin
        eroded_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_3_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_ce1;
    end else begin
        eroded_buf_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_3_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_3_we1;
    end else begin
        eroded_buf_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_4_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_4_ce0;
    end else begin
        eroded_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_4_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_ce1;
    end else begin
        eroded_buf_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_4_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_4_we1;
    end else begin
        eroded_buf_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_5_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_5_ce0;
    end else begin
        eroded_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_5_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_ce1;
    end else begin
        eroded_buf_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_5_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_5_we1;
    end else begin
        eroded_buf_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_6_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_6_ce0;
    end else begin
        eroded_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_6_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_ce1;
    end else begin
        eroded_buf_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_6_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_6_we1;
    end else begin
        eroded_buf_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_7_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_7_ce0;
    end else begin
        eroded_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_7_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_ce1;
    end else begin
        eroded_buf_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_7_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_7_we1;
    end else begin
        eroded_buf_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_8_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_8_ce0;
    end else begin
        eroded_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_8_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_ce1;
    end else begin
        eroded_buf_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_8_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_8_we1;
    end else begin
        eroded_buf_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        eroded_buf_ce0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_eroded_buf_ce0;
    end else begin
        eroded_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_ce1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_ce1;
    end else begin
        eroded_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        eroded_buf_we1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_eroded_buf_we1;
    end else begin
        eroded_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_201_ce = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_201_ce = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_ce;
    end else begin
        grp_fu_201_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_201_p0 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_201_p0 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_din0;
    end else begin
        grp_fu_201_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_201_p1 = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_grp_fu_201_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_201_p1 = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_grp_fu_201_p_din1;
    end else begin
        grp_fu_201_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call38 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bilateral_stream_read = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_bilateral_stream_read;

assign grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_ap_start_reg;

assign grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start = grp_stage_morphology_Pipeline_EROSION_LOOP_VITIS_LOOP_304_1_fu_128_ap_start_reg;

assign grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start = grp_stage_morphology_Pipeline_READ_BILATERAL_fu_104_ap_start_reg;

assign morphology_stream_din = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_morphology_stream_din;

assign morphology_stream_write = grp_stage_morphology_Pipeline_DILATION_LOOP_VITIS_LOOP_332_4_fu_150_morphology_stream_write;

endmodule //top_kernel_stage_morphology
