-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ag_pipeline_baseline_noise_reduction is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    red_in_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    red_in_ce0 : OUT STD_LOGIC;
    red_in_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of ag_pipeline_baseline_noise_reduction is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv50_1C71C72 : STD_LOGIC_VECTOR (49 downto 0) := "00000000000000000000000001110001110001110001110010";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv49_0 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal r_1_reg_539 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal out_addr_reg_550 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal empty_fu_237_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_reg_558 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal select_ln14_3_fu_321_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln14_3_reg_563 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_3_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln7_fu_337_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln7_reg_575 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln10_fu_371_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln10_reg_588 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln9_fu_377_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sum_4_fu_445_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal c_reg_121 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln6_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal i_reg_133 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln7_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_reg_145 : STD_LOGIC_VECTOR (15 downto 0);
    signal j_reg_157 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln9_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_2_reg_168 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln14_fu_212_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_fu_366_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_92 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln6_fu_217_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal red_in_ce0_local : STD_LOGIC;
    signal out_r_we0_local : STD_LOGIC;
    signal select_ln14_1_fu_523_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_r_ce0_local : STD_LOGIC;
    signal mul_ln14_fu_180_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_5_fu_205_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln9_fu_233_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_242_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln14_fu_180_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal trunc_ln14_fu_255_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal sub_ln14_fu_259_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_fu_265_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_cast_fu_273_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_cast_fu_293_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln14_2_fu_303_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln14_1_fu_311_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln14_1_fu_315_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_7_cast2_fu_283_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln10_fu_349_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_fu_353_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_8_fu_359_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln11_1_fu_387_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_3_fu_391_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln11_1_fu_387_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln11_fu_383_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln11_2_fu_397_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sum_3_fu_391_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_411_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln11_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_1_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln11_fu_437_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln14_1_fu_453_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_fu_467_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_456_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln14_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln14_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln14_2_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln14_1_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln14_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln14_1_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln14_1_fu_517_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln14_fu_509_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln14_2_fu_464_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ag_pipeline_baseline_mul_24s_26ns_50_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (25 downto 0);
        dout : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;



begin
    mul_24s_26ns_50_1_1_U1 : component ag_pipeline_baseline_mul_24s_26ns_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 26,
        dout_WIDTH => 50)
    port map (
        din0 => shl_ln_fu_242_p3,
        din1 => mul_ln14_fu_180_p1,
        dout => mul_ln14_fu_180_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    c_reg_121_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                c_reg_121 <= add_ln7_reg_575;
            elsif (((icmp_ln6_fu_193_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                c_reg_121 <= ap_const_lv7_1;
            end if; 
        end if;
    end process;

    i_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln10_fu_343_p2 = ap_const_lv1_1))) then 
                i_reg_133 <= add_ln9_fu_377_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln7_fu_199_p2 = ap_const_lv1_0))) then 
                i_reg_133 <= ap_const_lv3_7;
            end if; 
        end if;
    end process;

    j_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_reg_157 <= add_ln10_reg_588;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln9_fu_227_p2 = ap_const_lv1_0))) then 
                j_reg_157 <= ap_const_lv3_7;
            end if; 
        end if;
    end process;

    r_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_fu_92 <= ap_const_lv7_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln7_fu_199_p2 = ap_const_lv1_1))) then 
                r_fu_92 <= add_ln6_fu_217_p2;
            end if; 
        end if;
    end process;

    sum_2_reg_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                sum_2_reg_168 <= sum_4_fu_445_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln9_fu_227_p2 = ap_const_lv1_0))) then 
                sum_2_reg_168 <= sum_reg_145;
            end if; 
        end if;
    end process;

    sum_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln10_fu_343_p2 = ap_const_lv1_1))) then 
                sum_reg_145 <= sum_2_reg_168;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln7_fu_199_p2 = ap_const_lv1_0))) then 
                sum_reg_145 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln10_reg_588 <= add_ln10_fu_371_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln7_reg_575 <= add_ln7_fu_337_p2;
                empty_reg_558 <= empty_fu_237_p2;
                select_ln14_3_reg_563 <= select_ln14_3_fu_321_p3;
                tmp_3_reg_569 <= select_ln14_3_fu_321_p3(12 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                out_addr_reg_550 <= zext_ln14_fu_212_p1(14 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_1_reg_539 <= r_fu_92;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, icmp_ln6_fu_193_p2, icmp_ln7_fu_199_p2, icmp_ln10_fu_343_p2, icmp_ln9_fu_227_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln6_fu_193_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln7_fu_199_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln9_fu_227_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln10_fu_343_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln10_fu_371_p2 <= std_logic_vector(signed(j_reg_157) + signed(ap_const_lv3_1));
    add_ln11_2_fu_397_p2 <= std_logic_vector(signed(sext_ln11_1_fu_387_p1) + signed(sext_ln11_fu_383_p1));
    add_ln11_fu_353_p2 <= std_logic_vector(signed(sext_ln10_fu_349_p1) + signed(c_reg_121));
    add_ln6_fu_217_p2 <= std_logic_vector(unsigned(r_fu_92) + unsigned(ap_const_lv7_1));
    add_ln7_fu_337_p2 <= std_logic_vector(unsigned(c_reg_121) + unsigned(ap_const_lv7_1));
    add_ln9_fu_377_p2 <= std_logic_vector(signed(i_reg_133) + signed(ap_const_lv3_1));
    and_ln11_fu_425_p2 <= (xor_ln11_fu_419_p2 and tmp_6_fu_411_p3);
    and_ln14_1_fu_503_p2 <= (xor_ln14_1_fu_497_p2 and tmp_1_fu_456_p3);
    and_ln14_2_fu_492_p2 <= (tmp_3_reg_569 and tmp_2_fu_467_p3);
    and_ln14_fu_486_p2 <= (xor_ln14_fu_480_p2 and or_ln14_fu_475_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln6_fu_193_p2)
    begin
        if ((((icmp_ln6_fu_193_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln6_fu_193_p2)
    begin
        if (((icmp_ln6_fu_193_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_237_p2 <= std_logic_vector(signed(sext_ln9_fu_233_p1) + signed(r_1_reg_539));
    icmp_ln10_fu_343_p2 <= "1" when (j_reg_157 = ap_const_lv3_2) else "0";
    icmp_ln6_fu_193_p2 <= "1" when (r_fu_92 = ap_const_lv7_7F) else "0";
    icmp_ln7_fu_199_p2 <= "1" when (c_reg_121 = ap_const_lv7_7F) else "0";
    icmp_ln9_fu_227_p2 <= "1" when (i_reg_133 = ap_const_lv3_2) else "0";
    mul_ln14_fu_180_p1 <= ap_const_lv50_1C71C72(26 - 1 downto 0);
    or_ln14_1_fu_517_p2 <= (and_ln14_fu_486_p2 or and_ln14_1_fu_503_p2);
    or_ln14_fu_475_p2 <= (tmp_3_reg_569 or tmp_2_fu_467_p3);
    out_r_address0 <= out_addr_reg_550;
    out_r_ce0 <= out_r_ce0_local;

    out_r_ce0_local_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_ce0_local <= ap_const_logic_1;
        else 
            out_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_r_d0 <= select_ln14_1_fu_523_p3;
    out_r_we0 <= out_r_we0_local;

    out_r_we0_local_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_r_we0_local <= ap_const_logic_1;
        else 
            out_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    red_in_address0 <= zext_ln11_fu_366_p1(14 - 1 downto 0);
    red_in_ce0 <= red_in_ce0_local;

    red_in_ce0_local_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            red_in_ce0_local <= ap_const_logic_1;
        else 
            red_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln11_fu_437_p3 <= 
        ap_const_lv16_7FFF when (and_ln11_fu_425_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln14_1_fu_523_p3 <= 
        select_ln14_fu_509_p3 when (or_ln14_1_fu_517_p2(0) = '1') else 
        sext_ln14_2_fu_464_p1;
    select_ln14_2_fu_303_p3 <= 
        tmp_6_cast_fu_273_p4 when (tmp_fu_265_p3(0) = '1') else 
        tmp_7_cast_fu_293_p4;
    select_ln14_3_fu_321_p3 <= 
        sub_ln14_1_fu_315_p2 when (tmp_fu_265_p3(0) = '1') else 
        tmp_7_cast2_fu_283_p4;
    select_ln14_fu_509_p3 <= 
        ap_const_lv16_7FFF when (and_ln14_fu_486_p2(0) = '1') else 
        ap_const_lv16_8000;
        sext_ln10_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(j_reg_157),7));

    sext_ln11_1_fu_387_p0 <= red_in_q0;
        sext_ln11_1_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln11_1_fu_387_p0),17));

        sext_ln11_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_2_reg_168),17));

        sext_ln14_1_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln14_3_reg_563),24));

        sext_ln14_2_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln14_3_reg_563),16));

        sext_ln9_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(i_reg_133),7));

    shl_ln_fu_242_p3 <= (sum_reg_145 & ap_const_lv8_0);
    sub_ln14_1_fu_315_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(zext_ln14_1_fu_311_p1));
    sub_ln14_fu_259_p2 <= std_logic_vector(unsigned(ap_const_lv49_0) - unsigned(trunc_ln14_fu_255_p1));
    sum_3_fu_391_p0 <= red_in_q0;
    sum_3_fu_391_p2 <= std_logic_vector(signed(sum_3_fu_391_p0) + signed(sum_2_reg_168));
    sum_4_fu_445_p3 <= 
        select_ln11_fu_437_p3 when (xor_ln11_1_fu_431_p2(0) = '1') else 
        sum_3_fu_391_p2;
    tmp_1_fu_456_p3 <= sext_ln14_1_fu_453_p1(23 downto 23);
    tmp_2_fu_467_p3 <= sext_ln14_1_fu_453_p1(15 downto 15);
    tmp_4_fu_403_p3 <= add_ln11_2_fu_397_p2(16 downto 16);
    tmp_5_fu_205_p3 <= (r_fu_92 & c_reg_121);
    tmp_6_cast_fu_273_p4 <= sub_ln14_fu_259_p2(47 downto 36);
    tmp_6_fu_411_p3 <= sum_3_fu_391_p2(15 downto 15);
    tmp_7_cast2_fu_283_p4 <= mul_ln14_fu_180_p2(48 downto 36);
    tmp_7_cast_fu_293_p4 <= mul_ln14_fu_180_p2(47 downto 36);
    tmp_8_fu_359_p3 <= (empty_reg_558 & add_ln11_fu_353_p2);
    tmp_fu_265_p3 <= sum_reg_145(15 downto 15);
    trunc_ln14_fu_255_p1 <= mul_ln14_fu_180_p2(49 - 1 downto 0);
    xor_ln11_1_fu_431_p2 <= (tmp_6_fu_411_p3 xor tmp_4_fu_403_p3);
    xor_ln11_fu_419_p2 <= (tmp_4_fu_403_p3 xor ap_const_lv1_1);
    xor_ln14_1_fu_497_p2 <= (ap_const_lv1_1 xor and_ln14_2_fu_492_p2);
    xor_ln14_fu_480_p2 <= (tmp_1_fu_456_p3 xor ap_const_lv1_1);
    zext_ln11_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_359_p3),64));
    zext_ln14_1_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln14_2_fu_303_p3),13));
    zext_ln14_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_205_p3),64));
end behav;
