

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "13737643", "EstimateLatencyMax" : "13737643",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_g", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_b", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "histogram", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "intensity", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "cdf", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "equalized", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "gaussian_kernel", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "gaussian_blurred", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "spatial_weights", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bilateral_filtered", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "eroded", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_30_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state2"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state3"], "OneDepthLoop" : "1", "OneStateBlock": "ap_ST_fsm_state2_blk"}},
			{"Name" : "VITIS_LOOP_35_5", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state50"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state3"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_34_4", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state51"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_55_6", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state52", "LastState" : ["ap_ST_fsm_state53"], "QuitState" : ["ap_ST_fsm_state52"], "PreState" : ["ap_ST_fsm_state51"], "PostState" : ["ap_ST_fsm_state54"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_64_8", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state63", "LastState" : ["ap_ST_fsm_state89"], "QuitState" : ["ap_ST_fsm_state63"], "PreState" : ["ap_ST_fsm_state62"], "PostState" : ["ap_ST_fsm_state62"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_63_7", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state62", "LastState" : ["ap_ST_fsm_state63"], "QuitState" : ["ap_ST_fsm_state62"], "PreState" : ["ap_ST_fsm_state61"], "PostState" : ["ap_ST_fsm_state90"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_88_12", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state93", "LastState" : ["ap_ST_fsm_state102"], "QuitState" : ["ap_ST_fsm_state93"], "PreState" : ["ap_ST_fsm_state92"], "PostState" : ["ap_ST_fsm_state92"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_87_11", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state92", "LastState" : ["ap_ST_fsm_state93"], "QuitState" : ["ap_ST_fsm_state92"], "PreState" : ["ap_ST_fsm_state91"], "PostState" : ["ap_ST_fsm_state91"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_84_10", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state91", "LastState" : ["ap_ST_fsm_state92"], "QuitState" : ["ap_ST_fsm_state91"], "PreState" : ["ap_ST_fsm_state90"], "PostState" : ["ap_ST_fsm_state90"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_83_9", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state90", "LastState" : ["ap_ST_fsm_state91"], "QuitState" : ["ap_ST_fsm_state90"], "PreState" : ["ap_ST_fsm_state62"], "PostState" : ["ap_ST_fsm_state103"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_108_16", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state107", "LastState" : ["ap_ST_fsm_state155"], "QuitState" : ["ap_ST_fsm_state107"], "PreState" : ["ap_ST_fsm_state106"], "PostState" : ["ap_ST_fsm_state106"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_107_15", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state106", "LastState" : ["ap_ST_fsm_state107"], "QuitState" : ["ap_ST_fsm_state106"], "PreState" : ["ap_ST_fsm_state105"], "PostState" : ["ap_ST_fsm_state156"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_102_14", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state104", "LastState" : ["ap_ST_fsm_state167"], "QuitState" : ["ap_ST_fsm_state104"], "PreState" : ["ap_ST_fsm_state103"], "PostState" : ["ap_ST_fsm_state103"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_101_13", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state103", "LastState" : ["ap_ST_fsm_state104"], "QuitState" : ["ap_ST_fsm_state103"], "PreState" : ["ap_ST_fsm_state90"], "PostState" : ["ap_ST_fsm_state168"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_134_20", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state172", "LastState" : ["ap_ST_fsm_state174"], "QuitState" : ["ap_ST_fsm_state172"], "PreState" : ["ap_ST_fsm_state171"], "PostState" : ["ap_ST_fsm_state171"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_133_19", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state171", "LastState" : ["ap_ST_fsm_state172"], "QuitState" : ["ap_ST_fsm_state171"], "PreState" : ["ap_ST_fsm_state170"], "PostState" : ["ap_ST_fsm_state169"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_130_18", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state169", "LastState" : ["ap_ST_fsm_state171"], "QuitState" : ["ap_ST_fsm_state169"], "PreState" : ["ap_ST_fsm_state168"], "PostState" : ["ap_ST_fsm_state168"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_129_17", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state168", "LastState" : ["ap_ST_fsm_state169"], "QuitState" : ["ap_ST_fsm_state168"], "PreState" : ["ap_ST_fsm_state103"], "PostState" : ["ap_ST_fsm_state175"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_150_24", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state180", "LastState" : ["ap_ST_fsm_state182"], "QuitState" : ["ap_ST_fsm_state180"], "PreState" : ["ap_ST_fsm_state179"], "PostState" : ["ap_ST_fsm_state179"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_149_23", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state179", "LastState" : ["ap_ST_fsm_state180"], "QuitState" : ["ap_ST_fsm_state179"], "PreState" : ["ap_ST_fsm_state178"], "PostState" : ["ap_ST_fsm_state183"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_146_22", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state177", "LastState" : ["ap_ST_fsm_state183"], "QuitState" : ["ap_ST_fsm_state177"], "PreState" : ["ap_ST_fsm_state176"], "PostState" : ["ap_ST_fsm_state184"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_145_21", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "188", "FirstState" : "ap_ST_fsm_state175", "LastState" : ["ap_ST_fsm_state188"], "QuitState" : ["ap_ST_fsm_state175"], "PreState" : ["ap_ST_fsm_state168"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.histogram_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.intensity_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.cdf_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.equalized_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gaussian_kernel_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gaussian_blurred_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.spatial_weights_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bilateral_filtered_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.eroded_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.faddfsub_32ns_32ns_32_5_full_dsp_1_U1", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fadd_32ns_32ns_32_5_full_dsp_1_U2", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_4_max_dsp_1_U3", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_4_max_dsp_1_U4", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fdiv_32ns_32ns_32_10_no_dsp_1_U5", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sitofp_32ns_32_4_no_dsp_1_U6", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fptrunc_64ns_32_2_no_dsp_1_U7", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fpext_32ns_64_2_no_dsp_1_U8", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U9", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dexp_64ns_64ns_64_15_full_dsp_1_U10", "Parent" : "0"}]}
