

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13", "14", "15", "16", "17", "18", "19", "20"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "3410116", "EstimateLatencyMax" : "3410116",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_r", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_top_kernel_Outline_VITIS_LOOP_17_1_fu_725", "Port" : "in_r", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "in_g", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_top_kernel_Outline_VITIS_LOOP_17_1_fu_725", "Port" : "in_g", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "in_b", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_top_kernel_Outline_VITIS_LOOP_17_1_fu_725", "Port" : "in_b", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "out_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "intensity", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "10", "SubInstance" : "grp_top_kernel_Outline_VITIS_LOOP_17_1_fu_725", "Port" : "intensity", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "histogram", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_top_kernel_Outline_VITIS_LOOP_61_3_fu_737", "Port" : "histogram", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "cdf", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "equalized", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "gaussian_kernel", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "gaussian_blurred", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "spatial_weights", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bilateral_filtered", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "eroded", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_67_5", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state10"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state3"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_66_4", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state11"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_78_6", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state12", "LastState" : ["ap_ST_fsm_state13"], "QuitState" : ["ap_ST_fsm_state12"], "PreState" : ["ap_ST_fsm_state11"], "PostState" : ["ap_ST_fsm_state14"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_87_8", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state23", "LastState" : ["ap_ST_fsm_state49"], "QuitState" : ["ap_ST_fsm_state23"], "PreState" : ["ap_ST_fsm_state22"], "PostState" : ["ap_ST_fsm_state22"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_86_7", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state22", "LastState" : ["ap_ST_fsm_state23"], "QuitState" : ["ap_ST_fsm_state22"], "PreState" : ["ap_ST_fsm_state21"], "PostState" : ["ap_ST_fsm_state50"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_115_12", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state53", "LastState" : ["ap_ST_fsm_state62"], "QuitState" : ["ap_ST_fsm_state53"], "PreState" : ["ap_ST_fsm_state52"], "PostState" : ["ap_ST_fsm_state52"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_114_11", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state52", "LastState" : ["ap_ST_fsm_state53"], "QuitState" : ["ap_ST_fsm_state52"], "PreState" : ["ap_ST_fsm_state51"], "PostState" : ["ap_ST_fsm_state51"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_110_10", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state51", "LastState" : ["ap_ST_fsm_state52"], "QuitState" : ["ap_ST_fsm_state51"], "PreState" : ["ap_ST_fsm_state50"], "PostState" : ["ap_ST_fsm_state50"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_109_9", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state50", "LastState" : ["ap_ST_fsm_state51"], "QuitState" : ["ap_ST_fsm_state50"], "PreState" : ["ap_ST_fsm_state22"], "PostState" : ["ap_ST_fsm_state63"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_151_18", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state67", "LastState" : ["ap_ST_fsm_state119"], "QuitState" : ["ap_ST_fsm_state67"], "PreState" : ["ap_ST_fsm_state66"], "PostState" : ["ap_ST_fsm_state66"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_150_17", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state66", "LastState" : ["ap_ST_fsm_state67"], "QuitState" : ["ap_ST_fsm_state66"], "PreState" : ["ap_ST_fsm_state65"], "PostState" : ["ap_ST_fsm_state120"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_144_16", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state64", "LastState" : ["ap_ST_fsm_state131"], "QuitState" : ["ap_ST_fsm_state64"], "PreState" : ["ap_ST_fsm_state63"], "PostState" : ["ap_ST_fsm_state63"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_143_15", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state63", "LastState" : ["ap_ST_fsm_state64"], "QuitState" : ["ap_ST_fsm_state63"], "PreState" : ["ap_ST_fsm_state50"], "PostState" : ["ap_ST_fsm_state132"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_188_22", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state136", "LastState" : ["ap_ST_fsm_state138"], "QuitState" : ["ap_ST_fsm_state136"], "PreState" : ["ap_ST_fsm_state135"], "PostState" : ["ap_ST_fsm_state135"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_187_21", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state135", "LastState" : ["ap_ST_fsm_state136"], "QuitState" : ["ap_ST_fsm_state135"], "PreState" : ["ap_ST_fsm_state134"], "PostState" : ["ap_ST_fsm_state133"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_183_20", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state133", "LastState" : ["ap_ST_fsm_state135"], "QuitState" : ["ap_ST_fsm_state133"], "PreState" : ["ap_ST_fsm_state132"], "PostState" : ["ap_ST_fsm_state132"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_182_19", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state132", "LastState" : ["ap_ST_fsm_state133"], "QuitState" : ["ap_ST_fsm_state132"], "PreState" : ["ap_ST_fsm_state63"], "PostState" : ["ap_ST_fsm_state139"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_205_26", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state143", "LastState" : ["ap_ST_fsm_state145"], "QuitState" : ["ap_ST_fsm_state143"], "PreState" : ["ap_ST_fsm_state142"], "PostState" : ["ap_ST_fsm_state142"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_204_25", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state142", "LastState" : ["ap_ST_fsm_state143"], "QuitState" : ["ap_ST_fsm_state142"], "PreState" : ["ap_ST_fsm_state141"], "PostState" : ["ap_ST_fsm_state140"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_200_24", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state140", "LastState" : ["ap_ST_fsm_state142"], "QuitState" : ["ap_ST_fsm_state140"], "PreState" : ["ap_ST_fsm_state139"], "PostState" : ["ap_ST_fsm_state139"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_199_23", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "145", "FirstState" : "ap_ST_fsm_state139", "LastState" : ["ap_ST_fsm_state140"], "QuitState" : ["ap_ST_fsm_state139"], "PreState" : ["ap_ST_fsm_state132"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.intensity_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.histogram_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.cdf_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.equalized_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gaussian_kernel_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gaussian_blurred_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.spatial_weights_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bilateral_filtered_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.eroded_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Outline_VITIS_LOOP_17_1_fu_725", "Parent" : "0", "Child" : ["11"],
		"CDFG" : "top_kernel_Outline_VITIS_LOOP_17_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "135297", "EstimateLatencyMax" : "135297",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_g", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "in_b", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "intensity", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_18_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "35", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state35"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_17_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "35", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Outline_VITIS_LOOP_17_1_fu_725.fdiv_32ns_32ns_32_10_no_dsp_1_U3", "Parent" : "10"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Outline_VITIS_LOOP_61_3_fu_737", "Parent" : "0",
		"CDFG" : "top_kernel_Outline_VITIS_LOOP_61_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "257", "EstimateLatencyMax" : "257",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "histogram", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_61_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state2"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "1", "OneStateBlock": "ap_ST_fsm_state2_blk"}}]},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.faddfsub_32ns_32ns_32_5_full_dsp_1_U10", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_4_max_dsp_1_U11", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fdiv_32ns_32ns_32_10_no_dsp_1_U12", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sitofp_32ns_32_4_no_dsp_1_U13", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fptrunc_64ns_32_2_no_dsp_1_U14", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fpext_32ns_64_2_no_dsp_1_U15", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fcmp_32ns_32ns_1_2_no_dsp_1_U16", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.dexp_64ns_64ns_64_15_full_dsp_1_U17", "Parent" : "0"}]}
